swiftlang/swift-foundation

- Sources/FoundationEssentials/Decimal/Decimal+Conformances.swift
- Sources/FoundationEssentials/Decimal/Decimal+Math.swift
- Tests/FoundationEssentialsTests/DecimalTests.swift
These SPIs will be used by swift-corelibs-foundation
> Implement Decimal .int64Value and .uint64Value SPIs

- Sources/FoundationEssentials/URL/URLParser.swift
- Tests/FoundationEssentialsTests/URLTests.swift
`URLParser`'s percent-decoding function used `String(validatingUTF8:)`, which would truncate the string if we had just decoded `%00` to NULL. Instead of using a NULL-terminated `OutputBuffer`, I switched to using `String(_validating:as:)`, which handles/accepts NULL characters in the buffer.
> Fix URL percent-decoding of %00

- Sources/FoundationEssentials/Decimal/Decimal+Compatibility.swift
- Sources/FoundationEssentials/Decimal/Decimal+Conformances.swift
- Sources/FoundationEssentials/Decimal/Decimal.swift
- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Very large number values, like 100e200 are technically valid JSON, and so are not flagged by the parsing layer as invalid. When decoded as a Decimal, which cannot hold this value, we need a signal that differentiates that the value is too large compared to the input being unparseable. This allows JSONDecoder to throw the correct kind of error instead of hitting a fatal error.
This also generalizes the parsing implementation on Collection<UTF8.CodeUnit> so that JSONDecoder doesn't have to instantiate a throw-away String.
> rdar://131793235 (Invalid JSON string causes precondition failure)

- Sources/FoundationEssentials/String/String+Comparison.swift
- Sources/FoundationInternationalization/CMakeLists.txt
- Sources/FoundationInternationalization/URLParser+ICU.swift
- Tests/FoundationInternationalizationTests/URLTests+UIDNA.swift
Add `UIDNAHookICU` to `FoundationInternationalization` to support IDNA coding hostnames for `URL` and `URLComponents` using `uidna` functions. Add a unit test.
> Port UIDNAHook to FoundationInternationalization

- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationEssentials/Predicate/PredicateExpression.swift
- Sources/FoundationInternationalization/CMakeLists.txt
- Sources/FoundationMacros/CMakeLists.txt
Previously, we had issues with import `Synchronization` in the toolchain - this was due to the rpaths of the produced libraries. We previously applied `-no-toolchain-stdlib-rpath` so that the rpath of the libraries in the build folder had no rpaths set. When the libraries are installed into the toolchain, `$ORIGIN` was appended which is correct for the installed library. However, XCTest's tests link against these libraries directly in the build folder before they are installed. Loading the stdlib worked because XCTest's tests also link the stdlib and so the library was found in the cache, however since XCTest's tests do not link `Synchronization` it wasn't found in the cache and since the rpaths list was empty the library couldn't be found.
Instead, we now remove the …
> Re-Add Synchronization Import on non-Darwin

- Sources/FoundationMacros/CMakeLists.txt
- cmake/modules/SwiftFoundationSwiftSupport.cmake
Ensure that we install any linker files for the modules which are required on certain platforms.
> build: install linker files for installed targets

- Sources/FoundationEssentials/SortComparator.swift
- Tests/FoundationEssentialsTests/SortComparatorTests.swift
With https://github.com/apple/swift-foundation/pull/740 I accidentally introduced a bug that made `AnySortComparator.==` infinitely recursive. This updates the `==` function to compare the underlying `_base` properties instead of recursing by comparing `lhs` and `rhs` themselves
> (132084216) Make AnySortComparator.== not infinitely recursive

- Sources/FoundationMacros/CMakeLists.txt
- cmake/modules/SwiftFoundationSwiftSupport.cmake
This reverts commit 590caaa097729a5f745636561846f523104744af.
This introduces a failure in the Ubuntu 20.04 test suite (e.g. https://ci.swift.org/job/oss-swift-pr-test-ubuntu-20_04/7131/).
> Revert "build: install linker files for installed targets (#753)"

- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
The previous ObjC implementation only set the `.busy` attribute value when true and omitted the key when false. This restores the historic behavior for compatibility with existing clients.
> Only provide .busy file attribute when true

- Sources/FoundationEssentials/Calendar/Calendar_Cache.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/Locale/Locale_Cache.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationEssentials/URL/URLParser.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_GMTICU.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_ICU.swift
- Sources/FoundationInternationalization/URLParser+ICU.swift
We currently use `_typeByName` to "up call" from types in FoundationEssentials to types in FoundationInternationalization (mainly for finding ICU-based versions of types defined in the essentials module). Now that swift-foundation exists in the toolchain, `_typeByName` is conflating the two versions of FoundationInternationalization when building a copy locally resulting in test crashes and failures. Instead, this transitions to the use of `@_dynamicReplacement` in order to swap out the up-call function at runtime for an implementation that returns the resulting type. Since the replacement implementation is statically type checked at compile time, it statically references the correct version of the type avoiding the failures.
> Use dynamic replacement instead of _typeByName for internationalization upcalls

- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
When an XDG environment variable is set, we should skip this test because it may impact the result of this test (where we'd prefer the XDG environment variable over the `HOME` environment variable)
> Skip testSearchPaths_XDGEnvironmentVariables when XDG environment is set

- CMakeLists.txt
- Package.swift
The new stdlib APIs that FoundationPredicateRegex relies upon are present in macOS 15 aligned releases, so we can update the availability accordingly. Additionally, while I was here I added the same "generation" logic to the CMake files as that in the Package manifest so adding/updating availability in the future is easier.
> Update availability release for FoundationPredicateRegex

- CMakeLists.txt
Fixes a minor typo introduced in the CMake files in https://github.com/apple/swift-foundation/pull/760
> Fix CMake availability macro typo

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
`URL.appending(path:directoryHint:)` currently percent-encodes `path` like any other full path, where `:` is percent-encoded in the first path segment. However, `path` is generally a relative component, and in that case, `:` is percent-encoded when it shouldn’t be.
> URL: Don't percent-encode an appended component as a first path segment

- Sources/FoundationEssentials/Decimal/Decimal+Compatibility.swift
- Sources/FoundationEssentials/Decimal/Decimal+Conformances.swift
- Sources/FoundationEssentials/Decimal/Decimal.swift
- Tests/FoundationEssentialsTests/DecimalTests.swift
NSDecimalString historically accepted Any as the second parameter, which could be either a Locale or a Dictionary. We should keep that behavior.
> Bin compat: NSDecimalString should accept dictionary in addition to locale

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Per the [`CreateFileW` documentation](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew):
> FILE_FLAG_BACKUP_SEMANTICS: You must set this flag to obtain a handle to a directory. A directory handle can be passed to some functions instead of a file handle.
This causes an error when attempting to read attributes of a directory (the API throws the `.fileReadNoPermission` error). This resolves an issue that prevents SwiftPM from functioning properly on Windows
> Enable reading attributes of directory on Windows

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Cherry pick of https://github.com/apple/swift-foundation/pull/773
Explanation: Fixes a regression caused by the foundation re-core in the result of `FileManager.attributesOfItem(atPath:)` for the `.type` key
Scope: Only impacts Windows results of this function
Original PR: https://github.com/apple/swift-foundation/pull/773
Risk: Minimal - this only impacts Windows, and we have a unit test in place that tests this change
Testing: Testing done via local unit testing and swift-ci testing
Reviewer: @compnerd
> [6.0] Correctly set .fileTypeSymlink on windows

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
When calculating file attributes for an item, we did not previously correctly detect symlinks on Windows. This updates the implementation to correctly detect symlinks and set the file type when populating the attributes dictionary.
> Correctly set .fileTypeSymlink on windows

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
This doesn't yet tackle _slowpath_unwrapFixedWidthInteger, but at least allows us to round-trip [U]Int128 with our own encoder and decoder.
> Bare minimum [U]Int128 support for JSON encode/decode

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Resolves https://github.com/apple/swift-foundation/issues/790 (thanks @nicklockwood for filing!)
We should not standardize the relative path outside of the context of its base URL, such as when calculating the absolute `.path()`. This allows us to properly handle `".."` segments at the beginning of the relative path, such as in
```
let baseURL = URL(filePath: "/docs/src/")
let result = URL(filePath: "../images/foo.png", relativeTo: baseURL)
XCTAssertEqual(result.path(), "/docs/images/foo.png")
```
Note that if the inputted path is absolute, e.g. `"/../images/foo.png"`, we should not resolve against the base URL. I've added a small unit test to cover both cases.
> URL: Don't standardize relative file paths

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
release/6 cherry pick of https://github.com/apple/swift-foundation/pull/792
Resolves #790
> [6.0] URL: Don't standardize relative file paths

- Sources/_FoundationCShims/CMakeLists.txt
When building this package locally via CMake using a toolchain that contains the _FoundationCShims module, you currently encounter errors like:
```
/usr/lib/swift/_FoundationCShims/module.modulemap:1:8: error: redefinition of module '_FoundationCShims'
1 | module _FoundationCShims {
|        `- error: redefinition of module '_FoundationCShims'
2 |     header "_FoundationCShims.h"
3 | 
/Repos/Public/swift-foundation/Sources/_FoundationCShims/include/module.modulemap:1:8: note: previously defined here
1 | module _FoundationCShims {
|        `- note: previously defined here
2 |     header "_FoundationCShims.h"
3 | 
```
To solve this, we add an explicit `-fmodule-map-file` flag to swift clients which causes clang to prefer the local module over the module from the SDK. SwiftPM already applies …
> [CMake] Resolve module map conflict with duplicate in SDK

- Sources/_FoundationCShims/CMakeLists.txt
Explanation: Allows building the project via CMake outside of the toolchain
Scope: Should only resolve an issue in local, non-toolchain CMake builds
Original PR: https://github.com/apple/swift-foundation/pull/789
Risk: Minimal - minor change to CMake that has been tested
Testing: Testing done via swift-ci toolchain builds and local, standalone CMake builds
Reviewer: @iCharlesHu
> [6.0] Add explicit modulemap path to take priority over modulemap from SDK

- Sources/FoundationMacros/CMakeLists.txt
This updates the macro library's rpath to reference the correct locations for the host and stldib libraries that it depends upon. This matches the rpath values for the existing macro libraries:
```
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../../../swift/linux:$ORIGIN/..]
```
I confirmed that using a locally built `libFoundationMacros.so` with this change successfully finds the required libraries rather than erroring out with `compiler plugin '/usr/lib/swift/host/plugins/libFoundationMacros.so' could not be loaded;  libswift_StringProcessing.so: cannot open shared object file: No such file or directory` like before
> [CMake] Fix macro install rpath

- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
A file manager's delegate is stored as a property of the `FileManager` itself, rather than as a property of the underlying `_FileManagerImpl` type. However, when creating this type I accidentally left a stray `delegate` property here that was unused. To Avoid confusion, remove the extra, unused property and the function that referenced it so that it's clear that only `FileManager.delegate` is used.
> Remove unneccessary _FileManagerImpl.delegate

- Sources/_FoundationCShims/platform_shims.c
This is necessary to get the `__wasilibc_get_environ` function declaration.
> Add explicit include of `wasi/libc-environ.h`

- Sources/FoundationEssentials/Error/ErrorCodes+POSIX.swift
WASI does not define the EREMOTE error code.
> Exclude EREMOTE definition for WASI platform

- Sources/FoundationEssentials/Data/Data+Writing.swift
WASI does not have temp directory concept, and does not provide mktemp family of functions, so attempting to create a temporary file should be considered a feature unsupported.
> Throw `.featureUnsupported` when attempting to create temp files on WASI

- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
The `operatingSystemVersion` property type is a tuple but the it was returning an `OperatingSystemVersion` instance on unknown platforms.
> Fix `operatingSystemVersion` on WASI

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
This commit guards out the extended attributes and file system attributes related code on WASI as WASI does not support these features. Just return nothing or ignore the set request.
> Guard out extended or fs attributes related code on WASI

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
WASI does not surface the sticky bit and getuid, so we cannot check whether the file is actually deletable before attempting to delete it.
> Skip sticky-bit check in `isDeletableFile` on WASI

- Sources/FoundationEssentials/FileManager/FileOperations.swift
WASI doesn't have `sendfile`, so we need to implement the copy in user space with `read` and `write`. It's not as efficient as `sendfile`, but it's the best we can do.
> Implement `_copyRegularFile` for WASI without `sendfile`

- Sources/FoundationMacros/CMakeLists.txt
Explanation: Fixes the rpath value for the Foundation macro library in the toolchain
Scope: Should only modify the rpath value for the macro library which is currently only built on linux
Original PR: https://github.com/apple/swift-foundation/pull/793
Risk: Minimal - minor change to fix an already-broken rpath value for a macro library which no other toolchain components are using yet
Testing: Testing done via local build and validation of the rpath as well as swift-ci toolchain builds and testing
Reviewer: @iCharlesHu
> [6.0] [CMake] Fix macro install rpath

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Support for round-tripping [U]Int128 through our JSON encoder + decoder.
Clone of https://github.com/apple/swift-foundation/pull/767 for 6.0
> [6.0] Int128 support in json

- Sources/FoundationEssentials/LockedState.swift
- Sources/FoundationEssentials/_ThreadLocal.swift
`wasm32-unknown-wasi` target does not have pthread API and is considered to be single-threaded, so skip actual locking on it.
> Port `LockedState` and `_ThreadLocal` to WASI without any locking

- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL/URL.swift
Resolves #807
`String(decoding:as:)` was including the null-terminator from the Windows API, and when this is passed to `URL`, it's encoded in the form `file:///C:/Users/alex%00/`. When enumerating the directory, we get the file system representation of the `URL`, which decodes `%00` to back to `\0`. This was causing us to append a file name `alex` to the directory, getting `file:///C:/Users/alex%00/alex`, which "exists" because it was only checking for the existence of `file:///C:/Users/alex`. This cycle repeats, causing an infinite loop in the enumerator.
This PR 1) replaces `String(decoding:as:)` with `String(decodingCString:as:)` in the home directory function and 2) prevents `URL.fileSystemPath` from decoding `%00` to `\0`.
> Prevent null character in Windows home directory

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/Formatting/BinaryInteger+FormatStyleTests.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
+ Bare minimum `[U]Int128` support for `JSONEncoderTests`
+ Add some more `testTypeCoercion` in `testTypeCoercion()`
+ Add some more check `[U]Int128` in `testNumericStringRepresentation_builtinIntegersLimits()`
+ Correct typo comment from `resovled` to `resolved` at `URL.swift`
+ Sources/FoundationEssentials/URL/URL.swift
+ Tests/FoundationEssentialsTests/Formatting/BinaryInteger+FormatStyleTests.swift
+ Tests/FoundationEssentialsTests/JSONEncoderTests.swift
> Adding some more tests for [U]Int128 in BinaryInteger+FormatStyleTests.swift  and JSONEncoderTests.swift

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Data/Data.swift
- Sources/FoundationEssentials/Date.swift
- Sources/FoundationEssentials/Decimal/Decimal+Math.swift
- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Sources/FoundationEssentials/Error/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/Formatting/BinaryInteger+NumericStringRepresentation.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/PropertyList/OpenStepPlist.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Formatting/Duration+Formatting.swift
This is a starting point for repairing WASI build.
`import var WASILibc.errno` patterns appeared in this change is to avoid ambiguous reference for `errno`, which is defined in both errno.h and WASILibc overlay Swift module (we need to fix it in overlay side anyway)
> Add WASI platform conditions for libc imports and word size

- Sources/FoundationEssentials/String/String+IO.swift
Add a compatibility path for apps which parse invalid UTF8 data and expect it to be automatically repaired instead of returning `nil`.
> Add compatibility path for invalid UTF8 data

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
With https://github.com/apple/swift-corelibs-foundation/pull/5045, Foundation now dynamically replaces the implementation of this function when it is present so there is no need to perform a `_typeByName` lookup. We can safely remove this now and just return `nil` because we know that if this implementation is used, (the correct) Foundation is not loaded.
> Remove _typeByName lookup of _FoundationNSNumberInitializer

- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL/URL.swift
**Explanation:** Prevents a null-terminator from the Windows home directory API from ending up in the resulting `String` or `URL`. Prevents `%00` from being decoded to `\0` when getting a `URL`'s `fileSystemPath`, which is often converted to a C string for file system calls.
**Scope:** Windows-only change from `String(decoding:)` to `String(decodingCString:)` for `homeDirectoryPath(forUser:)`. Not decoding `%00` occurs for file paths of `URL`s on all platforms.
**Original PR:** https://github.com/apple/swift-foundation/pull/808
**Risk:** Low. Minor changes to prevent unexpected behavior when null-characters are included in file paths. The respective Windows APIs null-terminate their output, so `String(decodingCString:)` is safe.
**Testing:** swift-ci testing and local testing on Windows …
> [6.0] Prevent null character in Windows home directory

- Sources/FoundationEssentials/Data/Data.swift
This adds a hook for `FoundationNetworking` to override in order to support an up-call for cases where `Data` needs to read from a non-file URL
> Add FoundationNetworking hook for reading contents of remote URL

- Package.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
Explanation: Upgrade SwiftFoundationICU dependency 74, which aligns with macOS Sonoma
Scope: update Package.swift to fetch the new ICU
Original PR: https://github.com/apple/swift-foundation/pull/802
Risk: minimum. Only Package.swift and test files are affected
Testing: Testing done via local SwiftPM tests and swift-ci tests to ensure the new ICU works with SwiftFoundation
Reviewer: @jmschonfeld
> [6.0] Upgrade SwiftFoundationICU to version 74

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Fixup from previous change here. Like the previous version of this code, we should immediately throw an error if we fail to decode any Double from the buffer. We'll evaluate if it's expected to be the "wrong" integer only if it succeeds.
The previous fix caused a preconditionFailure crash since we'd fall through to the `validateNumber` function for a valid syntax JSON number.
> rdar://132940984 (Regression: Swift Decoding of Double.greatestFiniteMagnitude as Int causes a crash)

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Explanation: Restores previous behavior of throwing an error when a JSON floating point number (during slow-path integer parsing) fails to decode as `Double`.
Scope: Limited to JSONDecoder usages that attempt to parse very large floating point numbers as integers.
Original PR: https://github.com/apple/swift-foundation/pull/827
Risk: Minimal - fixes a regression that introduced an unexpected preconditionFailure
Reviewer: @itingliu
> [6.0] rdar://132940984 (Regression: Swift Decoding of Double.greatestFiniteMagnitude as Int causes a crash) (#827)

- Sources/_FoundationCShims/include/_CStdlib.h
…c++ interop enabled
Works around https://github.com/swiftlang/swift/issues/75720
> do not import stdatomic as it doesn't work with c++ interop on windows

- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/WASILibc+Extensions.swift
- Sources/_FoundationCShims/include/platform_shims.h
This change adds platform shims for `clock_gettime` so that we can use it in Swift code even when the clock id macros can't be imported through ClangImporter like wasi-libc's definitions.
Also wasi-libc's `timespec.tv_sec` and `timespec.tv_nsec` are not imported as `Int` in Swift, so we need to cast them to `UInt64` before doing arithmetic operations on them.
> Use platform shims for clock_gettime to support wasi-libc

- Sources/FoundationEssentials/FileManager/FileOperations.swift
The `st_blksize` field in `stat` struct is not provided by WASI, so we fall back to a default chunk size 4KB, which is a common page size. Otherwise, the below `read` and `write` loop won't progress.
> [wasm] Fall back to a default chunk size when `st_blksize` is not available

- Sources/FoundationEssentials/Data/Data.swift
Explanation: Adds a hook point for FoundationNetworking to allow `Data(contentsOf:)` to perform a remote URL request to fetch data
Scope: Should only impact calling `Data(contentsOf:)` with a non-file URL, turning an error into non-regressed behavior (but is inert without the matching SCL-F change)
Original PR: https://github.com/apple/swift-foundation/pull/820
Risk: Minimal - fixes a regression where the current behavior is just to `throw`, and fairly limited scope
Reviewer: @iCharlesHu
> [6.0] Add FoundationNetworking hook for reading contents of remote URL

- Foundation_Build_Process.md
Updates our build process documentation to note that `swift package update` may be required to fetch the latest copy of swift-foundation-icu when updating your swift-foundation checkout.
> Add note about 'swift package update' to build process documentation

- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
Explanation: fix ProcessInfo.processName for Windows by using existing `String.lastPathComponent`
Scope: Limited to `ProcessInfo._getProcessName`
Original PR: https://github.com/apple/swift-foundation/pull/839
Risk: Minimal - no new code introduced since we are replying on existing code.
Reviewer: @jmschonfeld
> [6.0] Fix ProcessInfo.processName for Windows (#839)

- CMakeLists.txt
This enables whole module optimization for FoundationEssentials and FoundationInternationalization for release builds. We've found that this added optimization results in a _significant_ (up to 4x) performance improvement for `JSONDecoder` in our benchmarks:
```
----------------------------------------------------------------------------------------------------------------------------
Canada-decodeFromJSON metrics
----------------------------------------------------------------------------------------------------------------------------
╒══════════════════════════════════════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╕
│          Throughput (# / s) (K)          │      p0 │     p25 │     p50 │     p75 │     p90 │     p99 │    p100 │ Samples │ …
```
> Enable WMO

- CMakeLists.txt
Explanation: Enables WMO in release builds
Scope: Should only impacts release builds for non-Windows
Original PR: https://github.com/apple/swift-foundation/pull/832
Risk: Minimal - enables WMO as a performance optimization, behavior should not change
Reviewer: @glessard
> [6.0] Enable WMO

- CMakeLists.txt
- Sources/CMakeLists.txt
- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationMacros/CMakeLists.txt
Use `ExternalProject` to switch FoundationMacros to cross-compilation. This allows us to build the macros for the right OS/architecture when cross-compiling Foundation for other environments.
> FoundationMacros: use cross-compilation to build for host

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/WASILibc+Extensions.swift
- Sources/_FoundationCShims/include/platform_shims.h
For now wasi-libc does not include fts(3) implementation, so mark features depending on it as unsupported on WASI. Once wasi-libc includes fts or we decide to implement and maintain our own fts-like API, we can remove these `#if os(WASI)` guards. 
I'm working on porting FTS to wasi-libc (https://github.com/WebAssembly/wasi-libc/pull/522), and we can share most of the enumerator code with other posix platforms after that.
Also, wasi-libc defines some constants in a way that ClangImporter can't understand, so we need to grab them manually through _FoundationCShims in function call form.
> Port directory enumeration related code to WASI

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Date.swift
- Sources/FoundationEssentials/Decimal/Decimal+Math.swift
- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Sources/FoundationEssentials/Error/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/Formatting/BinaryInteger+NumericStringRepresentation.swift
- Sources/FoundationEssentials/LockedState.swift
- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/PropertyList/OpenStepPlist.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationEssentials/_ThreadLocal.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Date+ICU.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
- Sources/FoundationInternationalization/Formatting/Duration+Formatting.swift
Adding MUSL support to Swift-Foundation to get the Swift static SDK building again after the swift-corelibs-foundation recore.
Cherry-picked from 6.0: https://github.com/apple/swift-foundation/pull/838
> [main] Get Swift-Foundation building against MUSL for Swift Static SDK

- Sources/FoundationEssentials/Decimal/Decimal+Math.swift
- Tests/FoundationEssentialsTests/DecimalTests.swift
Upcast numbers to higher bitwidth before performing calculations.
resolves: rdar://133458109
resolves: https://github.com/apple/swift-foundation/issues/595
> Resolved an arithmetic overflow error in Decimal division caused by improper upcasting

- Tests/FoundationEssentialsTests/ResourceUtilities.swift
SwiftPM used to incorrectly build tests for both host and target. That has been fixed by https://github.com/swiftlang/swift-package-manager/pull/7879.
The fix makes sure that if there are any direct macro dependencies in test targets xctest bundle is only built for "host".
This means that the hard-coded resources path needs to be updated to include "-tool" suffix.
> Fix hard-coded path to `FoundationEssentialsTests` resources

- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Tests/FoundationEssentialsTests/ProcessInfoTests.swift
Windows GetEnvironmentStringsW API can return magic environment variables set by the cmd shell that starts with "=". We should hide these values to avoid surprising behavior.
resolves: https://github.com/apple/swift-foundation/issues/847
> Hide Windows magic environment values from ProcessInfo.environment

- Tests/FoundationEssentialsTests/DecimalTests.swift
This test assumes `Int` is 64 bits.
resolves: rdar://133957938
> Add requirements to only run DecimalTests.testCrashingDivision on 64 bit devices

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/CodableUtilities.swift
- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Data/Data.swift
- Sources/FoundationEssentials/Date.swift
- Sources/FoundationEssentials/Decimal/Decimal+Math.swift
- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Sources/FoundationEssentials/Error/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/Formatting/BinaryInteger+NumericStringRepresentation.swift
- Sources/FoundationEssentials/LockedState.swift
- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/PropertyList/OpenStepPlist.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationEssentials/_ThreadLocal.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Date+ICU.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
- Sources/FoundationInternationalization/Formatting/Duration+Formatting.swift
Also, use `canImport()` wherever importing APIs, reserving `os(Android)` for platform differences.
I've started porting this repo to Android: this is a first pull that keeps everything building while more narrowly scoping imports.
@compnerd and @hyp, try it out and let me know what you think.
> [Android] Use the Bionic module in more places

- CMakeLists.txt
- Sources/CMakeLists.txt
- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationMacros/CMakeLists.txt
Use `ExternalProject` to switch FoundationMacros to cross-compilation. This allows us to build the macros for the right OS/architecture when cross-compiling Foundation for other environments.
> FoundationMacros: use cross-compilation to build for host (#714)

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
On macOS/Linux, when asking for the home directory of a user that doesn't exist, we fallback to `/var/empty` - we also have a handful of unit tests in swift-corelibs-foundation that verify this behavior. However, on Windows we currently crash with a `fatalError` when provided a non-existent user name. swift-corelibs-foundation previously defaulted to `/var/empty` on Windows too, but that directory doesn't make sense on Windows. Instead, we standardize on a fallback of `%SystemDrive%\Users\Public` for users that don't exist which is still a valid directory and is close enough to the macOS/Linux semantics despite not having a direct equivalent to `/var/empty`
> Use fallback home directory on Windows

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Date.swift
- Sources/FoundationEssentials/Decimal/Decimal+Math.swift
- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Sources/FoundationEssentials/Error/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/Formatting/BinaryInteger+NumericStringRepresentation.swift
- Sources/FoundationEssentials/LockedState.swift
- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/PropertyList/OpenStepPlist.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationEssentials/_ThreadLocal.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Date+ICU.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
- Sources/FoundationInternationalization/Formatting/Duration+Formatting.swift
This adds the missing imports to get Swift-Foundation building against Musl so we can get the static SDK going again.
> Get Swift-Foundation building for Musl/Static SDK

- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Currently `URL.fileSystemPath` only drops the last trailing slash. It should drop all of them so that we get:
```
let path = “/path///“
let url = URL(filePath: path)
print(url.fileSystemPath) // "/path" (previously "/path//" having one less trailing slash)
```
> URL.fileSystemPath should drop all trailing slashes

- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerPlayground.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
While getting SCL-F tests up and running on Windows, I noticed that those tests expose a handful of behavioral changes that swift-foundation made compared to swift-corelibs-foundation specifically around handling symlinks on Windows. In particular:
- `contentsEqual(atPath:andPath:)` would compare contents at the destination of symlinks rather than at the symlinks themselves
- `copyItem(atPath:toPath:)` would fail when copying symlinks
- `copyItem(atPath:toPath:)` would follow symlinks to directories and copy the directory contents rather than copying the symlinks themselves
This PR addresses these issues and adds a handful of unit tests to validate all of these behaviors.
Resolves https://github.com/apple/swift-foundation/issues/845
> Fix Windows symlink handling in FileManager APIs

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Explanation: Restores Swift 5.10 behavior for getting a home directory for a non-existent user on Windows (using a reasonable default rather than asserting)
Scope: Only impacts looking up home directories for non-existent users on Windows and turns a crash into a successful return value
Original PR: https://github.com/apple/swift-foundation/pull/854
Risk: Minimal - scope is very small and it restores pre-recore behavior
Reviewer: @compnerd @iCharlesHu
> [6.0] Use fallback home directory on Windows

- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerPlayground.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Explanation: Fixes issues handling symlinks on Windows
Scope: Only impacts a few `FileManager` APIs on Windows when operating on symlinks
Original PR: https://github.com/apple/swift-foundation/pull/858
Risk: Low - well tested change with limited scope
Testing: Testing done via local testing and testing in swift-ci via unit tests
Reviewer: @compnerd @itingliu
> [6.0] Fix Windows symlink handling in FileManager APIs

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
As a followup to https://github.com/apple/swift-foundation/pull/858, I've also noticed that `FileManager.fileExists(atPath:)` does not correctly handle symlinks on Windows. On Darwin/Linux this function determines if the destination of the symlink exists, but on Windows it currently checks whether the symlink itself exists. This updates the logic to follow the symlink and check the destination instead to match previous (swift 5.10) Windows behavior (and behavior on Darwin/Linux)
> FileManager.fileExists(atPath:) should follow symlinks on Windows

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
When looking up a home directory for a specific user, we currently have a bug that results in always using the fallback path. This PR updates the implementation to:
- Expect `LookupAccountNameW` and `RegGetValueW` to fail at the first call with an empty buffer (since there is no space in the buffer and it needs to return a valid buffer size
- Fix a minor typo in the registry key that ensures we interpolate the user name rather than putting the literal `\(String(decodingC...` text into the key string
The added unit test ensures we exercise this code path
> Fix Windows home directory for specific user

- CMakeLists.txt
- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationInternationalization/CMakeLists.txt
`_WASI_EMULATED_XXX` macros require linking against the corresponding emulation libraries. This patch adds `-Xfrontend -public-autolink-library` flags to the Swift compiler invocation to automatically link against the emulation libraries. Also enable getpid emulation explicitly, as it is available by default but emiting a warning.
> Autolink wasi-libc emulation libraries

- Sources/FoundationEssentials/Decimal/Decimal+Math.swift
- Tests/FoundationEssentialsTests/DecimalTests.swift
Explanation: resolves an arithmetic overflow error in Decimal division that can lead to crash with specific inputs.
Scope: Only impact Decimal division
Original PR: https://github.com/apple/swift-foundation/pull/850
Risk: Minimal - scope is very small (one line)
Reviewer: @jmschonfeld
> [6.0] Resolved an arithmetic overflow error in Decimal division caused by improper upcasting (#850)

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
If a user supplies a `path` with trailing slash(es) and hints that it's `.notDirectory`, we should take their word for it and strip all trailing slashes. While that user input is slightly contradictory, this was the behavior before the Swift URL implementation, and at least it maintains the following consistency for any `path`:
```
let url = URL(filePath: path, directoryHint: .notDirectory)
XCTAssertEqual(url.hasDirectoryPath, false)
```
> URL(filePath: path, directoryHint: .notDirectory) should strip trailing slashes

- Sources/_FoundationCShims/include/_CStdlib.h
It seems like we don't use neither setjmp nor longjmp in the Foundation codebase, so we can safely remove this include.
The main motivation for this change is to fix the build with the latest wasi-libc version. Recent wasi-libc versions started to provide `setjmp.h` header but it raises compilation errors unless Exception Handling feature (still under standardization process) is enabled.
See https://github.com/WebAssembly/wasi-libc/blob/wasi-sdk-22/libc-top-half/musl/include/setjmp.h
> Remove the `#include <setjmp.h>` from `_CStdlib.h`

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Explanation: Fixes a behavioral regression in Swift 6 for `FileManager.fileExists(atPath:)` when given symlinks
Scope: Only impacts this API on Windows
Original PR: https://github.com/apple/swift-foundation/pull/859
Risk: Minimal - well tested change with minimal scope
Testing: Testing done via local testing and testing in swift-ci
Reviewer: @compnerd @itingliu
> [6.0] FileManager.fileExists(atPath:) should follow symlinks

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Explanation: Fixes a behavioral regression in Swift 6 for getting the home directory of a specific user
Scope: Only impacts this API on Windows
Original PR: https://github.com/apple/swift-foundation/pull/861
Risk: Minimal - well tested change with minimal scope
Testing: Testing done via local testing and testing in swift-ci
Reviewer: @compnerd @itingliu
> [6.0] Fix Windows home directory for specific user

- Foundation_Build_Process.md
Fix typo issue at Foundation_Build_Process.md
> [docs] Fix typo issue at Foundation_Build_Process.md

- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
This should hopefully be the last of the Windows FileManager fixups for now 🙂
A swift-corelibs-foundation test revealed that `subpathsOfDirectory(atPath: "")` throws on Darwin/Linux but returns an empty array on Windows. We should make it behave the same by throwing an error (however Windows currently throws `.fileReadInvalidFileName` for empty paths unlike Darwin/Linux which reports that the file doesn't exist, so we maintain that consistency with other APIs here)
> subpathsOfDirectory(atPath:) should throw on empty paths

- Evolution.md
- Sources/FoundationEssentials/URL/URL.swift
+ Update the wording from `other API` to `other APIs`.
+ Update the link of `swift-evolution`.
> Update wording and link in evolution.md

- Package.swift
Originally, we added this conditional because `RegexBuilder` was not available on Windows. However CI has been successfully running these tests for some time now, so we no longer need the conditional. This simplifies the manifest a bit to remove the unnecessary logic.
> Remove RegexBuilder conditional in Package manifest

- Sources/FoundationEssentials/Decimal/Decimal+Compatibility.swift
Rationale: @_cdecl emits a C symbol that calls back to the Swift symbol. These new swift symbols does not exist on older OSs, causing a crash due to sym bol not found. Instead of using @_cdecl to implement public methods directly, use it on an internal type so it will not introduce unexpected public symbols.
resolves: rdar://133371820
> Decimal bin compat: remove the usage of @_cdecl from 'public' methods defined in NSDecimal.h

- Sources/FoundationEssentials/URL/URLComponents.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Resolves https://github.com/apple/swift-foundation/issues/828 (thanks @giginet for filing!)
Because the bridging code assigns non-percentEncoded variants of the components (e.g. `.path` instead of `.percentEncodedPath`), an `NSURLComponents` that is bridged to Swift `URLComponents` loses its percent-encoding. For example:
```
let nsURLComponents = NSURLComponents(
string: "https://example.com?url=https%3A%2F%2Fapple.com"
)!
let urlComponents = nsURLComponents as URLComponents
print(nsURLComponents.string) // "https://example.com?url=https%3A%2F%2Fapple.com"
print(urlComponents.string) // "https://example.com?url=https://apple.com"
```
Note we only lose percent-encoding if the percent-encoding is not absolutely required, e.g. `"://"` does not require encoding in the query component, but …
> Fix NSURLComponents bridging with percent-encoding

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Before this change, `URL.host` would just call `.host()`, which defaults to `.host(percentEncoded: true)`. This meant that if the host was IDNA-encoded, `.host` would decode the IDNA-encoding and then percent-encode, returning the percent-encoded string.
This PR fixes `.host` to match the behavior before the Swift URL implementation:
- If the host was percent-encoded, return the percent-decoded host
- If the host was IDNA-encoded (or not encoded at all), return that host string
This is exactly the behavior of `.host(percentEncoded: false)`, which is now used instead of `.host()`.
Resolves #863 (thanks @Lukasa!)
> URL.host should not return percent-encoded host

- Benchmarks/Benchmarks/Formatting/BenchmarkFormatting.swift
- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Cache.swift
- Sources/FoundationEssentials/Formatting/FormatterCache.swift
- Sources/FoundationEssentials/Locale/Locale.swift
- Sources/FoundationEssentials/Locale/Locale_Autoupdating.swift
- Sources/FoundationEssentials/Locale/Locale_Cache.swift
- Sources/FoundationEssentials/Locale/Locale_Notifications.swift
- Sources/FoundationEssentials/LockedState.swift
- Sources/FoundationEssentials/String/String+Internals.swift
- Sources/FoundationEssentials/TimeZone/TimeZone.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ObjC.swift
- Sources/FoundationInternationalization/Formatting/Number/ICUNumberFormatter.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Sources/FoundationInternationalization/Locale/Locale_ObjC.swift
Re-apply the diff from #719 (reverted in #744). We discovered the root cause was use of ICU's ability to set the malloc functions used, which can race. We will be disabling those in swift-foundation-icu soon. In the meantime, we know that they are not used on Linux so this patch is safe.
> Formatting performance improvements

- Sources/FoundationEssentials/URL/URLParser.swift
- Tests/FoundationEssentialsTests/URLTests.swift
The common (but not standardized) way to represent an "HTTP over Unix socket" URL is to use the scheme `http+unix` and set the URL's host to the percent-encoded path of the socket, e.g.
`http+unix://%2Fvar%2Frun%2Fdocker.sock/info`
Before the swift-corelibs-foundation re-core, `URLComponents` would always percent-encode the `.host`, so this worked as expected. After the re-core, `URLComponents` now supports and favors IDNA-encoding of the host, breaking this use case.
This PR special-cases the `http+unix` and `https+unix` schemes to percent-encode the host like before.
> URLComponents: support http(s)+unix schemes

- Sources/FoundationEssentials/Locale/CMakeLists.txt
https://github.com/apple/swift-foundation/pull/884 added Locale_Notifcations.swift but didn't include it in the FoundationEssentials library resulting in build failures. Adding it now.
> [cmake] Add missing locale_notifications.swift

- Tests/FoundationEssentialsTests/ResourceUtilities.swift
- Explanation:
The hard-coded resource directory path needs to account for the fact that sometimes tests are only build for the "host". So the changes try to find "-tool" prefixed directory first and if it exists, use it.
- Main Branch PR: https://github.com/apple/swift-foundation/pull/855
- Risk: Very Low (only tests of foundation are effected).
- Reviewed By: @jmschonfeld 
- Testing: Manual.
(cherry picked from commit d14ceaf88961afce40fd34bd51c3296fbdcbb012)
> [6.0] Fix hard-coded path to `FoundationEssentialsTests` resources

- Sources/FoundationEssentials/String/String+Essentials.swift
At String+Essentials.swift, correct available version macOS  is`10.10`  (release on 2014), not `10.0`(release on 2001).
> Correct available version macOS 10.10 for String+Essentials.swift

- Sources/FoundationEssentials/AttributedString/AttributeScope.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringAttribute.swift
- Sources/FoundationEssentials/AttributedString/FoundationAttributes.swift
- Sources/FoundationEssentials/Data/Data.swift
- Sources/FoundationEssentials/FileManager/SwiftFileManager.swift
- Sources/FoundationEssentials/Predicate/Predicate.swift
- Sources/FoundationEssentials/Predicate/PredicateBindings.swift
- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationInternationalization/Formatting/Number/NumberFormatStyleConfiguration.swift
- Sources/FoundationInternationalization/String/KeyPathComparator.swift
- Tests/FoundationInternationalizationTests/SortDescriptorTests.swift
`@_nonSendable` was designed as a detail for the compiler to use and was not intended to be written directly in source. As such, the compiler treats it slightly differently and has allowed us to commit some incorrect annotations, such as:
```swift
@_nonSendable
open class FileManager : @unchecked Sendable {
```
(a both non-sendable and unchecked-sendable class)
and
```swift
@_nonSendable
public struct KeyPathComparator<Compared>: SortComparator {
```
(a non-sendable struct that conforms to a `Sendable` protocol)
This PR replaces usages of `@_nonSendable` with the officially supported design (unavailable extensions). This has the drawbacks of needing to duplicate the type's availability and moving the non-sendable annotation away from the type itself, but it means that both of the errors …
> Change @_nonSendable to unavailable extensions

- Sources/FoundationMacros/CMakeLists.txt
When `FoundationMacros` was moved into its own CMake project, we did not copy over the `SWIFT_SYSTEM_NAME` setting. This results in the rpath for `libFoundationMacros.so` being `$ORIGIN/../../../swift/:$ORIGIN/..` instead of the correct value (`$ORIGIN/../../../swift/linux:$ORIGIN/..` for linux, for example). This fixes the macro build which allows `#Predicate` and `#Expression` to work as expected.
(note for context that this set value is used on line 90 of this file: `INSTALL_RPATH "$ORIGIN/../../../swift/${SWIFT_SYSTEM_NAME}:$ORIGIN/.."`)
> Set `SWIFT_SYSTEM_NAME` for macro project in CMake

- Sources/FoundationMacros/CMakeLists.txt
Explanation: A configuration change that updates the rpath value of `libFoundationMacros.so` to be correct
Scope: Only impacts the rpath value of `libFoundationMacros.so`
Original PR: https://github.com/apple/swift-foundation/pull/896
Risk: Low - scope is narrow, and fixes a regression that causes the macro to not be loadable so it can't really make anything worse :)
Testing: Testing done via local testing
Reviewer: @parkera
> [6.x] Set SWIFT_SYSTEM_NAME for macro project in CMake

- Tests/FoundationEssentialsTests/ResourceUtilities.swift
A cherry-pick of https://github.com/apple/swift-foundation/pull/855 to `release/6.0.1`, this change has already been cherry-picked to `release/6.0` via https://github.com/apple/swift-foundation/pull/887 but it appears the underlying change causing the failure is present in the 6.0.1 toolchain resulting in CI failures for `release/6.0.1` PRs
> [6.0.1] Fix hard-coded path to `FoundationEssentialsTests` resources

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
**Explanation:** Fixes `URL.host` to match the behavior before the Swift URL implementation:
- If the host was percent-encoded, return the percent-decoded host
- If the host was IDNA-encoded (or not encoded at all), return that host string
**Scope:** Only impacts deprecated (but still used) `URL.host` for URLs with an encoded host, restoring previous behavior
**Original PR:** https://github.com/apple/swift-foundation/pull/875
**Risk:** Low - minimal scope, one line change to restore behavior
**Testing:** Local, swift-ci, stable in `main` for 2 weeks
**Reviewer:** @parkera @jmschonfeld
> [6.0] URL.host should not return percent-encoded host

- Sources/FoundationEssentials/URL/URLParser.swift
- Tests/FoundationEssentialsTests/URLTests.swift
**Explanation:** Percent-encode the host (instead of IDNA-encoding) for URLs with the `http+unix` or `https+unix` scheme, supporting the common representation of a "HTTP over Unix socket" URL. This fixes `http(s)+unix`-related regressions in clients such as Vapor and AsyncHTTPClient (see https://github.com/apple/swift-foundation/issues/863 and https://github.com/swift-server/async-http-client/issues/767)
**Scope:** Only impacts `http+unix` and `https+unix` URLs, adds them to the set of `schemesToPercentEncodeHost`
**Original PR:** https://github.com/apple/swift-foundation/pull/883
**Risk:** Low - narrow scope, added special casing of two schemes to a larger set that has been well tested
**Testing:** Local, swift-ci, stable in `main` for 2 weeks, verified to fix …
> [6.0] URLComponents: support http(s)+unix schemes

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
Paths like /home/ would return "" instead of /
> Fix deleteLastPathComponent() for paths with trailing /

- Tests/FoundationEssentialsTests/ProcessInfoTests.swift
visionOS's version number is indeed lower than 5.
resolves: rdar://134731230
> ProcessInfoTests.testOperatingSystemIsAtLeastVersion should not run on visionOS

- Sources/FoundationEssentials/Decimal/Decimal+Compatibility.swift
- Sources/FoundationEssentials/Decimal/Decimal+Math.swift
- Tests/FoundationEssentialsTests/DecimalTests.swift
Historically Decimal has never supported negative power and will reproduce unexpected results
resolves: rdar://133875543
> Implement negative power support to pow(_ x: Decimal, _ y: Int). 

- Sources/FoundationMacros/CMakeLists.txt
Explanation: A configuration change that updates the rpath value of `libFoundationMacros.so` to be correct
Scope: Only impacts the rpath value of `libFoundationMacros.so`
Original PR: https://github.com/apple/swift-foundation/pull/896
Risk: Low - scope is narrow, and fixes a regression that causes the macro to not be loadable so it can't really make anything worse :)
Testing: Testing done via local testing
Reviewer: @parkera
> [6.0.1] Set SWIFT_SYSTEM_NAME for macro project in CMake

- Sources/FoundationEssentials/CMakeLists.txt
When a project is used through a FetchContent/add_subdirectory, the `CMAKE_SOURCE_DIR` path points to the calling project. This is resulting in some of the CI jobs attempting to FetchContent the macros from `swift-corelibs-foundation/Sources/FoundationMacros`, rather than `swift-foundation/Sources/FoundationMacros`, ultimately failing the build.
The `project` call sets a `${CMAKE_PROJECT_NAME}_SOURCE_DIR` variable to the source directory of the project itself, making it more reliable. `CMAKE_CURRENT_SOURCE_DIR` would also work here too.
Noticed in: https://ci.swift.org/view/all/job/swift-build-static-sdk/46
> Fix macro source location

- Proposals/NNNN-calendar-recurrence-rule-end-count-and-date.md
This proposal concerns adding couple properties to `Caledar.RecurrenceRule.End`, first introduced in SF-0009.
> [Proposal] SF-NNNN Extending Calendar.RecurrenceRule.End

- Sources/FoundationEssentials/URL/URLParser.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Original 6.0 cherry-pick: #903 
Description from that cherry-pick:
**Explanation:** Percent-encode the host (instead of IDNA-encoding) for URLs with the `http+unix` or `https+unix` scheme, supporting the common representation of a "HTTP over Unix socket" URL. This fixes `http(s)+unix`-related regressions in clients such as Vapor and AsyncHTTPClient (see https://github.com/apple/swift-foundation/issues/863 and https://github.com/swift-server/async-http-client/issues/767)
**Scope:** Only impacts `http+unix` and `https+unix` URLs, adds them to the set of `schemesToPercentEncodeHost`
**Original PR:** https://github.com/apple/swift-foundation/pull/883
**Risk:** Low - narrow scope, added special casing of two schemes to a larger set that has been well tested
**Testing:** Local, swift-ci, stable …
> [6.0.0] URLComponents: support http(s)+unix schemes

- CMakeLists.txt
- Package.swift
- Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift
- Sources/FoundationEssentials/Calendar/RecurrenceRule.swift
`Calendar.RecurrenceRule.End` is de-facto an enum, but has been implemented as a struct so we can more easily extend it in the future without breaking ABI. Sadly the current API only provides a way to construct the struct, and does not let us introspect the associated values. This change adds a couple read-only properties to the struct to address this.
> Add `.count` and `.date` properties to `Calendar.RecurrenceRule.End`

- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
- Tests/FoundationEssentialsTests/DataTests.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
- Tests/FoundationEssentialsTests/ProcessInfoTests.swift
while disabling setting extended file attributes and a test creating a hard link, features not normally allowed on Android.
This got all the tests passing natively on Android 13 AArch64.
@hyp and @compnerd, try it out yourself and please review.
> [Android] Enable more code and tests

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Formatting/Date+ISO8601FormatStyle.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
We have applied multiple different strategies with regard to overflow during calendrical calculation, including capping input `Date` and clipping Julian day calculation with artificial bounds. Those are still insufficient as there are too many paths where numeric overflow may happen.
This patch patches those places by `throw`ing whenever applicable. Also adds fuzzing tests to cover many more Calendar API.
Resolves rdar://133558250
> Properly `throw` in case of numeric overflow in Calendar mathematics

- Benchmarks/Benchmarks/URL/BenchmarkURL.swift
- Benchmarks/Package.swift
Initial performance benchmarks for `URL` and `URLComponents`. Results look great, particularly between Swift 5.10 and 6.0 toolchains (old `swift-corelibs-foundation` vs new `swift-foundation` implementations). I tested on the latest Ubuntu 22.04 Swift 5.10 and nightly-6.0 images. (`swift-6.0-DEVELOPMENT-SNAPSHOT-2024-08-22-a`)
From 5.10 to 6.0, we see a **5-10x** speedup for almost all benchmarks, with even better outliers for `URL-ParseValidASCII` (**29x!**) and `URL-ParseInvalid` (**94x!**), as well as a whopping **254x** speedup for `URLComponents-GetComponentRanges` (which is probably due to an implementation difference since we now store the Swift `Range<String.Index>` directly). These results were consistent across many runs.
I think the 29x speedup of `URL(string:)` for valid URL …
> Benchmarks for URL and URLComponents

- Sources/FoundationEssentials/URL/URLParser.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Original 6.0 cherry-pick: #903 
Description from that cherry-pick:
**Explanation:** Percent-encode the host (instead of IDNA-encoding) for URLs with the `http+unix` or `https+unix` scheme, supporting the common representation of a "HTTP over Unix socket" URL. This fixes `http(s)+unix`-related regressions in clients such as Vapor and AsyncHTTPClient (see https://github.com/apple/swift-foundation/issues/863 and https://github.com/swift-server/async-http-client/issues/767)
**Scope:** Only impacts `http+unix` and `https+unix` URLs, adds them to the set of `schemesToPercentEncodeHost`
**Original PR:** https://github.com/apple/swift-foundation/pull/883
**Risk:** Low - narrow scope, added special casing of two schemes to a larger set that has been well tested
**Testing:** Local, swift-ci, stable …
> [6.0.1] URLComponents: support http(s)+unix schemes

- Sources/FoundationEssentials/URL/URLParser.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Similar to https://github.com/apple/swift-foundation/pull/883, the common way to represent a "WebSocket over Unix socket" URL is to use the scheme `ws+unix` and set the URL's host to the percent-encoded path of the socket.
This PR adds `ws+unix` and `wss+unix` to the set of schemes where we percent-encode the host instead of IDNA-encode.
> URLComponents: support ws(s)+unix schemes

- Sources/FoundationEssentials/PropertyList/PlistEncoder.swift
- Tests/FoundationEssentialsTests/PropertyListEncoderTests.swift
Use the `var` on `PropertyListEncoder` instead of the options struct directly, to support overrides in subclasses.
> PropertyListEncoder: Reference the property on the class itself instead of the options struct

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
- Tests/FoundationEssentialsTests/StringTests.swift
Improved some String+Path functions' performance with the following changes:
- Used `.utf8` where applicable (such as when searching for ascii `UInt8._slash`, which happens a lot)
- Refactored some path components functions, fixed an issue where `.deletingPathComponent` didn't skip over consecutive trailing slashes
- Refactored `.removingDotSegments` to directly modify the String buffer
- Replaced automount prefix matching with `UInt8` arrays
Non-implementation related:
- Replaced my previous ambiguous use of a `var input` with `utf8` to avoid confusion
- Used `UInt8._dot` and `._slash` instead of re-defining them in-function
- Made state enum names more specific to avoid potential naming conflicts
- Renamed helper functions for clarity
- Added unit tests
Results: We generally see …
> String+Path parsing performance improvements

- Sources/FoundationEssentials/Decimal/Decimal+Conformances.swift
- Tests/FoundationEssentialsTests/DecimalTests.swift
Add runtime check to revert back to old behavior for `Decimal(sign:exponent:significand:)` if the app was build on older OSs.
resolves: rdar://135822747
resolves: https://github.com/apple/swift-foundation/issues/833
> Add runtime check to Decimal(sign:exponent:significand:) for bin compat

- Sources/FoundationEssentials/String/String+IO.swift
- Tests/FoundationEssentialsTests/StringTests.swift
In Foundation.framework, initializing a `String` with `.nonLossyASCII` behaves the same way as `.ascii`, so this replicates the behavior for non-`FOUNDATION_FRAMEWORK` builds.
Resolves https://github.com/apple/swift-foundation/issues/929
> Support initializing string with nonLossyASCII encoding

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Original 6.0 cherry-pick: #902
Description from that cherry-pick:
**Explanation:** Fixes `URL.host` to match the behavior before the Swift URL implementation:
- If the host was percent-encoded, return the percent-decoded host
- If the host was IDNA-encoded (or not encoded at all), return that host string
**Scope:** Only impacts deprecated (but still used) `URL.host` for URLs with an encoded host, restoring previous behavior
**Original PR:** https://github.com/swiftlang/swift-foundation/pull/875
**Risk:** Low - minimal scope, one line change to restore behavior
**Testing:** Local, swift-ci, stable in main, release/6.0
**Reviewer:** @parkera @jmschonfeld
> [6.0.1] URL.host should not return percent-encoded host

- Benchmarks/Benchmarks/DataIO/BenchmarkDataIO.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Sources/FoundationEssentials/Error/CocoaError.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
I've determined a few bottlenecks in the data reading/writing path that this PR addresses:
1. When writing data, cleaning up the temporary file used FileManager.removeItem(atPath:) which was performing a dynamic cast to get the delegate
- I added more type information to the FileManager internal functions and removed the dynamic cast to avoid any casting machinery here
- I avoided an additional as? CocoaError dynamic cast when possible
- I added a quick-check call to rmdir before calling `FileManager.removeItem(atPath:)` since `rmdir` is noticeably faster than `removefile` for known empty directories (the Linux implementation of removeItem(atPath:) already does this, so we can consider that for a future FM improvement for Darwin)
2. When reading from a file that didn't exist, we spend a …
> Performance optimizations for data reading/writing

- Benchmarks/Package.swift
The Benchmarks package currently fails to resolve. It errors because it can't find `Benchmarks/Calendar`:
```
Showing All Issues
invalid custom path 'Benchmarks/Calendar' for target 'CalendarBenchmarks'
```
- Rename `Benchmarks/Calendar` to `Benchmarks/Internationalization`
- Rename target `CalendarBenchmarks` to `InternationalizationBenchmarks`
Benchmarks run again.
> Rename `CalendarBenchmarks` to `InternationalizationBenchmarks`

- Sources/FoundationEssentials/FileManager/FileOperations.swift
This is a follow-up fix for 6c0a3e8453cdde633e1c55f6112fd53a0d756979, which re-organized CocoaError helper functions, to repair the following build failure:
```
/home/build-user/swift-foundation/Sources/FoundationEssentials/FileManager/FileOperations.swift:926:36: error: 'fileOperationError' is inaccessible due to 'private' protection level
74 |     }
75 | #else
76 |     private static func fileOperationError(_ errNum: Int32, _ suspectedErroneousPath: String, sourcePath: String? = nil, destinationPath: String? = nil, variant: String? = nil) -> CocoaError {
|                         `- note: 'fileOperationError(_:_:sourcePath:destinationPath:variant:)' declared here
77 |         // Try to be a little bit more intelligent about which path should be reported in the error. In the case of …
```
> [wasm] Fix CocoaError construction for unsupported copy/link operations

- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Explanation: Fixes creation of relative symlinks to directories on Windows to resolve SwiftPM issues
Scope: Fixes a path calculation while creating symlinks to directories
Original PR: https://github.com/swiftlang/swift-foundation/pull/931
Risk: Low - only impacts Windows and the change is heavily tested via unit tests
Reviewer: @iCharlesHu @compnerd
> [6.0.2] Fix windows creation of relative symlinks to directories

- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Explanation: Fixes creation of relative symlinks to directories on Windows to resolve SwiftPM issues
Scope: Fixes a path calculation while creating symlinks to directories
Original PR: https://github.com/swiftlang/swift-foundation/pull/931
Risk: Low - only impacts Windows and the change is heavily tested via unit tests
Reviewer: @iCharlesHu @compnerd
> [6.0.x] Fix windows creation of relative symlinks to directories

- Sources/FoundationEssentials/AttributedString/Conversion.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
These SPI `AttributedString` initializers are unused and can be removed to reduce clutter
> Remove unused AttributedString initializers

- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationEssentials/URL/URLComponents.swift
- Sources/FoundationEssentials/URL/URLComponents_ObjC.swift
Removes old, unused Swift URL code so that only the new Swift implementation is left.
> Remove unused Swift URL code

- Benchmarks/Benchmarks/Base64/Base64.swift
- Benchmarks/Benchmarks/DataIO/BenchmarkDataIO.swift
- Benchmarks/Package.swift
We love benchmarks. In order to ensure that our base64 performance does not regress we should have a bunch of benchmarks that test different aspects. Since we will have a bunch of those in the future lets get them into a separate target.
- Create `Base64Benchmarks` target
- Add Base64 benchmarks
- Use scaling factor one if the example data is sufficiently large (1MB)
- Use scaling factor kilo if the example data is so small that measuring perfs overhead is to large (mostly in the jwt head examples)
We have baselines to test against.
> Create benchmarks for base64

- Sources/FoundationEssentials/URL/URL.swift
Fix two instances of visionOS deprecation messages mentioning the wrong replacement method.
> Fix minor copy-paste error in deprecation message

- Tests/FoundationInternationalizationTests/CalendarTests.swift
These tests are compatibility tests that are extensive and long running. Their goal is not to check each change but rather provide exhaustive compatibility validations and they're intended to be run at desk rather than routinely in CI. This disables the tests - they can be enabled locally to validate changes on-demand.
> Disable GregorianCalendarCompatibilityTests

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Paths beginning with `~` should not be treated as absolute for `URL(filePath:)`. This is because when constructing a `URLComponents` for a file path we consider absolute, we do:
```
components.file = "file"
components.host = ""
components.path = path
```
This would create the string like `file://~/`. However, `URLComponents` rejects this string because the `~` is ambiguous--it looks like a host. This can lead `components.url!` to crash when force-unwrapping.
This PR changes the `isAbsolute` check to only consider `/` paths absolute. If the path starts with `~`, we will try to expand the tilde, then ensure that the result is absolute.
> URL(filePath:) should not treat "~" as absolute

- Package.swift
- Sources/FoundationMacros/CMakeLists.txt
- Tests/FoundationMacrosTests/MacroTestUtilities.swift
Now that swift-syntax 600.0.0 is released we can update our manifests to point at this tag. Additionally, this change removes a deprecation warning that was introduced with 600.0.0 and removes an availability check that is no longer needed.
> Update to swift-syntax 600.0.0

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/StringTests.swift
- Tests/FoundationEssentialsTests/URLTests.swift
When supplying a directory to `URL` like `URL(filePath: "/my/directory", directoryHint: .checkFileSystem)`, the initializer will automatically append a trailing slash, so the `.path()` is `/my/directory/`.
The current logic for `.appendingPathExtension("zip")` then directly appends the path extension, creating the unexpected path: `/my/directory/.zip`. A similar issue occurs where `.deletingPathExtension()` does not search before the trailing slash.
This PR restores the behavior from before the Swift `URL` implementation, which strips the trailing slash before appending or deleting the path extension, then appends a slash if the path was a directory. E.g. after appending the path extension, the resulting `.path()` is now `/my/directory.zip/` as expected.
> URL path extension APIs should strip trailing slashes

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
On Windows, `URL.fileSystemPath` should ideally provide the path exactly how you would make filesystem calls with it, e.g. by stripping the leading slash from an RFC drive path like `/C:/path` and by converting the slashes to backlashes.
But given that `URL.fileSystemPath` is vended directly to (and synonymous with) the widely-used `URL.path`, we should start by just stripping the leading slash from drive letters for compatibility. This returns `URL.path` to its previous behavior on Windows.
Resolves #857
> `URL.fileSystemPath` should strip leading slash for Windows drive letters

- Tests/FoundationEssentialsTests/URLTests.swift
Add guards to make these tests compatible with both the old and new `URL` implementation.
> Guard old behavior in URL tests

- Sources/FoundationEssentials/TimeZone/TimeZone.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_ICU.swift
- Sources/_FoundationCShims/include/_CStdlib.h
The current implementation of `TimeZone.current` attempts to read from `/etc/localtime` which is not a path that exists on Windows. This leads to `TimeZone.current` always being GMT on Windows. Instead, this updates the implementation to call `GetTimeZoneInformation`, convert the Windows name to an ICU system timezone name, and initialize a timezone with that name (this matches the behavior of `TimeZone` on Swift 5.10 when it was based on `CFTimeZone`). This also restricts the default values for `TZDEFAULT`/`TZDIR` to Darwin + Linux where the paths are reasonable unlike Windows where we know these constants should never exist to avoid accidental usage in the future.
There's likely more work to be done here for Windows for a full solution (to allow in some way for developers to interface …
> [Windows] Fix incorrect `TimeZone.current` lookup logic

- Sources/FoundationEssentials/TimeZone/TimeZone.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_ICU.swift
- Sources/_FoundationCShims/include/_CStdlib.h
Explanation: Fixes lookup of the current timezone on Windows
Scope: Only impacts `TimeZone.current` on Windows
Original PR: https://github.com/swiftlang/swift-foundation/pull/975
Risk: Low - restores Swift 5.10 behavior and scope is minimal
Reviewer: @parkera @compnerd
> [6.0.x] [Windows] Fix incorrect TimeZone.current lookup logic

- Sources/FoundationEssentials/String/String+Path.swift
As far as I know `\\?\` is always returned by `GetFinalPathNameByHandleW` but it’s better to be safe and actually check instead of unconditionally trimming the first 4 characters from the returned path.
See https://github.com/swiftlang/swift-tools-support-core/pull/485#discussion_r1795781075
> Conditionalize stripping of `\\?\` on it actually being present

- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/StringTests.swift
- Tests/FoundationEssentialsTests/URLTests.swift
**Explanation:** Fixes various `URL` path API behaviors to match the expected behavior from before the Swift URL implementation:
- Drops trailing slashes from `URL.fileSystemPath` and `URL.path`
- Strips trailing slashes in `URL(filePath:)` if a user supplies `.notDirectory`
- Does not treat `~` paths as absolute in `URL(filePath:)`, resolves the tilde and prevents a crash during initialization
- Strips the leading slash of Windows drive letter paths on Windows
- Prevents unexpected path extension API behavior when the path is a directory
**Scope:** Targeted changes to `URL` path APIs to maintain compatibility
**Original PRs:** #852, #867, #961, #964, #965
**Risk:** Low - Targeted scope, restores expected behavior
**Testing:** Local, swift-ci from `swift`, `swift-foundation`, and …
> [6.0.x] `URL` path bug fixes

- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/StringTests.swift
- Tests/FoundationEssentialsTests/URLTests.swift
**Explanation:** Fixes various `URL` path API behaviors to match the expected behavior from before the Swift URL implementation:
- Drops trailing slashes from `URL.fileSystemPath` and `URL.path`
- Strips trailing slashes in `URL(filePath:)` if a user supplies `.notDirectory`
- Does not treat `~` paths as absolute in `URL(filePath:)`, resolves the tilde and prevents a crash during initialization
- Strips the leading slash of Windows drive letter paths on Windows
- Prevents unexpected path extension API behavior when the path is a directory
**Scope:** Targeted changes to `URL` path APIs to maintain compatibility
**Original PRs:** #852, #867, #961, #964, #965
**Risk:** Low - Targeted scope, restores expected behavior
**Testing:** Local, swift-ci from `swift`, `swift-foundation`, and …
> [6.0.2] `URL` path bug fixes

- Sources/FoundationEssentials/TimeZone/TimeZone.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
https://github.com/swiftlang/swift-foundation/pull/975 started to restrict the fallback value for `TZDIR` and it revealed that WASI platform implicitly depends on TZDIR even though it won't have such directory. This patch explicitly handles the case for WASI platform for timezone operations.
> [wasm] Fix WASI build around TimeZone

- Sources/FoundationEssentials/URL/URL.swift
Bridging an invalid `CFURL` like `https://2001:db8::1:433` to `URL` in Swift causes a crash since the Swift parser returns `nil`. For compatibility, we can allow bridging to proceed by storing the string in a `URLParseInfo` with all `nil` ranges. This prevents the crash and allows `URL` to be a dummy container for the string, but otherwise will not return info that may be ambiguous.
> Prevent crash when bridging an invalid CFURL to Swift URL

- Benchmarks/Benchmarks/Internationalization/BenchmarkCalendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Enumerate.swift
- Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
The original implementation of `Calendar.RecurrenceRule` expanded recurrences of
dates using the Calendar APIs for matching date components. This would result in
multiple sequences for matching date components even when just a single sequence
would have sufficed, thus requiring more time and memory to complete enumeration
E.g: finding the dates for Thanksgivings (fourth Thursday of each November) took
~4 times as much time using RecurrenceRule when compared to simply matching date
components.
This commit optimizes how we expand dates for recurrences. Instead of creating a
sequence for each value of each component in the recurrence rule, we introduce a
new type of sequence closely resembling Calendar.DatesByMatching, but which also
allows multiple values per date component.
Addresses #555 …
> Performance improvements for `Calendar.RecurrenceRule`

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/SearchPaths/FileManager+DarwinSearchPaths.swift
- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/StringTests.swift
Explanation: Replaces uses of thread-unsafe user/group lookup functions with thread-safe versions
Scope: Impacts APIs that lookup user/group info (`FileManager`/`ProcessInfo`)
Original PR: https://github.com/swiftlang/swift-foundation/pull/994
Risk: Low - behavior is well tested by unit tests
Reviewer: @parkera
> [6.0.x] Fetching user/group info causes race conditions (#994)

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
When appending `path` to a URL with an empty relative path, the current code does: `"" + "/" + path`. This is problematic because it makes the relative path absolute, so it no longer resolves against the base URL.
E.g. for the following code,
```
let currentDir = URL(filePath: "")
print(currentDir.path) // "/my/cwd"
let file = currentDir.appending(path: "main.swift")
print(file.path) // "/main.swift"
```
we should get an output of `"/my/cwd/main.swift"`, not `"/main.swift"`.
This PR updates `URL.appending(path:)` so if the current path is empty (and thus relative), we don't append a slash which would make the path absolute. That is unless we have an authority. If we have an authority, we must add a slash to separate the path from the authority, e.g. …
> URL: Appending to an empty file path results in an absolute path

- Proposals/0010-calendar-recurrence-rule-end-count-and-date.md
Update the proposal to also make some of the recently introduced types Hashable.
> [Proposal] SF-0010 Amend proposal to make types Hashable

- Evolution.md
Add a section for proposing minor API changes
> Update contribution guideline for minor API proposals 

- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Sources/FoundationEssentials/JSON/JSONWriter.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Major refactoring of Darwin Foundation's (and hence swift-foundation's) `JSONEncoder` took place a couple of years ago, with the rewrite being entirely in Swift, no longer relying on `NSJSONSerialization`. This effort resulted in a significant performance boost on Darwin. However, when swift-corelibs-foundation was re-cored on top of swift-foundation in 6.0, a performance regression was discovered there compared to the 5.10 toolchain.
After examining the code from the 5.10 toolchain's `JSONEncoder`, I've adapted the swift-foundation implementation to use its general architecture, with some additional important correctness fixes and other adjustments. I also included some other optimizations on top of it. All of this resulted in slightly *improved* performance in usage within the toolchain …
> Fix JSONEncoder performance regression in 6.0 toolchain

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
As part of the new Swift `URL` implementation, we unified `URL.host` to behave like `URLComponents.host`, which will return an IP literal with the square brackets included. While RFC 3986 does say that `host` includes these square brackets, this change caused bincompat issues for clients who take IPv6 addresses from `URL.host` and pass them directly to APIs like `inet_pton(3)`.
Because `URL.host` has long behaved by stripping the brackets, and no longer stripping them can cause immediate client breakage that requires workaround, this PR restores the previous behavior. Thank you to all who worked around it for the time being.
Resolves https://github.com/swiftlang/swift-foundation/issues/957
> Restore `URL.host` bracket stripping for compatibility

- Sources/FoundationEssentials/FileManager/SearchPaths/FileManager+DarwinSearchPaths.swift
Fixes a typo where we created a path with just the user's name rather than the user's home directory due to a recent change in this function.
> Fix typo in String.replacingTildeWithRealHomeDirectory

- Sources/FoundationEssentials/URL/URL.swift
`CFURL` considers a URL decomposable if it can be decomposed into its component parts according to RFC 1808. This varies slightly from an analogous definition of decomposable for RFC 3986, specifically when it comes to relative paths as found in `data:` URLs.
This PR adjusts Swift URL's `CFURL` creation logic to add the `IS_DECOMPOSABLE` flag only if it does not have a scheme or if there is a slash directly following the scheme.
> Fix `IS_DECOMPOSABLE` flag when bridging to `CFURL`

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
**Explanation:** Corrects `URL.appending(path:)` behavior to prevent an empty relative path from becoming absolute, which would no longer resolve against the base URL.
**Scope:** Only impacts `URL.appending(...)` APIs when the relative path is empty.
**Original PR:** #988 
**Risk:** Low - Small change to fix breaking behavior in this edge case.
**Testing:** Added unit tests, swift-ci, stable in `main`
**Reviewer:** @jmschonfeld 
Resolves https://github.com/swiftlang/swift-foundation/issues/921 for `release/6.0`
> [6.0.x] URL: Appending to an empty file path results in an absolute path (#988)

- Sources/FoundationEssentials/Platform.swift
Platform.swift regressed after 71eefee7fca08ecbeacc89098b74ab80319baa6b
> [android] fix the android build

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
- Tests/FoundationEssentialsTests/StringTests.swift
**Explanation:** Rewrote String+Path functions for performance and functionality. ~2-6x speedup. Fixed bugs where `.deletingLastPathComponent()` didn't skip over trailing slashes, and where `"/path/".deletingLastPathComponent()` would delete the entire string instead of leaving the leading `"/"` (https://github.com/swiftlang/swift-foundation/issues/980).
**Scope:** Impacts various Foundation types like `URL` that use these `String` extensions on file paths.
**Original PR:** #927 
**Risk:** Low/Med - Well-tested to ensure correct behavior, but does touch several commonly used `String` extensions.
**Testing:** Added unit tests, local, swift-ci, stable in `main` for over a month
**Reviewer:** @jmschonfeld 
Resolves https://github.com/swiftlang/swift-foundation/issues/980 for `release/6.0`
> [6.0.x] String+Path performance improvements and bug fixes

- Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift
- Tests/FoundationInternationalizationTests/CalendarRecurrenceRuleTests.swift
This change makes a fix to `Calendar.RecurrenceRule` with regards to leap months and adds a few tests to verify correctness. When constructing the base sequence, we include `isLeapMonth` of the start date in the date components. Before, start dates falling on a leap month would have been treated the same as dates which do fall on the non-leap month before.
> RecurrenceRule: Respect leap months

- Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
In recurrence rules that expand days or weekdays in a month, we first use a base recurrence to calculate "anchors" in the month, and then change the day of month or weekday to find results. Because the base recurrence used to match the day of month of the start date, we could miss anchors if matching was set to `.strict`. This change makes sure that if we know that the day of month is known to change, we reset it to 1 in the base recurrence.
> Don't skip anchors with strict matching in Calendar.RecurrenceRule. Resolve #881

- Sources/FoundationEssentials/AttributedString/AttributedString+Runs.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
Empty `AttributedSubstring`s should contain no runs, however there was a small index calculation bug in which empty substrings in the middle of the string (neither at the start or end indices) would incorrectly expand their ranges to the next run. This resolves the bug by ensuring that the `Runs.startIndex == Runs.endIndex` for all empty substrings regardless of their location in the string.
Resolves rdar://138432081
> Ensure empty AttributedSubstrings produce no runs

- Sources/FoundationEssentials/Error/CocoaError.swift
Optimized `CustomNSError.errorDomain` calculation.
`String(reflecting:)` for `Any.Type` objects eventually calls `_type(:qualified:)`. But `String(reflecting:)` call has overhead because of `as?` checks. 
All details are listed in [issue](https://github.com/swiftlang/swift-foundation/issues/1031).
Also I've opened same MR for non-Darwin platforms: https://github.com/swiftlang/swift-corelibs-foundation/pull/5132
> improve CustomNSError.errorDomain calculation

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
**Explanation:** Corrects `URL.deletingLastPathComponent()` behavior to append `..` in special cases, such as when the relative path is empty or ends in a `..` segment. This makes `.deletingLastPathComponent()` semantically accurate when resolving against a base URL.
**Scope:** Only impacts `URL.deletingLastPathComponent()` in special cases of relative paths.
**Original PR:** #989  
**Risk:** Low - Small change to fix behavior for these edge cases.
**Testing:** Added comprehensive unit test, swift-ci, stable in `main`
**Reviewer:** @itingliu 
Resolves https://github.com/swiftlang/swift-foundation/issues/922 for `release/6.0`
> [6.0.x] URL.deletingLastPathComponent() should append .. in special cases

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
**Explanation:** Strips the square brackets from IP literal hosts when calling `URL.host`. This restores previous behavior and prevents bincompat issues for clients who take IPv6 addresses from `URL.host` and pass them directly to APIs like `inet_pton(3)`.
**Scope:** Only impacts `URL.host` and `URL.host()` when the host is an IP literal.
**Original PR:** #1008   
**Risk:** Low - Small change to restore previous behavior.
**Testing:** Added unit test, swift-ci, stable in `main`
**Reviewer:** @parkera  
Resolves https://github.com/swiftlang/swift-foundation/issues/957 for `release/6.0`
> [6.0.x] Restore URL.host bracket stripping for compatibility

- Package.swift
- Sources/FoundationMacros/PredicateMacro.swift
- Tests/FoundationMacrosTests/MacroTestUtilities.swift
`#Predicate` currently performs its transformation in two passes over the AST:
1. Rewrite all optional chaining as explicit calls to `flatMap` (ex. `foo?.bar` --> `foo.flatMap { $0.bar }`)
2. Perform transformation to `PredicateExpression` builder calls (ex. `foo.bar()` --> `PredicateExpressions.build_bar(PredicateExpressions.build_Arg(foo))`)
Unfortunately, performing the rewrite in Step 1 creates a new AST that lacks all source information from the original code in the source file. This means that when diagnostics are emitted during pass 2, the diagnostics are detached from any source locations and only appear as standalone messages in the build log which makes for a challenging debugging experience.
After talking with the swift-syntax folks, in the fullness of time we will need to …
> Ensure predicate diagnostics contain source information when possible

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
Instead of recursively creating all the parent directories, which is racy if the directory is created between the check if the parent directory exists and the actual directory creation, use `SHCreateDirectoryExW`, which also creates intermediate directories.
Alternative to https://github.com/swiftlang/swift-foundation/pull/1021
> Use `SHCreateDirectoryExW` to create a directory with intermediate directories on Windows

- Sources/FoundationEssentials/JSON/JSONWriter.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
We had a testing gap in the encoding of strings containing low unicode escape sequences. The recent JSONWriter re-write broke these, and the missing test means we didn't catch it.
Single digit hex values were getting / 16 when % 16 was more correct (though actually unnecessary).
Double digit hex values were in reverse order.
> Fix incorrect unicode escape sequence encodings

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
On Windows, we could potentially return a `nil` for the current working directory in the rare case that the current working directory was changed during the computation:
```swift
let dwLength: DWORD = GetCurrentDirectoryW(0, nil)                                // 1
return withUnsafeTemporaryAllocation(of: WCHAR.self, capacity: Int(dwLength)) {
if GetCurrentDirectoryW(dwLength, $0.baseAddress) == dwLength - 1 {           // 2
return String(decodingCString: $0.baseAddress!, as: UTF16.self)
}
return nil                                                                    // 3
}
```
Consider the case where at step 1, we receive $n$. We then are interrupted, the CWD changed. We then perform step 2, where we receive $m$ (st $m != n$). We would then proceed to point 3, where we return `nil`. Avoid …
> FileManager: avoid a TOCTOU issue in computing CWD

- Sources/FoundationEssentials/JSON/JSONEncoder.swift
Pulling in a change from previous swift-corelibs-foundation code in an attempt to reduce memory consumption without making a large sacrifice on CPU
> JSONEncoder using large amount of memory when encoding array of structs

- Sources/FoundationEssentials/URL/URL.swift
This PR adds a linked-on-or-after check for apps which pass an empty string to `URL(string:)`, which previously returned `nil`. The new `URL(string:)` implementations allow the empty string as input since an empty path is valid and can be resolved against a base URL. This is shown in the RFC 3986 examples: https://datatracker.ietf.org/doc/html/rfc3986#section-5.4.1
> Add linked-on-or-after check for apps that pass an empty URL string

- Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
When filtering by weekdays, we match the dates against a set of date components. These components happened to contain the hour, minute and second components from the anchor date, so filtering would undo previous expansions by hour, minute and second.
> Calendar.RecurrenceRule: Only match weekday components when filtering by weekday

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
We should not strip the trailing slash when getting the `fileSystemPath` for `C:\` on Windows, since `C:\` represents the root while `C:` does not. Similarly, we should not strip the trailing slash for any UNC path, since the trailing slash might be root.
Resolves https://github.com/swiftlang/swift-foundation/issues/976 and https://github.com/swiftlang/swift-foundation/issues/977
> `URL.path` should not strip trailing slash for root paths on Windows

- Proposals/0010-concurrency-safe-notifications.md
- Proposals/NNNN-concurrency-safe-notifications.md
This PR introduces a proposal for adopting Swift Concurrency in `NotificationCenter`.
> Concurrency-Safe Notifications

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
These `try!` assertions were incorrect. They were focused on the fact that the type of the value in the input JSON was guaranteed to be a string, but with the on-demand parsing behavior, there is no longer any initial UTF-8 validation step, which means decoding the keys into String values could fail. This needs to actually throw an error instead of trapping. Fortunately, this is an (embarrassingly) easy change to make.
> rdar://133742708 (JSONDecoder crashes whole app on invalid input instead of throwing Error)

- Sources/FoundationEssentials/FileManager/SearchPaths/FileManager+DarwinSearchPaths.swift
- Sources/FoundationEssentials/FileManager/SearchPaths/FileManager+SearchPaths.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
This adds ObjC-visible entry points to our Swift FileManager code to allow some of the ObjC directory enumeration functions to use the new Swift implementation instead of the old ObjC implementation. This also fixes a bug with enumeration of special directories on macOS that this new coverage discovered.
> FileManager Entry Points for ObjC Directory Enumeration

- Sources/FoundationEssentials/AttributedString/Conversion.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
When converting an `NSRange` to a `Range<AttributedString.Index>` via our API, the conversion currently does not take the provided `AttributedStringProtocol`'s `startIndex`/`endIndex` into account. This means that the `NSRange`'s location is considered relative to the base's start for an `AttributedSubstring` rather than the substring's start, leading to conversion failing because the `NSRange` is often considered beyond the bounds of the slice.
This updates the conversion to operate on a slice of the underlying `BigString` so that the range calculation is performed from the slice's `startIndex` rather than the base's `startIndex`.
> NSRange to Range<AttributedString.Index> conversion should be relative to sliced boundaries

- Sources/FoundationEssentials/Locale/Locale.swift
- Sources/FoundationEssentials/Locale/Locale_Unlocalized.swift
- Sources/FoundationInternationalization/Locale/Locale_ObjC.swift
- use @_effects(releasenone) to solemnly swear to the compiler that we won't release anything inside these getters, eliminating refcounting to call them
- micro-optimize identifierDoesNotRequireSpecialCaseHandling, allowing us to delete the cache of it without regressing perf
On the test app this goes from "so slow I didn't bother to see how long it takes to finish" to "finishes in around 1 second"
Resolves 137885111
Co-authored-by: @Catfish-Man
> Improve performance for calling `Locale.identifier` from `NS/CFLocale`

- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
The logic for fallback timezone detection on Android should be the same as Linux.
> Detect current timezone on Android the same as Linux

- Sources/FoundationEssentials/FileManager/SwiftFileManager.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Forced unpacking caused a crash.
```
let dest = "/tmp/a/b/c"
let fm = FileManager.default
try fm.createDirectory(atPath: dest, withIntermediateDirectories: true, attributes: nil)
let _ = fm.changeCurrentDirectoryPath(dest)
let _ = fm.currentDirectoryPath // it's ok
try fm.removeItem(atPath: dest)
let _ = fm.currentDirectoryPath // will crash
```
The same code in the old version(<5.10) of swift will be empty string.
> Fix 'var currentDirectoryPath: String' crash when the directory is removed

- Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
This commit fixes the use of the `in:` bound in
Calendar.RecurrenceRule.recurrences(of:in:) to properly exclude the upper bound as revealed by #1040.
> Fix upper bound in Calendar.RecurrenceRule.recurrences(of:in:)

- Sources/FoundationInternationalization/Locale/Locale_ObjC.swift
`NSLocale` wants to use `Locale._identifierCapturingPreferences` when calling into ICU.
For 55573864
> Expose `_identifierCapturingPreferences` for `NSLocale`

- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
Regression after https://github.com/swiftlang/swift-foundation/pull/1053
> [android] fix the tm_zone access, which is nullable on Android

- CMakeLists.txt
- Package.swift
Now that we've branched for `release/6.1`, changes targeting main will need to be annotated via a new 6.2-aligned availability. This PR adds `FoundationPreview 6.2` as an allowed availability annotation so that future API work can use this to properly mark availability on platforms where Foundation ships as part of an SDK.
> Add FoundationPreview 6.2 as an allowed availability annotation

- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Cleans up many uses of `#if FOUNDATION_FRAMEWORK` and `FOUNDATION_FRAMEWORK_NSURL`.
> Clean up Swift URL build flags

- Sources/FoundationEssentials/String/String+Path.swift
Temporary directory lookup has faulty logic on Darwin:
```swift
if length > 0 && length < buffer.count {
return String(decoding: buffer, as: UTF8.self)
}
```
1. We already checked 1length > 0` above, so we can eliminate that check
2. `length < buffer.count` will never be true, since we pass `capacity: length` to the `withUnsafeTemporaryAllocation` call which means that `buffer.count` will always be `length`
3. Since `buffer.count == length == finalLength`, `buffer.count` includes the null terminator but `String(decoding:)` does not stop at null terminators (in other words, the resulting string would contain a null byte at the end
This means we never actually read the value from `confstr` and always fell back to `TMPDIR`. To fix it, we just remove the unnecessary checks and switch to …
> Correct buffer size logic when calling `confstr`

- Sources/FoundationEssentials/Data/Data+Writing.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Previously, using `Data.write(to:)` (or `FileManager.createFile(atPath:)` which calls to that function) with a path that contained non-ASCII characters would crash. This crash was caused by an incorrect buffer length calculation that used `String.count` instead of the actual length of the buffer (which will differ for non-ASCII paths). Fixing the crash however revealed incorrect behavior where file creation would fail due to providing a UTF-8 file name to `_sopen_s`. Instead, we need to transcode the file name to UTF-16 and open the file with `_wsopen_s` to ensure that non-ASCII file names can be opened. The added unit test previously crashed (and then failed when the crash was resolved) but now successfully creates the file.
Resolves …
> Properly write non-ASCII file names on Windows for file creation

- Sources/FoundationEssentials/Data/Data+Writing.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
- **Explanation**: Fixes creation of files on Windows when the file's path contains non-ASCII characters
- **Scope**: Impacts file creation on Windows via `Data` and `FileManager`
- **Issues**: https://github.com/swiftlang/swift-foundation/issues/1058
- **Original PRs**: https://github.com/swiftlang/swift-foundation/pull/1059
- **Risk**: Low, scope is narrow and change is well tested
- **Testing**: local testing and testing in CI
- **Reviewers**: @compnerd
> [6.1] Properly write non-ASCII file names on Windows for file creation

- Sources/FoundationEssentials/FileManager/SearchPaths/FileManager+SearchPaths.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
The `String`, ObjC-based search path enumeration calls the Swift implementation which produces a `URL` and then converts each URL back to a `String` path. This process is actually making paths absolute which is fine for Swift use cases, but the ObjC API has an option to prevent expansion of the tilde directory. By passing those unexpanded paths through `URL`, we end up with paths like `/Users/USER/Library` which are incorrect because the tilde is expanded.
To avoid these behaviors and maintain support for the "legacy" ObjC behavior for string paths, I shuffled the functions around just a bit so that the implementation creates `String`s instead of `URL`s and only converts to `URL` for the Swift API. This also allows us to test the `String` results directly in our unit tests to add a test …
> Darwin SearchPaths without expanding tilde produce non-tilde-based paths

- Sources/FoundationEssentials/FileManager/FileOperations.swift
The previous ObjC implementation of `-[NSFileManager removeItemAtPath:]` only attached callbacks to the `removefile_state_t` when the delegate was present and it implemented the equivalent functions. However, the new Swift implementation unconditionally attaches callbacks that simply return "default" values when no delegate responds. This causes a behavioral difference in `removefile` when removing items that are not materialized (ex. remote iCloud documents that do not currently exist on disk). Calling the confirm callback requires iterating the children of the removed directory and performing this iteration causes `removefile` to materialize the file on-disk. We should avoid this materialization when no callback exists - this change does this by only attaching callbacks to the …
> Avoid attaching removefile callbacks when delegate does not implement functions

- Sources/FoundationEssentials/Predicate/Expression.swift
- Sources/FoundationEssentials/Predicate/Predicate.swift
To enable building this package with a "minimal" Swift toolchain whose compiler does not have support for macros, guard the macro declarations behind `#if hasFeature(Macros)`. This has no effect on anything but the toolchain bootstrap process.
> Guard macro declarations behind `hasFeature(Macros)`

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
When porting `FileManager` to swift-foundation, I made the mistake of changing the underlying home directory lookup behavior for non-existent users to fallback to `/var/empty`. I also synced this behavior to Windows where it now falls back to `%ALLUSERSPROFILE%` and updated unit tests to match this behavior. However, this behavior is incorrect. Falling back to `/var/empty` or `%ALLUSERSPROFILE%` is an alright choice for the current user, but for an arbitrary other user, we should instead return `nil` as these APIs return optional values. This PR splits the user home directory implementation into two: one for the current user that falls back to `/var/empty`/`%ALLUSERSPROFILE%` and one for a specific user that returns `nil` on failure.
> Home directory for non-existent user should not fall back to /var/empty or %ALLUSERSPROFILE%

- Proposals/0007-swift-subprocess.md
This PR updates the proposal for `SF-0007 Swift Subprocess` to version 5 and added header docs. Here are the changes since version 3:
- **v4**: Minor updates (primarily name changes):
- Dropped the `executing` label from `.run()`.
- Removed references to `Subprocess.AsyncBytes`:
- Instead, we use an opaque type: `some AsyncSequence<UInt8, Error>`.
- When `typed throws` is ready, we can then update to the actual error type.
- Updated `.standardOutput` and `.standardError` properties on `Subprocess` and `CollectedResult` to be non-optional (now they use `fatalError` instead).
- Rationale: These properties can only be `nil` in two cases:
1. The corresponding `.output`/`.error` was not set to `.redirectToSequence` when `run()` was called.
2. These properties are accessed multiple times. This …
> Updated SF-0007 to version 5

- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
`URL.appendingPathExtension("")` should return the URL unchanged instead of appending a trailing dot.
Resolves https://github.com/swiftlang/swift-foundation/issues/1080
> URL.appendingPathExtension("") should not append a trailing dot

- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
`FileManager.copyItem(atPath:toPath:)` has a TOCTOU bug due to how it recursively copies directories. As we recursively copy directories, we copy the directory itself with default metadata/permissions, copy the contents of the directory, then copy the metadata over (which may change permissions on the directory, including potentially making it read-only). This TOCTOU bug allows another process with write access to the source directory to (with the right timing) cause a process that uses `FileManager.copyItem` to copy and apply metadata to a file rather than a directory.
To fix the TOCTOU issue, the post-order traversal which copies the metadata now:
- Opens a file descriptor to both the source and destination directories
- `fstats` the source and destination directories to validate that …
> Ensure that FileManager.copyItem cannot copy directory metadata to files

- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
- **Explanation**: Eliminates a TOCTOU issue that allowed FileManager to copy metadata from files believing they were directories
- **Scope**: Impacts FileManager.copyItem(atPath:toPath:) on non-Windows platforms
- **Original PRs**: https://github.com/swiftlang/swift-foundation/pull/1081
- **Risk**: Medium - large amount of new code but it has a decent amount of testing and the reward of fixing the TOCTOU issue is high
- **Testing**: local testing, swift-ci testing
- **Reviewers**: @parkera
> [6.1] Ensure that FileManager.copyItem cannot copy directory metadata to files

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
- **Explanation**: Requesting the home directory for a non-existent user now returns `nil` as it used to instead of `/var/empty` or `%ALLUSERSPROFILE%`. The current user's home directory still falls back to `/var/empty`/`%ALLUSERSPROFILE%` as it has previously.
- **Scope**: Impacts requesting the home directory for a username that does not exist across all platforms
- **Original PRs**: https://github.com/swiftlang/swift-foundation/pull/1072
- **Risk**: Low-Medium - this does change behavior, however it restores swift 5.10 behavior, this is heavily tested by unit tests, and I don't expect this behavior to be fairly load bearing
- **Testing**: local testing, swift-ci testing
- **Reviewers**: @jrflat @kperryua
> [6.1] Home directory for non-existent user should not fall back to /var/empty or %ALLUSERSPROFILE%

- Proposals/0001-calendar-improvements.md
Fix typo for some words at 0001-calendar-improvements.md
+ manully => manually
+ discrepency => discrepancy
+ diffcult  => difficult
> [docs] Fix typo for some words at 0001-calendar-improvements.md

- Sources/FoundationEssentials/URL/URL.swift
This PR adds a linked-on-or-after check for apps which expect `URL.host()` to return `nil` for URLs like `https:///`. The new `.host()` implementation returns an empty string because according to RFC 3986, a host always exists if there is an authority component, it just might be empty.
> Add linked-on-or-after check for empty URL.host()

- Sources/FoundationEssentials/FileManager/FileOperations.swift
Extended attributes don't exist in WASI, so we need to exclude the use of xattr-related APIs including `flistxattr`.
> Fix WASI build of `_copyDirectoryMetadata`

- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/WASILibc+Extensions.swift
- Sources/_FoundationCShims/include/platform_shims.h
Fix remaining build issues with wasi-libc for missing functions, some constant shims, and replace a legacy libc function use (`futimes`) with `futimens`
> Follow-up fixes to make it work with wasi-libc

- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
A small typo causes file path errors on Windows to not include the variant of the API that produced the error. This patch ensures we pass the variant down to the error constructor
Resolves https://github.com/swiftlang/swift-foundation/issues/1084
> [Windows] Include variant in file path errors

- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
**Explanation:** Prevents a trailing dot from being appended for an empty path extension.
**Scope:** Only impacts `URL.appendingPathExtension(_:)` when the input is an empty string.
**Original PR:** #1082 
**Risk:** Low - empty string check, restores previous behavior
**Testing:** Added unit test, swift-ci
**Reviewer:** @jmschonfeld   
Resolves https://github.com/swiftlang/swift-foundation/issues/1080 for `release/6.1`
> [6.1] URL.appendingPathExtension("") appends a trailing dot

- Sources/FoundationEssentials/AttributedString/AttributedString+UTF16View.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+UTF8View.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringProtocol.swift
- Sources/FoundationEssentials/AttributedString/CMakeLists.txt
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
This adds a new UTF-8 and UTF-16 view to `AttributedString`, vending APIs similar to the underlying `BigString`'s UTF-8 and UTF-16 view
> Implement AttributedString UTF8 and UTF16 views

- Sources/FoundationEssentials/URL/URL.swift
After receiving more reports of bincompat issues, we're restoring the previous behavior of `URL(string: "")` returning `nil`. `URL(string: "", relativeTo: baseURL)` will still be valid input, allowing us to pass all the RFC 3986 examples.
Resolves #962
> Restore behavior of URL(string: "") returning nil

- Sources/FoundationEssentials/LockedState.swift
Unfortunately, we're missing a few conditionals in the `LockedState` implementation that left `LockedState` acting as a no-op for the static linux SDK. This results in the lack of synchronization of caches in swift-foundation for that platform. I went ahead and added the right conditionals for Musl (same as Glibc) and also added an explicit `#else` case with a `#error` so that we can more quickly and easily detect platforms for which we have not implemented synchronization primitives here.
I've confirmed that running the sample program in the linked issue produces the segmentation fault but with this change the fault no longer occurs.
Resolves https://github.com/swiftlang/swift-foundation/issues/1100
> Implement LockedState for Musl

- Sources/FoundationEssentials/FileManager/FileOperations.swift
Normal users don't have permission to change these, even for their own files.
@jmschonfeld, as [done previously for Android](https://github.com/swiftlang/swift-foundation/pull/871#discussion_r1722073325).
> Don't try to set extended attributes on Android

- Sources/FoundationEssentials/LockedState.swift
- **Explanation**: Implements locking behavior for the internal `LockedState` type for the static linux SDK build
- **Scope**: Impacts synchronization primitives in FoundationEssentials/FoundationInternationalization in the static linux SDK
- **Issues**: https://github.com/swiftlang/swift-foundation/issues/1100
- **Original PRs**: https://github.com/swiftlang/swift-foundation/pull/1101
- **Risk**: Low - changed code is minimal and makes `Musl` perform the equivalent to `Glibc`
- **Testing**: local testing with sample code
- **Reviewers**: @itingliu @parkera @iCharlesHu
> [6.1] Implement LockedState for Musl

- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationEssentials/URL/URLComponents.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Calling `URL.standardized` on a URL like `../../../../` removes the dot segments and produces an empty string. `NSURL` allows the empty string, and in the old implementation, this would return a `URL` that wraps an empty string `NSURL`.
In the new implementation, we ultimately call `URL(string: "")` when initializing this standardized URL, which returns `nil` again after #1103. Since `URL.standardized` returns a non-nil `URL`, this would crash when unwrapped.
We can allow `URL.standardized` (and other methods that call `URLComponents.url`) to return an empty string `URL` as they did previously by using `URL(string:relativeTo:)` instead.
> (142076445) Allow URL.standardized to return an empty string URL

- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/WASILibc+Extensions.swift
- Sources/_FoundationCShims/include/platform_shims.h
**Explanation:** Fix build issues in WASI platform, which are introduced in https://github.com/swiftlang/swift-foundation/pull/1083
**Scope:** Impacts FileManager.copyItem(atPath:toPath:) on non-Windows platforms
**Original PR:** https://github.com/swiftlang/swift-foundation/pull/1094 and https://github.com/swiftlang/swift-foundation/pull/1095
**Risk:** Low - replace a legacy libc function call with a modern one, gate a few parts behind `os(WASI)`
**Testing:** swift-ci testing
**Reviewer:** @jmschonfeld
> [6.1] Fix WASI build of `_copyDirectoryMetadata`

- Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
In recurrence rules without a strict matching policy, we'd sometimes come across dates which don't exist (such as February 29, 2009). When adjusting these dates, we were passing unadjusted date components. That resulted in adjusted dates with the highest unspecified component different than the original date. For example, adjusting February 29, 2009 to match components {month: 2, day: 29} would result February 29, 2012, instead of Match 1 or February 28 of the same year.
Adjusting the date components (that is, setting the year to 2009 for the example above) fixes this. This is what we already do in Calendar.dates(byMatching: ...)
> Properly adjust invalid dates in RecurrenceRule enumeration

- Sources/FoundationEssentials/URL/URL.swift
Compatibility path for apps that recurse on `url = url.deletingPathComponent().standardized` until `url.path.isEmpty`.
Before Swift `URL`, this used to work due to a combination of two bugs where:
```
URL("/").deletingLastPathComponent == URL("/../")
URL("/../").standardized == URL("")
```
both of which are incorrect behaviors. This PR adds a compatibility path to prevent the infinite loop and crash.
> Compatibility path for apps looping on URL.deletingLastPathComponent().standardized

- Sources/FoundationEssentials/URL/URL.swift
> Make URLResourceValues private properties internal

- Sources/FoundationEssentials/URL/URLComponents_ObjC.swift
- Sources/FoundationEssentials/URL/URLParser.swift
Allow compatibility-mode Swift URL parsing to be called directly from ObjC, saving an `NSURLComponents` allocation and improving performance.
> Allow URLParser to be called directly from ObjC

- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationEssentials/URL/URLComponents.swift
- Tests/FoundationEssentialsTests/URLTests.swift
The following code can recursively call `.path()`, causing an infinite loop.
```
let str = "./not a scheme:"
let baseStr = "base"
let base = URL(string: baseStr)!
let url = URL(string: str, relativeTo: base)!
print(url.path()) // Infinite loop
```
The issue is that `self.path()` calls `.absoluteURL.path()` if `self` has a base URL. `.absoluteURL` _should_ never have a base URL, so this shouldn't recurse. However, if `URL(string: absoluteString)` fails like it does in this example, then `.absoluteURL` returns `self`, causing the recursion.
In the example above, merging the relative and base paths gives us `./not%20a%20scheme:` since they are both relative. Then, we remove the dot segments as specified by the RFC algorithm, giving us `not%20a%20scheme:`. We assign this to a …
> URLComponents.string should percent-encode colons in first path segment if needed

- Sources/FoundationInternationalization/Formatting/Number/Decimal+ParseStrategy.swift
- Sources/FoundationInternationalization/Formatting/Number/FloatingPointFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Number/FloatingPointParseStrategy.swift
- Sources/FoundationInternationalization/Formatting/Number/ICULegacyNumberFormatter.swift
- Sources/FoundationInternationalization/Formatting/Number/IntegerFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Number/IntegerParseStrategy.swift
- Sources/FoundationInternationalization/ICU/ICU+Enums.swift
- Sources/TestSupport/TestSupport.swift
- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/NumberParseStrategyTests.swift
Currently parsing a currency string would fail if the currency code does not match `FormatStyle`'s locale region. 
For example,
```swift
let style = Decimal.FormatStyle.Currency(code: "GBP", locale: .init(identifier: "en_US")).presentation(.isoCode)
```
This formats 3.14 into `"GBP\u{0xa0}3.14"`, but parsing such string fails. 
Fix this by always set the ICU formatter's currency code.
Resolves rdar://138179737
> Fix parsing foreign currency strings

- Sources/FoundationEssentials/FileManager/FileOperations.swift
__Explanation:__ A single type conversion that @hyp added after bb3fccfa3 to get Android armv7 building again, this is [the last patch I apply on my Android CI for this repo for 6.1](https://github.com/finagolfin/swift-android-sdk/blob/main/swift-android-foundation-devel.patch).
__Scope:__ Should do nothing on most platforms
__Issue:__ None
__Original PR:__ #1086
__Risk:__ very low
__Testing:__ Passed all CI on trunk and my Android CI for the last month
__Reviewer:__ @compnerd
> [6.1][android] fix 32-bit build (#1086)

- Sources/FoundationEssentials/String/String+Internals.swift
The CoreFoundation-level file system representation APIs allow for filling a provided buffer and returning a boolean value indicating success or failure. In some cases, we've seen clients partially filling a buffer, failing, and then reading the buffer despite the `false` return value. We can't avoid writing partial results to the buffer (as some clients depend on the partial results) but we can ensure that the buffer ends with a null terminator even in cases of failure. While the buffer may contain incorrect values, it will at least prevent simple buffer over-reads caused by immediate calls to functions like `strlen` on the return value.
> Prevent potential buffer over-reads of file system representations

- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationEssentials/URL/URLComponents.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Recent regression from reverting to compatibility `URL` behaviors in #1113.
`URL.absoluteString` uses `URLComponents` to build the string from the correct parts of the relative and base URLs. After allowing `URL` to have an empty scheme for compatibility in #1113, `URL.absoluteString` would crash if we used an empty scheme from the base URL. The crash occurs when we assign `components.scheme = ""` since `URLComponents` does not consider an empty scheme valid.
Since we are only using `URLComponents` to produce an absolute string, we can bypass the scheme validation with an internal function, since the scheme used for the URL's `absoluteString` has already been validated by the base `URL`.
> URL.absoluteString crashes if baseURL starts with colon

- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
- Remove an unused variable.
- Calling `JSONDecoder`'s `func decode<T: Decodable>(_ type: T.Type, from data: Data) throws -> T` with `Decimal.FormatStyle.Currency` as the type isn't correct. But for some reason, the compiler allows it incorrectly. Fix it.
- Clean up whitespaces while we're here.
> Clean up for #1074

- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationEssentials/URL/URLParser.swift
`CFURL` historically allowed URLs such as `scheme://host:port-string` as long as the port string only contained valid URL characters (characters that can exist in at least some part of a URL string). RFC 3986 only allows digits in the port, so this breaks that use case when a `CFURL` is bridged to `URL`. This PR allows `URL` to have non-numeric ports with valid URL characters, but only in the case of bridging.
> Allow non-numeric port when bridging from CFURL

- Evolution.md
This section is adapted from [that of Swift-Evolution](https://github.com/apple/swift-evolution/blob/main/process.md#review-announcement)
> Add review announcement section to the Evolution document

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/String/String+Bridging.swift
This PR publishes the `NSString` -> `String` bridging code and moves a handful of extensions out of `FileManager` to the bottom of String.swift to work around swiftlang/swift #78731.
> Publish NSString bridging

- Sources/FoundationEssentials/String/CMakeLists.txt
This PR includes the new `String+Bridging.swift` file in `CMakeLists.txt` to ensure `swift-foundation` builds correctly.
> Include String+Bridging.swift in CMakeLists.txt

- Sources/FoundationEssentials/Locale/Locale_Cache.swift
Currently, we do not cache the current Swift locale if we cannot fetch proper preferences. This allows us to update the cached value if subsequent access succeeds.
We should be doing that for `currentNSLocale` too, but we are not. Fix the logic so that the behaviors match.
Resolves rdar://142699797
> Do not cache NSLocale.current if we fail to fetch preferences

- Sources/FoundationEssentials/PropertyList/PlistEncoder.swift
This avoids a duplicate ObjC class warning when testing on macOS.
> Only use objc name for PropertyListEncoder when building for the framework

- Sources/FoundationEssentials/URL/URLComponents.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Apps can take a URL string like
```
://host/path
```
which `URL` now allows (after the compatibility change to go back to allowing an empty scheme), and pass it to `URLComponents(string:)`. `URLComponents` follows RFC 3986, which says a scheme cannot be empty, so it interprets the whole string as a path. The app could then use `components.queryItems = ...` to assign query items and call `components.url`, which needs to generate the new `.string`.
During string generation, `URLComponents` percent encodes the colon at the beginning of the path, so the `URL` returned does not have the scheme, host, and path it started out with. We can fix this by not percent-encoding any colons in the first path segment if the colon is the first character in the string.
This still preserves the behaviors of …
> Don't encode colon if URLComponents path starts with colon

- Sources/FoundationEssentials/AttributedString/AttributeScope.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
Adds a new `AttributeScope` property to provide a public sequence of attribute keys within the scope
> AttributedString Scope Enumeration

- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationEssentials/URL/URLParser.swift
Previously on Darwin, all `URL` initializers created an `NSURL` then ran it through a conversion function to resolve any file reference URLs (with `/.file/id=` paths). This was done to prevent `URL` from ever being a file reference URL, since that changes the nullability of many functions' return values.
With the Swift `URL` implementation, I kept the conversion when bridging `NSURL` to `URL`, but I forgot that resolving the file reference needs to occur in _every_ initializer, e.g. to prevent `URL(string: "file:///.file/id=xxxxxx")` from storing a file reference.
This PR changes all `URL` inits to check if we have a file reference path, and if so, convert it to an actual path.
> URL inits should resolve file reference paths

- Sources/FoundationEssentials/String/String+Bridging.swift
Temporarily removes this piece of string bridging behavior while we work out some compatibility issues with existing clients.
> Temporarily remove special tagged pointer string bridging behavior

- CMakeLists.txt
- Package.swift
- Tests/FoundationEssentialsTests/DateTests.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
- Tests/FoundationEssentialsTests/Formatting/BinaryInteger+FormatStyleTests.swift
- Tests/FoundationEssentialsTests/Formatting/ISO8601FormatStyleParsingTests.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
- Tests/FoundationEssentialsTests/SortComparatorTests.swift
- Tests/FoundationEssentialsTests/StringTests.swift
- Tests/FoundationEssentialsTests/URLTests.swift
- Tests/FoundationEssentialsTests/UUIDTests.swift
- Tests/FoundationInternationalizationTests/CalendarRecurrenceRuleTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
- Tests/FoundationInternationalizationTests/Formatting/ByteCountFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateRelativeFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DiscreteFormatStyleTestUtilities.swift
- Tests/FoundationInternationalizationTests/Formatting/DurationTimeFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DurationUnitsFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/ListFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/NumberParseStrategyTests.swift
- Tests/FoundationInternationalizationTests/PredicateInternationalizationTests.swift
- Tests/FoundationInternationalizationTests/SortDescriptorTests.swift
As we add new APIs and features to Foundation, we plan to adopt new APIs from the Swift standard library that were introduced in the macOS 15-aligned releases. Using these features requires that we increase the minimum deployment target of the SwiftPM build (used for ease of at-desk to macOS 15). This increases the deployment target accordingly so that we can begin to adopt these new APIs without guarding for macOS 15 availability.
In order to bumping the deployment target version, this change also:
- Updates some code in a handful of unit tests to deal with new ambiguity discovered by the compiler (these ambiguity issues stem from new APIs added to Foundation.framework in macOS 15 that were previously disfavored due to lacking matching availability but are now equally favored due to the …
> Increase package deployment target to macOS 15

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
When calling `quotactl` on Darwin as part of `FileManager.attributesOfFileSystem(atPath:)`, we take the effective user ID (a `uid_t`) and attempt to pass it to `quotactl` (whose parameter is a C `int` imported as `Int32`). The cast we perform currently causes a crash when the current EUID is greater than `Int32.max`. This is an annotation issue with `quotactl` which should be taking an unsigned integer instead of a signed integer. For now, to prevent the crash and restore the pre-swift-rewrite behavior, we can change this to a bit-pattern cast so that when `quotactl`'s implementation reinterprets the number as an unsigned integer it works.
Unfortunately there's no way to add a unit test for this as it requires the current EUID to be an abnormally large value which is not possible in our …
> Prevent crashing when calling quotactl with UIDs greater than Int32.max

- Sources/FoundationEssentials/CMakeLists.txt
In preparation for supporting static library linking on Windows, we are adjusting the library naming convention for static Swift libraries, preferring to use `lib<name>.lib` to differentiate them from the import library for a dynamic variant of the same library. This mechanism is already known to be used by Microsoft for ucrt (`ucrt.lib` vs `libucrt.lib`), and was previously used in Swift as well for the C++ interop libraries.
> build: support a non-standard library prefix for Windows

- Sources/FoundationEssentials/Data/Data+Reading.swift
The custom deallocator is passed a pointer to the allocated buffer, _not_ the underlying handle. The call to `CloseHandle` here was failing with `ERROR_INVALID_HANDLE`, but by changing the callback parameter to shadow `pData` instead of `hMapping` (and updating the call to `UnmapViewOfFile`), the call to `CloseHandle` now runs on the expected captured `hMapping` handle.
cc @compnerd
> Fix Windows .alwaysMapped deallocator

- Sources/FoundationEssentials/Data/Data+Reading.swift
(cherry picked from commit 281db8e767eeeb679510d81b06c8d1778f91b66e)
> [6.1] Fix Windows .alwaysMapped deallocator (#1147)

- Tests/FoundationInternationalizationTests/LocaleComponentsTests.swift
The behavior regarding parsing a POSIX string will change in ICU-76. While we haven't updated ICU dependency to ICU-76 yet, test will fail when we do. Disable the test for now.
I'll follow up with ICU owners to figure out the expected behavior and update the test or implementation if needed.
resolves 143438257
> Disable a test that fails with ICU-76

- Benchmarks/Benchmarks/AttributedString/BenchmarkAttributedString.swift
- Benchmarks/Package.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Guts.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringAttributeStorage.swift
When removing an attribute from an `AttributedString`, we iterate through each run and remove the value from the attribute storage for each run. After mutating a run, we need to check to see if that run needs to be coalesced with the surrounding runs. Previously when removing an attribute that didn't exist, we still checked whether each run needed to be coalesced with its surrounding runs. However, we only need to check this if we actually removed an item from the storage (otherwise the storage remains unchanged and the check is unnecessary, and potentially costly). Since the underlying `Dictionary` API already tells us when removing an item whether it existed to begin with, we can feed that information to the run enumeration to decide whether the coalescing check should be run. In a …
> Optimize removing nonexistent attributes in AttributedString

- Sources/FoundationEssentials/Calendar/Calendar_Cache.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
Use the `_CalendarGregorian` implementation for the ISO8601 calendar, instead of ICU. This lowers it into FoundationEssentials. Previously, the same behavior could be achieved by customizing the init of a Gregorian calendar, but this makes it easier to do the right thing.
> Use _CalendarGregorian for ISO8601

- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+AttributeSlices.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
Minor update to this SPI to make it more usable for its callers
> AttributesString.Runs.subscript(nsAttributedStringKeys:) should accept array of keys rather than variadic

- Tests/FoundationEssentialsTests/DataTests.swift
There are some code paths in base64 encoding that are currently undertested. This PR tries to fill the gap here. It adds tests mostly around base64 scenarios in which line breaks are required.
> Add additional base64 tests

- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+AttributeSlices.swift
With further testing, it's not safe to remove the existing SPI here in favor of the new one so this change adds the existing SPI back alongside the new SPI
> Re-add existing SPI for enumerating NSAttributedString.Key Runs

- Sources/FoundationEssentials/Date.swift
Unlike other `import Glibc` platforms, FreeBSD needs to standard format to produce correct output. Otherwise, the year components is set to the `4Y` constant.
> Fix FreeBSD date formatting

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Sources/FoundationEssentials/PropertyList/PlistDecoder.swift
- Sources/FoundationEssentials/PropertyList/PlistEncoder.swift
This requires that the userInfo values are `Sendable` since they are stored in `Sendable` types. The `@preconcurrency` attribute ensures that this is not an ABI breaking change or a source breaking change for projects using the Swift 5 language mode.
> JSON/PropertyList coders userInfo should require Sendable values

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Sources/FoundationEssentials/PropertyList/PlistDecoder.swift
- Sources/FoundationEssentials/PropertyList/PlistEncoder.swift
Reverts swiftlang/swift-foundation#764. Linux + Windows toolchains are now both failing.
> Revert "JSON/PropertyList coders userInfo should require Sendable values"

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
Reverts #1168 because it breaks swift-ci: https://ci.swift.org/job/oss-swift-RA-linux-ubuntu-22_04-long-test/8314/
> Revert "New Calendar Identifiers (#1168)"

- Sources/FoundationEssentials/String/String+IO.swift
- Tests/FoundationEssentialsTests/StringTests.swift
Historically, `NSString` has dropped a UTF-8 BOM if present while parsing UTF-8 bytes, however the Swift implementation of `String(bytes:encoding:)` does not exhibit this behavior. While a UTF-8 BOM is not required since UTF-8 bytes can only have one ordering, there are still applications that may output this BOM at the start of a sequence of UTF-8 bytes. It seems reasonable that a higher level API like Foundation which handles BOMs in UTF-16/UTF-32 bytes would also be resilient in handling the presence of a UTF-8 BOM (unlike the stdlib-provided `String(decoding:as:)` APIs which are lower-level and do not handle BOMs or encodings of a particular endianness). This change drops the UTF-8 BOM from the decoded bytes if it is present at the start of the bytes (but only at the start of the …
> Drop UTF-8 BOM when present while decoding UTF-8 bytes into String

- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
- Tests/FoundationEssentialsTests/ProcessInfoTests.swift
Apart from a trivial change for `ProcessInfoTests`. This PR make `FileManagerTests` to compare the sorted output instead since this test sometimes fails due to the ordering of elements in the array.
> Fix FreeBSD tests

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Sources/FoundationEssentials/PropertyList/PlistDecoder.swift
- Sources/FoundationEssentials/PropertyList/PlistEncoder.swift
Another attempt at https://github.com/swiftlang/swift-foundation/pull/764 to land after blocking compiler changes land
> JSON/PropertyList coders userInfo should require Sendable user info values

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
Exposed identifiers for 12 calendars. API Proposal: [SF-017](https://github.com/swiftlang/swift-foundation/blob/main/Proposals/0017-expanded-calendar-support.md)
This is take two, as we needed to revert the [first attempt](https://github.com/swiftlang/swift-foundation/pull/1168) due to CI failures.
141795986
> New Calendar Identifiers

- Sources/FoundationEssentials/PropertyList/XMLPlistScanner.swift
- Tests/FoundationEssentialsTests/PropertyListEncoderTests.swift
A mistake was made during translation of PropertyListSerialization XML parsing to native PropertyListDecoder with regard to open tags.
`PropertyListSerialization` accepts open tags that look like any of the following:
```
`<` <VALIDTAG> `>`
`<` <VALIDTAG> `/` `>`
`<` <VALIDTAG> <WHITESPACE> <ANYTHING> `>`
```
The latter case is to handle tags with attributes, which are typically only used on the `plist` tag, e.g. `<plist version="1.0">`.
The adapted code was too permissive and accepted:
```
`<` <VALIDTAG> <ANYTHING> `>`
`<` <VALIDTAG> <ANYTHING> `/` `>`
```
Which means we accepted input like:
```
<stringGARBAGE>foo</string>
```
This PR fixes that by checking the next character after a valid tag name before accepting it.
> New XML PropertyListDecoder parser accepts malformed tags

- .spi.yml
The Swift Package Index is capable of hosting documentation. `swift-foundation` is currently not publishing documentation there but it would be really helpful to understand what types are available in the `FoundationEssentials` and `FoundationInternationalization` modules.
This PR adds an `.spi` file to trigger the generation of documentation by the Swift Package Index.
Publicly hosted documentation for the products provided by `swift-foundation`
> Add `.spi` file to generate documentation

- NOTICE.txt
- Sources/FoundationEssentials/Data/Data+Base64.swift
This pr should be rebased after #1155 has landed.
I'll post benchmark comparisons soon.
> Base64 faster encode

- Tests/FoundationEssentialsTests/PropertyListEncoderTests.swift
https://github.com/swiftlang/swift-foundation/pull/1180 accidentally introduces a build issue on macOS due to new ambiguity between `Foundation.String.Encoding` and `FoundationEssentials.String.Encoding` but we weren't able to detect that since macOS CI is currently nonfunctional. This fixes the ambiguity using the same trick we use elsewhere in our unit tests. I've validated locally that this fixes the build issues on macOS.
> Fix ambiguity on macOS in PropertyListEncoderTests

- Sources/FoundationEssentials/Data/Data+Base64.swift
- Tests/FoundationEssentialsTests/DataTests.swift
Fixes: https://github.com/swiftlang/swift-corelibs-foundation/pull/5174/files
> [Base64] Fix: Dont add line separators in last line when last line fits

- Tests/FoundationEssentialsTests/DataTests.swift
In #1184 I accidentally added trailing commata in the test cases. This compiles fine in 6.1. But it doesn't in 6.0.
> [Base64] Tests: remove trailing commata

- Benchmarks/Package.swift
- CMakeLists.txt
- Package.swift
- Sources/FoundationMacros/CMakeLists.txt
- **Explanation**: Updates the dependencies declared in the SwiftPM package manifest and `CMakeLists.txt` files to match the versions of the dependencies actually used when building the toolchain. Having these be correct will be important when making lockstep changes (for example, between swift-foundation and swift-syntax) so that if a dependency like swift-syntax makes a breaking change on `main` it will not break the build of our package's `release/6.1` branch due to incorrectly depending on the wrong branch.
- **Scope**: Only affects the version of used dependencies and does not change the project's code itself. Also only impacts "local" builds and not any toolchain builds
- **Issues**: N/A
- **Original PRs**: N/A
- **Risk**: Low - does not impact toolchain build and change is intended …
> [6.1] Update SwiftPM/CMake dependencies to match toolchain build

- Sources/FoundationMacros/PredicateMacro.swift
This accompanies the [swift-syntax](https://github.com/swiftlang/swift-syntax/pull/2950) and [compiler implementation](https://github.com/swiftlang/swift/pull/78823) for [Method and Initializer Keypaths](https://github.com/swiftlang/swift-evolution/pull/2675) which extends keypath usage to include references to methods and initializers.
Key path`.method` handling is currently unimplemented for `#Predicate` and will be added once this feature is accepted and slotted to be made available in a future version of Swift.
> Add default keypath method handling for #Predicate.

- Sources/FoundationEssentials/AttributedString/AttributedString+CharacterView.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Guts.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+IndexValidity.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+AttributeSlices.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+Run.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+UTF16View.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+UTF8View.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+UnicodeScalarView.swift
- Sources/FoundationEssentials/AttributedString/AttributedString.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringProtocol.swift
- Sources/FoundationEssentials/AttributedString/AttributedSubstring.swift
- Sources/FoundationEssentials/AttributedString/CMakeLists.txt
- Sources/FoundationEssentials/AttributedString/Conversion.swift
- Sources/FoundationEssentials/AttributedString/DiscontiguousAttributedSubstring.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringIndexValidityTests.swift
This PR implements the index validity checking APIs as proposed in [SF-0015](https://github.com/swiftlang/swift-foundation/blob/main/Proposals/0015-attributedstring-tracking-indices.md) by adding a new version number tracked within each `AttributedString` and `AttributedString.Index`. As neither type is frozen, we have the flexibility in the future to optimize this (for example, by taking advantage of the version number stored within the already-nested `BigString.Index` if the swift-collections package provided access to it) if we deem necessary.
> AttributedString Index Validity APIs

- Sources/FoundationEssentials/AttributedString/AttributedString+Guts.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+IndexTracking.swift
- Sources/FoundationEssentials/AttributedString/CMakeLists.txt
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringCOWTests.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringIndexTrackingTests.swift
This implements tracking of `AttributedString` indices across mutations
> AttributedString Index Tracking

- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationEssentials/URL/URLComponents.swift
- Sources/FoundationEssentials/URL/URLParser.swift
- Tests/FoundationEssentialsTests/URLTests.swift
**Explanation:** Cherry-picking `URL` bug fixes that improve compatibility and stability, aligning the 6.1 behavior with what we expect moving forward.
**Scope:** Impacts some `URL` and `URLComponents` APIs that were found to cause bincompat issues in apps due to new behavior. Changes were made to be more compatible with usage that was previously allowed. See #1113 for more details. Other PRs are small follow-on fixes for crashes or unintended behavior as a result of #1103 and #1113.
**Original PRs:** #1103, #1110, #1113, #1117, #1119, #1139 
**Risk:** Low - restores previous behaviors or fixes crashes, well-tested on Darwin and swift-foundation `main` branch.
**Testing:** Added unit tests, swift-ci, testing on Darwin, stable in `main` for 1-2 months.
**Reviewers:** @jmschonfeld, …
> [6.1] URL compatibility and bug fixes

- Proposals/0017-expanded-calendar-support.md
Due to lack of an authoritative source of calendrical calculations, we’re not able to add support for the Thai lunisolar calendar in ICU and correspondingly in Swift Foundation. This is to update the proposal to remove the identifier that was previously exposed with #1138.
API Update in #1203.
> [SF-0017] Expanded Calendar Support (Update)

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
Due to lack of an authoritative source of calendrical calculations, we’re not able to add support for it in ICU and correspondingly in Swift Foundation. Removing the identifier that was previously exposed with #1171.
API Proposal Update in #1202.
145890794
> Remove Thai Calendar

- Sources/FoundationEssentials/Calendar/Calendar.swift
Some app is passing in `value: -9223372036854775808` to the function below, and force unwrapping the result. It then crashes when the force unwrap fails.
```swift
/// - returns: A new date, or nil if a date could not be calculated with the given input.
public func date(byAdding component: Component, value: Int, to date: Date, wrappingComponents: Bool = false) -> Date?
```
The crash is caused by #1149. Prior to the change, we were using `_CalendarICU`'s implementation, where we truncate the input value to `Int32`, which becomes 0 in this case. That results in us returning the input `date` unchanged.
Now with #1149, we truthfully return `nil` because the calculation cannot be done.
We could restore the old behavior, but that implementation is incorrect. It's also clearly a wrong assumption …
> Introduce compatibility behavior of `Calendar.date(byAdding:value:to:wrappingComponents)`

- Sources/FoundationEssentials/AttributedString/AttributeContainer.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+Run.swift
- Sources/FoundationEssentials/AttributedString/AttributedString.swift
- Sources/FoundationEssentials/AttributedString/AttributedSubstring.swift
- Sources/FoundationEssentials/AttributedString/DiscontiguousAttributedSubstring.swift
When profiling some uses of `AttributedString`, we noticed that simple attribute mutations like `attrStr.languageIdentifier = "en"` spend a decent amount of time in `swift_getKeyPath` allocating and initializing a `KeyPath` to provide to the `dynamicMemberLookup` subscript. In reality, this `KeyPath` instance is never used, we only use it to infer the type of the `K: AttributedStringKey` generic argument and then the implementation of this subscript forwards that type on to the subscript that accepts a concrete type. By marking the dynamic member subscripts (at least those that are trivially implemented) `@inlinable`, the compiler can see the immediate indirection to the alternative subscript and inline it which then allows the optimizer to optimize away the allocation/initialization and …
> Make trivial AttributedString dynamicMemberLookup subscripts inlinable

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Date+FormatStyle.swift
- Sources/FoundationEssentials/Formatting/Date+HTTPFormatStyle.swift
- Sources/FoundationEssentials/Formatting/Date+ISO8601FormatStyle.swift
- Sources/FoundationEssentials/Formatting/FormatParsingUtilities.swift
- Tests/FoundationEssentialsTests/Formatting/HTTPFormatStyleFormattingTests.swift
Adds a prototype HTTP format style for `Date` and `DateComponents`.
(https://forums.swift.org/t/pitch-http-date-format-style/76783)
> Add an HTTP format style for both `Date` and `DateComponents`

- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Data/Data.swift
Remove some compatibility paths for NO_FILESYSTEM and further unify Data reading/writing.
> Clean up some NO_FILESYSTEM paths

- Sources/FoundationEssentials/FileManager/FileOperations.swift
`_copyDirectoryMetadata` does not compile on FreeBSD since `f{list,get}xattr` is not available. Use `extattr_*_fd` to copy extended attributes recursively instead.
Unlike the Linux variant, `extxattr_*(2)` does not return an entry list with null terminating attribute names. Instead, each list entry consists of a single byte containing the length of the attribute name follow by the non-null terminating name itself.
To iterate each entry:
- we prepare a null-terminating terminating temporary buffer of to store the entrylist, plus 1 null terminator.
- we first get the length of the first entry
- in each iteration, we store the length of next entry and replace the length byte of the next entry with NULL, this effectively make the current attribute name a NULL-terminating string, that we can …
> Fix `_copyDirectoryMetadata` compilation error on FreeBSD

- Sources/FoundationEssentials/String/String+IO.swift
- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
- Tests/FoundationEssentialsTests/StringTests.swift
As mentioned in https://github.com/swiftlang/swift-foundation/issues/1216, the ISO Latin 1 Encoding/Decoding written natively in swift-foundation does not behave correctly. I accidentally referenced an incorrect code page table when writing the original implementation which limited the supported characters to a subset of those actually supported. In reality, ISO Latin 1 is just the 0x0 through 0xFF unicode code points encoded as single bytes. This means that encoding should simply encode the code point value (and fail for any code point greater than 0xFF) and decoding can simply extend each byte to 16 bits and parse as UTF-16 since all bytes are valid by definition.
This updates the implementation and adds some extra characters to the unit test to validate this behavior.
> Fix ISO Latin 1 Encoding/Decoding issues

- CMakeLists.txt
Per @al45tair - Foundation should build with -fno-omit-frame-pointer on Linux (which is typically off by default on some distributions) in order to help capture better backtraces.
> Build with -fno-omit-frame-pointer on Linux

- Sources/FoundationEssentials/String/String+IO.swift
- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
- Tests/FoundationEssentialsTests/StringTests.swift
- **Explanation**: Fixes a behavior issue with String ISO Latin 1 encoding that prevents some characters from being successfully encoded/decoded
- **Scope**: Only impacts ISO Latin 1 String encoding/decoding via Foundation
- **Issues**: N/A
- **Original PRs**: https://github.com/swiftlang/swift-foundation/pull/1219
- **Risk**: Low - scope is minimal and likely not widely used and change is well tested
- **Testing**: Unit testing locally and via swift-ci
- **Reviewers**: @parkera
> [6.1] Fix ISO Latin 1 Encoding/Decoding issues

- Sources/FoundationEssentials/String/String+IO.swift
- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
Add an upcall to swift-corelibs-foundation for converting String encodings that swift-foundation does not implement.
Partially resolves https://github.com/swiftlang/swift-foundation/issues/1216.
> Add an upcall point to swift-corelibs-foundation for String encoding conversion

- Benchmarks/Benchmarks/AttributedString/BenchmarkAttributedString.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Guts.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs.swift
- Sources/FoundationEssentials/AttributedString/DiscontiguousAttributedSubstring.swift
Two `AttributedString`s with differing character counts will never compare equal. When we can cheaply determine that the character counts are inequal, we should return early from `AttributedString.==` rather than comparing each runs contents. This situation can be quite common (for example, just appending a single character to the end of the last run like when a user types into a text box) and it turns a full run-by-run comparison of the entire string into a single constant time evaluation. The benchmark results highlight that for this worst-case, but common, scenario the wins are significant:
```
╒══════════════════════════════════════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╕
│          Throughput (# / s) (M)          │      p0 │     p25 │ …
```
> Improve performance for comparing AttributedStrings with differing character counts

- Benchmarks/Benchmarks/DataIO/BenchmarkDataIO.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Data/Data.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/String/String+IO.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
fixes swiftwasm/swift#5593
`FileManager.createFile()` currently doesn't work on WASI because it requires `.atomic`, it requires creating a temporary file, and it isn't suppported on WASI.
So I have fixed that by removing the `.atomic` requirement only on WASI.
> [wasm] Make `FileManager.createFile()` work on WASI

- Sources/FoundationEssentials/Data/Data+Reading.swift
Use nonblocking for `open`, so if the file is non-regular then we can proceed past this call without blocking. A later check will verify the kind of file with `fstat`.
> Use nonblocking IO for open

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
Match the previous behavior of an `iso8601` calendar by setting the time zone to the `default` (which falls back to `current`) instead of using only `gmt`.
> Use the default time zone instead of gmt

- Benchmarks/Benchmarks/AttributedString/BenchmarkAttributedString.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+AttributeSlices.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringAttribute.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringAttributeConstrainingBehavior.swift
Attributes bound to particular run boundaries (paragraphs, characters, etc.) are guaranteed to have consistent values between each boundary. This invariant is enforced at mutation time so that reading the attributed string can take advantage of this information. One place where we have yet to take advantage of this is when enumerating runs sliced to a particular attribute (for example `attrStr.runs[\.someParagraphConstrainedAttribute]`). Currently, we follow these steps to find the end of a coalesced run:
- Iterate run-by-run through the storage comparing attribute values until we find the run where the attribute value has changed
- If we have iterated past the end of the current chunk in a discontiguous slice, jump back to the end of the chunk
- Scan the original location through the …
> Improve performance of enumerating constraint-bound attributes consistent across many runs

- Sources/FoundationMacros/PredicateMacro.swift
This resolves a deprecation warning that was introduced by a swift-syntax change. We resolve the deprecation by switching to the recommended initializer.
> Resolve deprecation warning in Foundation Macros concerning FunctionCallExprSyntax initializer

- Benchmarks/Benchmarks/Formatting/BenchmarkFormatting.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Calendar/DateComponents.swift
- Sources/FoundationEssentials/Formatting/Date+HTTPFormatStyle.swift
- Sources/FoundationEssentials/Formatting/Date+ISO8601FormatStyle.swift
- Sources/FoundationEssentials/Formatting/DateComponents+ISO8601FormatStyle.swift
- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Sources/FoundationEssentials/TimeZone/TimeZone.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_GMT.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Protocol.swift
- Tests/FoundationEssentialsTests/Formatting/ISO8601FormatStyleFormattingTests.swift
- Tests/FoundationEssentialsTests/Formatting/ISO8601FormatStyleParsingTests.swift
Add an ISO8601 components format style. See [pitch thread](https://forums.swift.org/t/pitch-iso8601-components-format-style/77990).
Resolves:
https://github.com/swiftlang/swift-foundation/issues/323
https://github.com/swiftlang/swift-foundation/issues/967
https://github.com/swiftlang/swift-foundation/issues/1159
> ISO8601 DateComponents format style

- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/LockedState.swift
- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/_FoundationCShims/include/_CStdlib.h
Fixes a few small matters:
* OpenBSD also needs `pthread_mutex_t?`.
* OpenBSD does not have secure_getenv.
* OpenBSD does not support extended attributes.
* Correct statvfs type casts for OpenBSD.
On OpenBSD, fsblkcnt_t -- the type of f_blocks -- is a UInt64; therefore, so must `blockSize` be.
Ultimately, both sides of the `totalSizeBytes` multiplication should probably be type cast for all platforms, but that's a more significant functional change for another time.
* Update the default to activeProcessorCount and add sysconf support. This is a more sensible default; it does not make sense to have 0 active processors on a running system as I understand the semantics.
Additionally, #1075 beat me to a few small changes; some follow-ups:
* In `FileOperations+Enumeration.swift` originally I …
> OpenBSD support.

- Sources/FoundationEssentials/AttributedString/AttributedStringAttributeStorage.swift
`_attributeModified` is called when an attribute value in an attribute storage dictionary was replaced by a new value. It is responsible for enforcing the invalidation constraints on attributes by removing any dependent attributes from the storage (recursively). Currently (assuming both a new and old value exist) this function unconditionally compares the new and old values to return early if the value didn't change (meaning attributes shouldn't be invalidated). However, this requires unboxing the existential attribute values and calling through to their `==` implementation which can be expensive. Instead, we can make this calculation lazy, only performing it when we actually find another attribute dependent upon the changed one. In cases where there are no dependent attributes, we avoid …
> Lazily compute whether attribute changed in _attributeModified(_:old:new:)

- Sources/FoundationEssentials/AttributedString/FoundationAttributes.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
The implementation for https://github.com/swiftlang/swift-foundation/pull/1234
> Writing Direction Attribute Implementation

- Sources/FoundationEssentials/CodableUtilities.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL/CMakeLists.txt
- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationEssentials/URL/URLComponents.swift
- Sources/FoundationEssentials/URL/URLComponents_ObjC.swift
- Sources/FoundationEssentials/URL/URLParser.swift
- Sources/FoundationEssentials/URL/URL_Bridge.swift
- Sources/FoundationEssentials/URL/URL_ObjC.swift
- Sources/FoundationEssentials/URL/URL_Protocol.swift
- Sources/FoundationEssentials/URL/URL_Swift.swift
- Tests/FoundationEssentialsTests/StringTests.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Changes to allow `NSURL` and `CFURL` to use the Swift `URL` implementation. With this refactoring, the behavior of `URL` should be identical, except for a few minor compatibility/bug fixes to the parser and URL functions, revealed by NS/CFURL test failures with the re-core enabled. The overall architecture has a bit of complexity in order to support:
- file reference `NSURL`s, but not `URL`s,
- subclassed `NSURL`s, and
- the ability to bridge a `NSURL` to Swift while maintaining the same object pointer returned by functions like `.absoluteURL` (returning `self`) and `.baseURL`, which is the previous behavior, and one I believe could have implications for reference counting in ObjC/C land.
This PR changes `struct URL` to wrap a single class that implements each of its methods. In …
> Support NS/CFURL re-core in Swift

- Sources/_FoundationCShims/include/_CStdlib.h
Those constants are not used on WASI in Swift side, so there's no need to require them in the C headers. The `#error` was introduced by 03fe46f43b3a2d8d9159d46a1f56517acc525e69.
> [wasm] Stop requiring `TZDIR` and `TZDEFAULT` on WASI

- Sources/FoundationEssentials/AttributedString/AttributedStringAttributeConstrainingBehavior.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringConstrainingBehaviorTests.swift
When inserting a character into an attribute run, if that run contains any text-dependent attributes we should invalidate those attributes. However if the text is inserted between two runs of that attribute value, neither surrounding run should be invalidated. This updates `enforceAttributeConstraintsBeforeMutation(to:)` to ensure that we handle an empty range mutation (i.e. an insertion) correctly rather than skipping constraint enforcement for empty ranges.
rdar://149623441
> AttributedString character insertion doesn't invalidate text dependent attributes

- Sources/FoundationEssentials/URL/CMakeLists.txt
https://github.com/swiftlang/swift-foundation/pull/1198 added most of the new files, but missed `URLTemplate_Expression.swift`, add it.
> Update `CMakeLists.txt` with missing `URLTemplate_Expression.swift`

- Tests/FoundationEssentialsTests/URITemplatingTests/URLTemplate_ExpressionTests.swift
`TestSupport` already defines a typealias for `Expression` as `public typealias Expression = Foundation.Expression`. Therefore the top level typealias `private typealias Expression = URL.Template.Expression` caused an error when `TestSupport` is imported.
Move the typealias declaration to inside the test suite.
> Follow up for #1198: Fix test  for FOUNDATION_FRAMEWORK

- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
This is a similar fix to https://github.com/swiftlang/swift-corelibs-foundation/pull/5204 but for `FoundationInternationalization` instead of `plutil`. Specifying `Character` explicitly here avoids attempting to link a RegexBuilder symbol instead of the symbol from the standard library.
> [FoundationInternationalization] Avoid implicitly linking RegexBuilder symbol

- Sources/FoundationEssentials/URL/URLParser.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Previously, `URL` and the `URLParser` mistakenly allowed invalid characters in an IP-literal (within the square brackets) if the zone-ID was percent-encoded. This was revealed by testing the `NSURL` and `CFURL` re-core in Swift. My original goal was to make the new implementation match the slightly more strict validation of the old NS/CFURL implementations for compatibility.
However, I misunderstood which characters `CFURL` was actually allowing when validating an IP-literal. Instead of validating hex digits, colons, and periods before a potential zone ID, it was allowing any valid ASCII character anywhere in the host, so malformed URLs like `http://[www.apple.com]` were allowed.
While I think better IPv6 validation would ultimately be good, it could impact bincompat for `URL`, …
> Revert strict IPv6 validation in URL

- Sources/FoundationEssentials/URL/URL.swift
Tested with a recent nightly-main container, and removing the Linux-only workaround `unsafeBitCast == 0x1` check works now that swift-corelibs-foundation was built with the new swift-foundation `URL` changes in #1238.
Removing the other `private var _padding` workaround still causes a crash in libXCTest on Linux, so that will require further investigation.
> Remove URL workaround for Linux crash once SCL-F is rebuilt

- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/String/String+Internals.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
On Windows, there is a built-in maximum path limitation of 260 characters under most conditions. This can be extended to 32767 characters under either of the following two conditions:
- Adding the longPathAware attribute to the executable's manifest AND enabling the LongPathsEnabled system-wide registry key or group policy.
- Ensuring fully qualified paths passed to Win32 APIs are prefixed with \?\
Unfortunately, the former is not realistic for the Swift ecosystem, since it requires developers to have awareness of this specific Windows limitation, AND set longPathAware in their apps' manifest AND expect end users of those apps to change their system configuration.
Instead, this patch transparently prefixes all eligible paths in calls to Win32 APIs with the \?\ prefix to allow them to work …
> Transparently add the \\?\ prefix to Win32 calls for extended length path handling

- Proposals/0024-CurrentBundle.md
- Proposals/NNNN-CurrentBundle.md
This proposal adds a macro to find the bundle that contains resources useful for the current context: `#bundle`.
> [Proposal]: `#bundle` macro

- Sources/FoundationEssentials/AttributedString/FoundationAttributes.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
Now that blocking changes have been resolved, we can remove these `@_spi` markers
> Upgrade AttributedStringWritingDirection SPI to API

- Proposals/0025-markdown-list-delimiters.md
- Proposals/NNNN-markdown-list-delimiters.md
This proposal adds a new `AttributedString` attribute that will be populated when parsing markdown with the delimiter used for entries in a list.
> Markdown List Delimiters

- Sources/FoundationEssentials/URL/URL_Swift.swift
Fixes a compatibility issue that occurs when a `URL` such as `scheme://?query` is bridged to an `NSURL`. `NSURL` originally expected `.path` to return `nil` for this string, but `URL` and RFC 3986 say that the path *always* exists and is the empty string in this case. `URL` would then store an empty path range instead when bridging to `NSURL`, causing this discrepancy.
This PR fixes the issue during bridging by only storing the path range if `NSURL` would think there's a path, i.e. in the case where 1) the path is not empty, or 2) the path is empty, but we have a non-empty authority component.
> Restore selective nil path behavior for bridged NSURLs

- Sources/FoundationEssentials/URL/URLTemplate.swift
- Sources/FoundationEssentials/URL/URLTemplate_Value.swift
- Sources/FoundationEssentials/URL/URLTemplate_VariableName.swift
All public `URL.Template` extensions need to be marked with the `FoundationPreview 6.2` availability since extensions are separate declarations and availability is per declaration. Extensions don't automatically inherit the availability from the type they're extending.
> Fix URL.Template availability annotations

- Package.swift
- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/Locale/Locale+Language.swift
- Sources/FoundationEssentials/URL/URLParser.swift
- Sources/FoundationEssentials/URL/URL_Swift.swift
- Sources/FoundationInternationalization/CMakeLists.txt
- Sources/FoundationInternationalization/ICU/ICU+Foundation.swift
- Sources/FoundationInternationalization/URLParser+ICU.swift
- Sources/FoundationMacros/BundleMacro.swift
- Sources/FoundationMacros/CMakeLists.txt
- Tests/FoundationEssentialsTests/URITemplatingTests/URLTemplate_PercentEncodingTests.swift
- Tests/FoundationEssentialsTests/URITemplatingTests/URLTemplate_TemplateTests.swift
- Tests/FoundationEssentialsTests/URITemplatingTests/URLTemplate_ValueTests.swift
Enable the MemberImportVisibility compiler flag, which ensures that we don't accidentally depend on implicit imports in our sources.
> Enable MemberImportVisibility upcoming feature in Foundation

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/WinSDK+Extensions.swift
Instead of looping 8 times to work around the TOCTOU issue with sizing the current directory buffer, instead keep doubling the buffer up until the 32767 character limit until the result fits. This ensures we always get a working directory if GetWorkingDirectoryW didn't return some other error, rather than returning nil in the case of a race condition.
> Switch to a safer technique for obtaining the working directory on Windows

- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
This fixes the Android [build error](https://github.com/swift-everywhere/swift-package-builds/actions/runs/14801693208/job/41561703634#step:32:2259) that I noted at https://github.com/swiftlang/swift-foundation/pull/1280#issuecomment-2848066387:
```
/home/runner/work/swift-package-builds/swift-package-builds/swift-foundation/Sources/FoundationEssentials/Error/CocoaError+FilePath.swift:76:37: error: initializer 'init(rawValue:)' is not available due to missing import of defining module 'Android'
18 | #elseif canImport(Bionic)
19 | @preconcurrency import Bionic
20 | #elseif canImport(Glibc)
| `- note: add import of module 'Android'
21 | @preconcurrency import Glibc
22 | #elseif canImport(Musl)
:
74 |         // (130280235) POSIXError.Code does not have a case for EOPNOTSUPP
75 | …
```
> Fix @preconcurrency import Android in CocoaError+FilePath.swift

- Sources/FoundationEssentials/URL/URL_Swift.swift
- Tests/FoundationEssentialsTests/URLTests.swift
Maintain previous behavior of appending an empty string to a `URL` with an empty path and host, so that `URL(string: "scheme://").appendingPathComponent("")` returns `scheme://` (no change), while `URL(string: "scheme://example.com").appendingPathComponent("")` returns `scheme://example.com/` (appends a slash).
> Don't add a slash when appending an empty string to an empty path and host

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
Fixes a warning due to `lastElement` being unconditionally false in the non-`FOUNDATION_FRAMEWORK` branch
```
[2025-05-09T17:53:00.386Z] /build/swift-foundation/Sources/FoundationEssentials/FileManager/FileManager+Directories.swift:90:44: warning: will never be executed
[2025-05-09T17:53:00.386Z]  88 |         #endif
[2025-05-09T17:53:00.386Z]  89 |         let urls = Array(_SearchPathURLs(for: directory, in: domain, expandTilde: true))
[2025-05-09T17:53:00.386Z]  90 |         guard let url = lastElement ? urls.last : urls.first else {
[2025-05-09T17:53:00.386Z]     |                         |                  `- warning: will never be executed
[2025-05-09T17:53:00.386Z]     |                         `- note: condition always evaluates to false
[2025-05-09T17:53:00.386Z]  91 | …
```
> Fix FileManager directories warning

- Benchmarks/Benchmarks/URL/BenchmarkURL.swift
The `URL.Template` benchmark code needs to be updated since we removed `ExpressibleByStringLiteral` from `URL.Template.VariableName`.
> Fix URL.Template benchmark variable initialization

- Sources/FoundationEssentials/AttributedString/AttributedString+Runs.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringAttributeStorage.swift
This commit includes a handful of performance improvements for `AttributedString` that provide some great speedups to its `Equatable` conformance and `Runs` view. These are the changes this makes:
`AttributedString` attribute raw value casting: for a little while we've known that comparing `AttributedString` attribute values is more expensive than we'd like. This fixes a few of those issues by:
- Avoiding unnecessarily boxing the existential attribute value in an `Optional` which requires looking up type metadata and allocating space for the optional. This `Optional` in `__equalAttributes` was required previously but is no longer used
- Avoid dynamic casts when casting the attribute values (as existential) to their expected types for fetching values and comparing values. We know that when …
> AttributedString Equatable conformance performance improvements

- Sources/FoundationEssentials/URL/URLTemplate.swift
- Sources/FoundationEssentials/URL/URLTemplate_Expression.swift
- Sources/FoundationEssentials/URL/URLTemplate_PercentEncoding.swift
- Tests/FoundationEssentialsTests/URITemplatingTests/URLTemplate_ExpressionTests.swift
- Tests/FoundationEssentialsTests/URITemplatingTests/URLTemplate_TemplateTests.swift
This fixes #1269
This uses `try! Regex("…")` instead of `RegexBuilder` to create regular expressions used by the URL Template implementation.
> Move off of RegexBuilder for URL.Template

- Sources/FoundationEssentials/AttributedString/AttributedStringAttributeStorage.swift
This reverts a small portion of https://github.com/swiftlang/swift-foundation/pull/1287. It's not always possible to use an identity cast here, because in some cases (such as catalyst applications where `AttributedString`s interchangeably use both UIKit `UIColor` and AppKit `NSColor` attributes) we do rely on dynamic casting behavior. The dynamic cast should attempt an identity cast first so this shouldn't have a strong impact on the overall performance win since we still avoid the optional boxing in `__equalAttributes` and retain the performance wins from the runs view.
> Retrieving attributed string attribute values should not use identity casts

- Proposals/0011-concurrency-safe-notifications.md
This PR updates the Concurrency-Safe Notification Center proposal with requested enhancements from the initial review:
- `AsyncSequence`-style observation
- Automatic de-registration when `ObservationToken` goes out of scope
It also includes the following tweaks:
- `Message.Subject` can now be `Identifiable` where `Identifiable.ID == ObjectIdentifier` in addition to `AnyObject`
- `post()` function argument label changed from `with` to `subject` for clarity
> Update concurrency-safe notifications proposal (v4)

- Sources/FoundationEssentials/Data/Data+Reading.swift
Musl's definition of `S_IFMT` gets imported by the Swift importer, which means Swift can see `S_IFMT` as a `CInt` and also `S_IFMT` from the Swift overlay as a `mode_t`.  The upshot is that attempting to convert it to `mode_t` produces an ambiguity error, as Swift doesn't know which definition to use.
> [Data] Fix build issue with Static SDK for Linux.

- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationEssentials/URL/URL_Bridge.swift
Some C APIs take in a `const void *` that is expected to be a `CFURLRef *` in certain cases. When a Swift API is generated for these functions, they instead take an `UnsafeRawPointer`.
Code passing an implicit raw pointer to a `struct URL` using `&var` notation can cause issues if the C function assumes the address of a `URL` points to a `NSURL *` or `CFURLRef`. This used to work because an `NSURL` was the first member of `struct URL`, but now that memory location contains the `_SwiftURL` class.
This PR allows us to restore the old behavior in very rare cases on Darwin where it's needed for compatibility by making `_BridgedURL` an `NSObject` and forwarding the ObjC messages it receives to the wrapped `NSURL`.
> Forward ObjC messages to _BridgedURL in rare compatibility cases

- Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
This PR attempts to fix #1283, by adjisting `Calendar.DatesByRecurring.Iterator` to maintain nanosecond precision on the dates it produces, if the original start date had a non-zero nanosecond component.
This brings the behaviour of the `Calendar.RecurrenceRule` API in line with how it was defined and described in [the proposal](https://github.com/swiftlang/swift-foundation/blob/main/Proposals/0009-calendar-recurrence-rule.md).
> fix `Calendar.RecurrenceRule`

- Proposals/0011-concurrency-safe-notifications.md
Minor update to improve readability of code indentation and generic parameter spelling.
> Update code formatting on SF-0011 with more readable indentation and generic parameters

- Proposals/0026-preferredLocales.md
Proposal for introducing `Locale.preferredLocales`.
> Locale.preferredLocales

- Sources/FoundationEssentials/AttributedString/AttributeContainer.swift
- Sources/FoundationEssentials/AttributedString/AttributeScope.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+IndexTracking.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+IndexValidity.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+UTF16View.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+UTF8View.swift
- Sources/FoundationEssentials/AttributedString/DiscontiguousAttributedSubstring.swift
This fixes up / adds documentation for my recent `AttributedString` API additions
> Fixup documentation for new AttributedString APIs

- Sources/FoundationEssentials/AttributedString/AttributedStringAttributeStorage.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringCodable.swift
- Sources/FoundationEssentials/AttributedString/Conversion.swift
`AttributedString` is `Sendable`, and it requires that all of its attribute values are `Sendable`. However, prior to this decision, we shipped attributes in the Apple SDKs that have non-`Sendable` values. We could not add an `AttributedStringKey.Value : Sendable` constraint because that constraint would cause downstream projects to fail to build when built with concurrency errors enabled, so instead every public `AttributedString` entry point has a `where Key.Value : Sendable` constraint to prevent reading/writing attributes values that are non-`Sendable`.
Unfortunately, there are a few situations where we cannot put this constraint because clients provide an attribute scope rather than an individual attribute key: attribute encoding/decoding and `NSAttributedString` conversion. In these …
> Resolve AttributedString attribute storage Sendable warnings

- Sources/FoundationEssentials/Locale/Locale+Language.swift
- Sources/FoundationInternationalization/Locale/Locale+Components_ICU.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
Here are some examples:
```swift
print(Locale(languageCode: "", script: "", languageRegion: "").identifier) // "-_"
let languageComponents = Locale.Language.Components(language: .init(identifier:""))
print(Locale(languageComponents: languageComponents).identifier) // "-Latn"
```
Fix this by handling empty identifiers passed in at initialization time correctly.
resolves 132353443
> Initiating a Locale/Language with empty language code/script/region results in an unreasonable locale.

- Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
This PR is a follow up to #1284: we missed the fact that `remainder(dividingBy:)` can produce negative values if the input's fractional part is greater than 0.5. (eg: `1.9.remainder(dividingBy: 1)` is -0.1).
Since the dates produced by `Calendar.DatesByRecurring.Iterator` all have their nanosecond component set to 0 (rather than being rounded to the nearest whole number), we need to use `truncatingRemainder(dividingBy:)` instead.
I also changed it to operate on `timeIntervalSinceReferenceDate` instead of `timeIntervalSince1970`, since that saves us on having to perform the `timeIntervalSince1970` computation every time.
> fix recurrence nanosecond handling for nanosecond values > 0.5

- CMakeLists.txt
- Package.swift
- README.md
- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationEssentials/Data/Data.swift
- Tests/FoundationEssentialsTests/DataTests.swift
Add the properties `span`, `mutableSpan`, `bytes` and `mutableBytes` to `Data`, as proposed in [SE-0456](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0456-stdlib-span-properties.md) and [SE-0467](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0467-MutableSpan.md).
Addresses rdar://137711067
> [SE-0456, -0467] Data+Span+MutableSpan

- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTestSupport.swift
I suspect this overload was added to our test files to support the tests before `AttributedStringProtocol.range(of:)` was ported to swift-foundation. But today, the `range(of:)` function exists in swift-foundation so we should remove this extra one from our tests to make sure we're testing the real function rather than the one overloaded by the tests.
> Remove extra AttributedStringProtocol.range(of:) overload

- Sources/FoundationEssentials/Data/Data.swift
Make `Data.bytes` a disfavored overload, to resolve issues when a using project defines a property of that name, while also importing FoundationEssentials.
> Temporarily make Data.bytes a disfavored overload

- Benchmarks/Benchmarks/Internationalization/BenchmarkLocale.swift
- Sources/FoundationEssentials/Locale/Locale+Components.swift
- Sources/FoundationEssentials/Locale/Locale_Cache.swift
- Sources/FoundationInternationalization/Locale/Locale+Components_ICU.swift
Previously we maintain a cache `private var cachedFixedComponentsLocales: [Locale.Components : any _LocaleProtocol]`, and every call to `Locale(components: Locale.Components)` reads a
nd writes to the cache. This results in a cache with non trivial size of keys.
Optimize this by replacing the key with a String instead of the full `Locale.Components` instance.
Using this as the baseline:
```swift
for identifier in Locale.availableIdentifiers {
let locale = Locale(identifier: identifier)
}
```
With the following as the testing code:
```swift
for identifier in Locale.availableIdentifiers {
let components = Locale.Components(identifier: identifier)
let locale = Locale(components: components)
let components2 = Locale.Components(locale: locale)
let locale2 = Locale(components: components2) // …
```
> Reduce size of `cachedFixedComponentsLocales`

- Tests/FoundationEssentialsTests/AttributedString/AttributedStringCOWTests.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringConstrainingBehaviorTests.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringDiscontiguousTests.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringIndexValidityTests.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
This adopts swift-testing for all of the `AttributedString` test suites. This paves the way for adding new capabilities to our `AttributedString` tests, such as adding exit tests to support validating all of our preconditions related to index validation (I'll post a followup PR that adds these new tests as I've noticed that when adding the tests, we have quite a few behavioral bugs that we should fix when adding these tests.
> Adopt swift-testing for AttributedString tests

- Proposals/NNNN-UTCClock.md
This adds a new API defining an additional clock primitive that uses Date as an Instant and additionally adds routines for looking up historical leap seconds for high precision calculations that involve leap seconds.
> Add a proposal for the definition of a UTCClock

- .github/workflows/pull_request.yml
It turns out that swiftlang's GitHub actions macOS CI doesn't use a nightly snapshot like the linux/windows testing, but instead uses the compiler from the Xcode installed on the device which currently only contains a 6.1 toolchain (which isn't new enough to build swift-foundation). This turns macOS GitHub action CI back off for this repo until we have an action that will use a new enough toolchain.
> Disable macOS GitHub Actions CI

- Package.swift
Now that the underlying issue in swift-testing has been resolved via https://github.com/swiftlang/swift-testing/pull/1145, let's try re-enabling this again
> Reenable exit tests on Ubuntu 20.04

- Tests/FoundationEssentialsTests/FileManager/FilePlayground.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
- Tests/FoundationEssentialsTests/ProcessInfoTests.swift
- Tests/FoundationEssentialsTests/StringTests.swift
Applies more patches from https://github.com/swiftlang/swift-foundation/pull/908 to bring a handful more FoundationEssentials test suites to swift-testing (adjusting the patches to account for newly added and modified tests)
> Convert String/Predicate/ProcessInfo/RecurrenceRule tests to swift-testing

- Package.swift
- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationEssentials/Data/Data.swift
- Tests/FoundationEssentialsTests/DataTests.swift
Remove conditional compilation statements put in place to work around a mismatch in the compiler version used by the Windows CI.
> [Windows] Clean up workarounds and enable `Span`

- .github/workflows/pull_request.yml
- CMakeLists.txt
- Sources/FoundationMacros/CMakeLists.txt
Enables a CI job for this repo to build the project via CMake on Linux to validate changes do not break the CMake build
> Enable CI job to build via CMake

- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
- Tests/FoundationInternationalizationTests/GegorianCalendarInternationalizationTests.swift
This converts the last of FoundationEssentials tests to swift-testing (the Gregorian calendar tests). Aside from converting to swift-testing, the only modification is that the final test now explicitly specifies the GMT timezone to avoid relying on the default timezone which other tests may change in parallel
> Convert Gregorian Calendar tests to swift-testing

- Proposals/0022-writing-direction-attribute.md
Update the link for Proposals `0022-writing-direction-attribute.md` . Currently, it displays `404 not found` error.
> Update the link for Proposals 0022-writing-direction-attribute.md

- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
- Tests/FoundationEssentialsTests/PropertyListEncoderTests.swift
Continued cherry-picks (with edits) of the initial swift-testing adoption for all of our encoder/decoder-related tests
In particular, this change (in addition to adopting swift-testing):
- Enables the exit tests previously if-def'ed out in these files (they now pass)
- Slightly refactors some expectation handling (using `#expect(throws:)` instead of `do`/`catch` with `Issue.record` for example) for older tests written before these types of expectations existed
- Removes trivial uses of `try!`/`as!` to help trigger expectation failures instead of crashes when unit tests fail
- Removes accidental uses of Foundation APIs not present in FoundationEssentials (like `replacingOccurrences(of:with:)` and `range(of:)`)
> Convert JSON/PropertyList tests to swift-testing

- Sources/FoundationInternationalization/Locale/Locale+Components_ICU.swift
- Tests/FoundationInternationalizationTests/LocaleRegionTests.swift
Proposal: https://github.com/swiftlang/swift-foundation/pull/1247/files
> Implement Locale.Region category filtering methods

- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
This applies a workaround to avoid https://github.com/swiftlang/swift/issues/82458
> Avoid passing (U)Int128 as test args

- Sources/FoundationEssentials/URL/URL_Swift.swift
- Tests/FoundationEssentialsTests/URLTests.swift
If we aren't in the special `CFURL` case where we need the original absolute string, we should always leave the base components encoded. This ensures we receive properly encoded absolute strings that correctly treat `?` and `#` as encoded path characters if those were previously inputted to the `URL(filePath:)` initializer.
Resolves https://github.com/swiftlang/swift-foundation/issues/1367
> URL.absoluteString should always use encoded base components

- Proposals/0011-concurrency-safe-notifications.md
This PR updates the Concurrency-Safe Notifications proposal to include changes requested during the second review.
> Remove Identifiable overloads and base Message protocol from NotificationCenter API proposal

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
While the `utimensat` has the ability to set nanosecond-precision dates on files (when supported by the file system), unfortunately the current call site of it loses precision for some input dates (represented as `Double`s). Unfortunately I haven't found a good way to convert the `Double` date representation to the second and nanosecond components without losing precision, and this precision causes issues with some clients expecting dates to roundtrip with full fidelity (even though values like `Date.now` may only support 1000ns-level precision, the imprecision when calculating nanosecond values can cause round tripping a date to return a different value than the one set).
Resolves rdar://153731450
> Revert "Adopt utimensat for setting file modification dates (#1324)"

- Sources/FoundationEssentials/URL/URL_Swift.swift
`URL.compatibility4` is no longer needed and we can just use `URL.compatibility1` for the `url.deletingPathComponent().standardized` compatibility path instead.
> Consolidate URL compatibility checks

- Sources/FoundationEssentials/URL/URL.swift
> Swift URL and URLResourceValues have no method for changing tags on a file

- Sources/FoundationMacros/BundleMacro.swift
- Tests/FoundationMacrosTests/BundleMacroTests.swift
Updating the `#bundle` macro to check whether `SWIFT_BUNDLE_LOOKUP_HELPER_AVAILABLE` is set. If that is the case, the build system built a mergable library and emitted a class called `__BundleLookupHelper`. 
The linker has a code path that makes `Bundle(forClass: )` work for merged libraries, whereas the DSO-handle is the same for all merged targets.
The build system counterpart has been merged here: https://github.com/swiftlang/swift-build/pull/599
> Use __BundleLookupHelper.self when building mergable library

- Tests/FoundationInternationalizationTests/CalendarRecurrenceRuleTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
- Tests/FoundationInternationalizationTests/CurrentInternationalizationPreferencesActor.swift
- Tests/FoundationInternationalizationTests/DateComponentsTests.swift
- Tests/FoundationInternationalizationTests/DateTests+Locale.swift
- Tests/FoundationInternationalizationTests/Formatting/ByteCountFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateIntervalFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateRelativeFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DiscreteFormatStyleTestUtilities.swift
- Tests/FoundationInternationalizationTests/Formatting/DurationTimeFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DurationUnitsFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
- Tests/FoundationInternationalizationTests/PredicateInternationalizationTests.swift
- Tests/FoundationInternationalizationTests/SortDescriptorConversionTests.swift
- Tests/FoundationInternationalizationTests/SortDescriptorTests.swift
- Tests/FoundationInternationalizationTests/StringSortComparatorTests.swift
This moves most of the remaining test cases to swift-testing (with a few still remaining that I'm working on)
> Continue to move FoundationInternationalization tests to swift-testing

- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationInternationalization/CMakeLists.txt
When building statically, ensure that we prefix the Swift libraries with the correct prefix to permit static linking of the libraries.
> build: adjust the autolink library for Windows

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ObjC.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
There is a bug in ICU that returns the wrong value for min/max range. Workaround that here.
Also fix the same issue in Gregorian calendar, where the returned value isn't sensible.
153548677
> Work towards leap month bug fixes

- Proposals/0024-CurrentBundle.md
Update the link for Proposals `0024-CurrentBundle.md` . Currently, it displays `404 not found` error.
> Update the link for Proposals 0024-CurrentBundle.md

- Proposals/0017-expanded-calendar-support.md
renamed isAdhikaDay to isRepeatedDay
added DateComponents.swift section
> update expanded calendar support proposal

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/StringTests.swift
Minor fix for `String.pathExtension` found when comparing the old `NSString` behavior. `String.pathExtension` returns "" for path extensions appended to "." and ".." file names. This behavior is in part to prevent `.deletingPathExtension()` from returning a path referencing the current or parent directory.
However, `String.pathExtension` currently returns "" for all file names that start with "..", so some valid file paths like "..name.txt" aren't receiving the correct behavior.
This PR makes it so we only disallow extensions that would leave "." and ".." file names when removed. I also renamed a variable to make it more clear we're working with the `UTF8View`.
> String.pathExtension should allow "..name" file names but not ".."

- Package.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Sources/FoundationInternationalization/CMakeLists.txt
- Sources/FoundationInternationalization/Formatting/Number/ICUNumberFormatter.swift
- Sources/FoundationInternationalization/ICU/ICU+CaseMap.swift
- Sources/FoundationInternationalization/ICU/ICU+FieldPositer.swift
- Sources/FoundationInternationalization/ICU/ICU+Foundation.swift
- Sources/FoundationInternationalization/ICU/ICU+StringConverter.swift
- Sources/FoundationInternationalization/Locale/Locale+Components_ICU.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
When enabling symbol renaming in ICU, we import the functions as an alias. This causes the implicit nullability translation with C to disappear. Make these conversions explicit so that we can enable symbol renaming on non-Darwin platforms.
> FoundationEssentials,FoundationInternationalization: adjust for aliasing

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Enumerate.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Calendar/DateComponents.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ObjC.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
- Tests/FoundationInternationalizationTests/DateComponentsTests.swift
adding support for "repeated day" (a.k.a. "adhika tithi" and "leap day") for use with Hindu lunisolar calendars
> support for repeating days in Hindu lunisolar calendars

- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationInternationalization/CMakeLists.txt
This commit was accidentally pulled from main to 6.2. We chose not to merge the similar swift-corelibs-foundation change back to 6.2 because this change depends on a swift repo change. Unfortunately, our release/6.2 branch CI did not catch that on this repo. This reverts the commit from the release/6.2 branch leaving it on the main branch
> [6.2] Revert "build: adjust the auto link library for Windows (#1312)"

- Sources/FoundationEssentials/AttributedString/AttributedString+Runs.swift
This fixes up a few places where AttributedString previously used 10000 availability instead of macOS 26-aligned availability (due to limitations of availability macros). This fixes those up to be consistent.
> Fix-up newer AttributedString availability/deprecation annotations

- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
This test and other tests testing the dot syntax assume that the left hand side of the comparison is using the same locale as the right side, in which case is `Locale.autoupdatingCurrent`. This further assumes that the state of the host machine remains unchanged throughout the tests.
Fix this by specifying the locale of the left and right side so they don't depend on the current locale settings.
Addresses 154994643
> formattedAttributedLeadingDotSyntax() test failed

- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateIntervalFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
Many tests for the dot syntax assume that the left hand side of the comparison is using the same locale as the right side, in which case is `Locale.autoupdatingCurrent`. Previously we put them inside `usingCurrentInternationalizationPreferences` to ensure that the current locale isn't mutated concurrently while the tests are running. That works but we can also set the locale of both the left and right side to a specific locale so they don't depend on the current status.
Addresses 155437764
> Limit the use of concurrent scope in unit tests

- Tests/FoundationInternationalizationTests/Formatting/NumberParseStrategyTests.swift
Updates this unit test to avoid relying on the current locale so that it won't fail if the locale changes to non-en_US in the middle of the test
> Prevent decimal_withFormat_localeDependent from relying on the current locale

- Sources/FoundationEssentials/JSON/JSON5Scanner.swift
- Sources/FoundationEssentials/JSON/JSONScanner.swift
- Sources/FoundationEssentials/PropertyList/PlistDecoder.swift
- Sources/FoundationEssentials/PropertyList/XMLPlistScanner.swift
- Sources/_FoundationCShims/include/string_shims.h
- Sources/_FoundationCShims/string_shims.c
When updating the JSON encoder tests to swift-testing, we noticed that on Windows the test that calls `setlocale` (which now runs in parallel to other tests) was interfering with other JSON tests causing rare crashes. This updates our string shims to explicitly use the c locale rather than relying on a `NULL` value (which on Windows used the global current locale)
> Update stringshims to always use clocale

- Sources/FoundationEssentials/Data/Data+Base64.swift
- Tests/FoundationEssentialsTests/DataTests.swift
We have an issue in `encodeComputeCapacity`. If we add lineBreaks, we assumed to add line breaks for lines that ended at the max capacity.
- `encodeComputeCapacity` checks if the last line uses the full length and removes unnecessary seperatorBytes if needed
rdar://155204772
> Fix Data Base64 length encoding bug

- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
This test would fail if the cache is cleared while running the test. It could happen if the number of objects exceeds the internal limit.
For some reason we have not seen test failures when building for FOUNDATION_FRAMEWORK, so still leave it enabled there.
We should come back to re-write the test to be more reliable for all platforms regardless.
> Disable `nsICUNumberFormatterCache` test

- Tests/FoundationInternationalizationTests/Formatting/DateRelativeFormatStyleTests.swift
`Date.RelativeFormatStyle` uses the current locale and calendar (which uses the default timezone) by default. There are a few unit tests that accidentally used one of these current values, or intentionally used them without guarding via `usingCurrentInternationalizationPreferences`. This updates `dateRelativeFormatConvenience` to be guarded with `usingCurrentInternationalizationPreferences` and explicitly specifies a locale/calendar/timezone in a few other missing places throughout the tests
Resolves rdar://155753882
> Update current preference-using Date.RelativeFormatStyle tests

- Sources/FoundationEssentials/Platform.swift
`CommandLine` is not available on platforms with no file system. Return `nil` in these cases
Resolves: rdar://156436329
> Fix Platform.getFullExecutablePath for platforms with no file system

- Proposals/0029-attributedstring-sendable-metatype.md
- Proposals/NNNN-attributedstring-sendable-metatype.md
Adds a proposal to conform `AttributedStringKey` and `AttributeScope` to `SendableMetatype`
> [Proposal] AttributedString & SendableMetatype

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
India only has Sunday as their weekend; the other places (GB, US, etc) have two days. Update `Calendar.nextWeekend(startingAfter:direction:)` to handle this case.
153114732
> Handle 1-day weekend properly

- Package.swift
One small improvement to package manifest:
* We follow the pattern from `swift-corelibs-foundation`[^1] to compute the location of dependencies:
* `SWIFTCI_USE_LOCAL_DEPS=1` moves us up one directory when looking for dependencies.
* Missing or empty `SWIFTCI_USE_LOCAL_DEPS` pulls dependencies from GitHub.
This also keeps us consistent with how we compute a local path for Benchmarks.[^2]
Tested locally from my machine:
```shell
$ cd ~/Developer/swift-foundation
$ swift build
...
Build complete!
$ SWIFTCI_USE_LOCAL_DEPS=~/Developer swift build
...
Build complete!
$ SWIFTCI_USE_LOCAL_DEPS=~ swift build
...
error: the package at '/Users/rick/swift-collections' cannot be accessed (Error Domain=NSCocoaErrorDomain Code=260 "The folder “swift-collections” doesn’t exist." …
```
> update package deps for custom project root

- Package.swift
Now that the toolchains have been updated, this enables exit tests on Windows
> Enable exit tests on Windows

- Sources/FoundationEssentials/Platform.swift
The Swift driver uses the location of the driver to search for other binaries including the swift-frontend, legacy driver, etc... Dropping the filepath means that we lose this information and search from the current working directory instead of where the driver exists, which then results in the driver failing.
This broke the FreeBSD job: `error: unknown or missing subcommand 'swiftc-legacy-driver'`
> Keep executable path

- Proposals/NNNN-random-uuid.md
- Sources/FoundationEssentials/UUID.swift
- Tests/FoundationEssentialsTests/UUIDTests.swift
This PR adds a proposal to generate `UUID's` using `RandomNumberGenerator`s
> Proposal to generate `UUID`s using `RandomNumberGenerator`s

- .github/workflows/pull_request.yml
Now that `swiftlang/github-workflows` supports building with the Swift Wasm SDK in https://github.com/swiftlang/github-workflows/pull/142, we can enable the job in swift-foundation to prevent WASI build regressions.
> [CI] Enable Wasm SDK build in swift-foundation

- Sources/FoundationEssentials/Data/Data.swift
It is available from visionOS 1.0, as fixed in
https://github.com/swiftlang/swift/pull/82850
This requires swift-DEVELOPMENT-SNAPSHOT-2025-07-17-a or swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-09-a.
Addresses https://github.com/swiftlang/swift-foundation/issues/1419
> Fix visionOS availability of `Span`

- Tests/FoundationMacrosTests/MacroTestUtilities.swift
- Tests/FoundationMacrosTests/PredicateMacroUsageTests.swift
We no longer have any scenarios where we need to build the macro for a host older than macOS 14 so we can cleanup some of the availability checks in the macros target to assume a macOS 14 deployment target
> Cleanup FoundationMacros availability checks

- Sources/FoundationEssentials/Predicate/KeyPath+Inspection.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
As a followup to https://github.com/swiftlang/swift-foundation/pull/1475, this adds exit tests to validate situations when we _should_ be preventing usage of a particular keypath (specifically, when a keypath is multiple components or when it represents optional chaining or subscripts).
Adding these tests uncovered that the default value of `restrictArguments` in `_validatedForPredicateUsage` was incorrect and that we weren't actually validating that subscripts with arguments can't be used. In addition to adding these tests, this fixes the default value of this argument so that in cases where we don't expect arguments we enforce that they cannot be used.
> Add predicate keypath assertion exit tests

- Sources/FoundationEssentials/Decimal/Decimal+Compatibility.swift
Resolves: https://github.com/swiftlang/swift-foundation/issues/1455
> Expose Decimal.pow() as a public API on FoundationEssentials

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Locale/Locale.swift
- Sources/FoundationEssentials/Locale/Locale_Preferences.swift
- Sources/FoundationEssentials/TimeZone/TimeZone.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
- Tests/FoundationInternationalizationTests/CalendarRecurrenceRuleTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
- Tests/FoundationInternationalizationTests/TimeZoneTests.swift
There's been a handful of changes over the years in this area, but the situation we have today is that `TimeZone`, `Calendar`, and `Locale` all have different behaviors for how they encode `.current`. All 3 mostly agree that `.autoupdatingCurrent` is always encoded as as sentinel value becoming the `.autoupdatingCurrent` at decode time, and that fixed values are decoded simply as fixed values (Calendar doesn't do the latter sometimes). However:
- `TimeZone` always encodes `.current` as a fixed value. When decoded it is the same time zone that was encoded regardless of `.current` at decode time
- `Locale` always encodes `.current` as a sentinel value. When decoded, it takes the value of whatever `.current` is at decode time regardless of the locale that was encoded
- `Calendar` encodes a …
> TimeZone, Calendar, and Locale disagree on how `.current` is serialized

- Proposals/NNNN-String-Encoding-Names.md
This proposal allows `String.Encoding` to be converted to and from various names.
For example:
```swift
print(String.Encoding.utf8.ianaName!) // Prints "UTF-8"
print(String.Encoding(ianaName: "ISO_646.irv:1991") == .ascii) // Prints "true"
```
-----
Implementation: https://github.com/swiftlang/swift-foundation/pull/1286
> [Proposal] Add "String Encoding Names" proposal.

- Sources/FoundationInternationalization/Locale/Locale+Components_ICU.swift
- Tests/FoundationInternationalizationTests/LocaleRegionTests.swift
With @abi we can make an ABI compatible change so existing clients can continue to work on user's 6.2 devices even after they adopt the correct name on 6.2.1 and above.
But only use @abi for FOUNDATION_FRAMEWORK since ABI compatibility isn't a concern in other scenarios.
> Locale.Region subregion API is misspelled

- Sources/FoundationEssentials/LockedState.swift
`wasm32-unknown-wasip1-threads` target provides access to basic pthread APIs, so we should use it in LockedState
> [wasm] Use pthread mutex for wasm32-unknown-wasip1-threads target

- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Prevent a nil force unwrap from crashing this test while we investigate the cause.
> Prevent nil force unwrap in JSONEncoder test

- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateIntervalFormatStyleTests.swift
We encountered a test failure that surfaced an issue with the `leadingDotSyntax` tests: some of them use the current internationalization preferences without being synchronized. This corrects the two tests that contain issues (other `leadingDotSyntax` tests don't have this issue) by either synchronizing usage of the preferences, or avoiding a reliance on the preferences.
Resolves rdar://161031455
> Fix leadingDotSyntax test reliance on current internationalization preferences

- Sources/FoundationEssentials/Data/Data.swift
- Tests/FoundationEssentialsTests/DataTests.swift
Unfortunately the `mutableSpan` and `mutableBytes` accessors on `Data` do not currently perform a uniqueness check to trigger CoW. This means that you can mutate a `Data` via its mutable span even if it references a shared storage. This updates the implementation to trigger CoW for the shared storage representations when accessing the mutable spans as well as a unit test to ensure a copy occurs when not uniquely referenced (and that no copy occurs if the storage is uniquely referenced).
> Data.mutableSpan and Data.mutableBytes do not perform uniqueness check
