swiftlang/swift-foundation

- README.md
This PR fixes Swift 5.9 docker image and toolchain links.
Personally, I spent a time trying to find the tag name for docker image.
> Fix Swift 5.9 docker image and toolchain links in README.

- Sources/FoundationEssentials/String/StringBlocks.swift
The leading space for this code block didn't match that of other code blocks at the same indentation level.
> Fix formatting

- Sources/FoundationEssentials/AttributedString/AttributeScope.swift
- Sources/FoundationEssentials/AttributedString/AttributedString.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringAttribute.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringCodable.swift
- Sources/FoundationEssentials/AttributedString/Conversion.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
Currently, when converting/serializing an `AttributedString` we walk the provided `AttributeScope` one time for every new attribute we encounter and we do not cache the information between conversions. However, walking an attribute scope is fairly slow (since it requires a conforms-to-protocol check on the type of each field in the scope) so this behavior has been demonstrated to be a performance bottleneck. This patch improves the behavior by:
- Eagerly walking a scope at the start of conversion rather than walking it after encountering each new attribute
- Cache the result of scope walking so that each scope is walked a maximum of one time
- Switch from `dlopen`/`dlsym` to `_typeByName` to avoid a dependency on framework paths and simplify scope loading code
> AttributeScope Cacheing and Performance Improvements

- Sources/FoundationEssentials/AttributedString/AttributedString+CharacterView.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Guts.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+Run.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+UnicodeScalarView.swift
- Sources/FoundationEssentials/AttributedString/AttributedString.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringProtocol.swift
- Sources/FoundationEssentials/AttributedString/AttributedSubstring.swift
- Sources/FoundationEssentials/AttributedString/Collection Stdlib Defaults.swift
- Sources/FoundationEssentials/AttributedString/Conversion.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringConstrainingBehaviorTests.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
This is effectively the same problem as https://github.com/apple/swift/pull/41417, but for `AttributedString` instead of `String`.
Consider the following code:
```swift
import Foundation
let a: AttributedString = "🇺🇸" // U+1F1FA U+1F1F8
let i = a.unicodeScalars.index(after: a.startIndex)
let b = a.characters[..<i]
```
The index `i` falls between character boundaries in the string, and this makes `b` an invalid collection:
```swift
print(b.count) 
// Fatal error: String index is out of bounds
```
The issue is that `AttributedString.CharacterView` shipped with the default `Slice` as its `SubSequence` type, and `Slice` does not expect to deal with unreachable indices.
This is an unintended consequence of SE-0180, which unified the index type for String views, without due consideration to …
> rdar://105027055: Improve AttributedString view slicing

- Sources/FoundationInternationalization/Calendar/Calendar.swift
Updates the documentation of the parameters and return types of the following two methods:
`public func dateIntervalOfWeekend(containing date: Date, start: inout Date, interval: inout TimeInterval) -> Bool`
and
`public func nextWeekend(startingAfter date: Date, start: inout Date, interval: inout TimeInterval, direction: SearchDirection = .forward) -> Bool`
The updated documentation is written with reference to the language used in `public func dateInterval(of component: Component, start: inout Date, interval: inout TimeInterval, for date: Date) -> Bool`.
> Refine the documentation of Calendar's methods.

- Sources/FoundationEssentials/LockedState.swift
- Sources/FoundationInternationalization/LockedState.swift
- Tests/FoundationEssentialsTests/LockedStateTests.swift
- Tests/FoundationInternationalizationTests/LockedStateTests.swift
Currently, if the `body` closure passed to `withLockExtendingLifespanOfState(_:)` throws an error, the lock is not released. This PR fixes that.
My fix was to switch the implementation of `withLockExtendingLifespanOfState(_:)` to delegate to `withLockUnchecked(_:)`, which does properly unlock if its body throws an error.
Added unit tests to verify this change, and backfilled tests that verify the lifespan-extending behavior of this method.
> LockedState: Fix lock not being released when body throws

- Sources/FoundationEssentials/Date.swift
- Tests/FoundationEssentialsTests/DateTests.swift
Calling Date.description might result in undefined behaviour
The buffer used was too small in some cases.
Fixed by allocating (more than) enough space on the stack.
> Fixes issue #78: Calling Date.description might result in undefined behaviour

- Sources/FoundationEssentials/JSON/JSON5Scanner.swift
- Sources/FoundationEssentials/JSON/JSONScanner.swift
Using the `consuming` parameter modifier for copyable (aka normal) types is deferred from swift 5.9. This uses the older `__owned` modifier instead, and consumes the parameter into a `var` as the first statement. This should generate the same code. This fixes a compilation error in `swift-foundation`'s Linux CI.
> Use `__owned` parameter modifier

- Sources/FoundationEssentials/Data/Data.swift
- Sources/FoundationEssentials/String/String+Essentials.swift
This PR updates memory binding call sites for correctness in the wake of SE-0333, which made withMemoryRebound available for raw memory buffers.
Addresses https://github.com/apple/swift-foundation/issues/98 (rdar://108960577)
> Fix Memory Binding Issues

- Sources/FoundationEssentials/JSON/BufferView.swift
This reverts a change in the internal representation of `BufferView` which potentially has significant performance consequences. We might want to make this change, but we need to carefully evaluate its performance consequences first.
This reverts commit 6900c61344048242878ccbb9b79b0a47b2b75e80.
> Revert "Move count among the Collection conformance in BufferView"

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Sources/TestSupport/TestSupport.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
This adds support for `JSONEncoder` and `JSONDecoder` to directly encode/decode a `CodableWithConfiguration` type by providing a configuration directly or by providing an appropriate configuration-providing type
> Top Level Coder Support for `CodableWithConfiguration`

- Sources/FoundationEssentials/UUID_Wrappers.swift
We've found that some apps out there are depending on the exact name `__NSConcreteUUID`. Rename the new `_NSSwiftUUID` to `__NSConcreteUUID` to preserve compatibility.
rdar://108154678
> Change _NSSwiftUUID to __NSConcreteUUID

- Tests/FoundationEssentialsTests/BufferViewTests.swift
This test contained randomness which led to a 0.1% probability of spurious failure. I don’t know why I thought it was a good idea. At least 1 CI run errored because of it.
> Remove randomness from a test

- Sources/FoundationInternals/LockedState.swift
The method description was wrong: the `State` parameter must outlive the locked scope, not just the call to the closure. Thanks to @phausler for the pointer.
Addresses rdar://109056170
> Correct implementation of `withLockExtendingLifetimeOfState`

- Package.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Guts.swift
- Sources/FoundationEssentials/AttributedString/AttributedString.swift
- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Sources/FoundationEssentials/JSON/JSONScanner.swift
- Sources/FoundationEssentials/LockedState.swift
- Sources/FoundationEssentials/Predicate/Expression.swift
- Sources/FoundationEssentials/String/RegexPatternCache.swift
- Sources/FoundationInternationalization/Calendar/Calendar_Cache.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
- Sources/FoundationInternationalization/Formatting/FormatterCache.swift
- Sources/FoundationInternationalization/ICU/ICU+CaseMap.swift
- Sources/FoundationInternationalization/Locale/Locale_Cache.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Sources/FoundationInternationalization/LockedState.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_Cache.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_ICU.swift
- Tests/FoundationEssentialsTests/LockedStateTests.swift
- Tests/FoundationInternationalizationTests/LockedStateTests.swift
- Revert "Create FoundationInternals, an internal module to host shared files used by FoundationInternationalization and FoundationEssentials (#101)"
- Reapply fb718cd3fb9f058a5fd6d736cec9c2b99d6f7dc6 fix to the other restored LockedState
> Revert "Create FoundationInternals, an internal module to host shared files used by FoundationInternationalization and FoundationEssentials (#101)"

- README.md
The `consume` keyword requires `-enable-experimental-move-only` frontend flag, which was only enabled in recent snapshots. Specify a snapshot version that we know works in README.
> Update README for toolchain requirement

- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
Removes some stray print statements in our tests and correctly checks the current system language
> Clean up print statements in NumberFormatStyleTests

- Tests/FoundationEssentialsTests/DateTests.swift
We use ICU for date calculation for Foundation Framework, and `gmtime` otherwise. It appears that the result starts to diverge at some time in Gregorian year 1582, which happens to be the year when Gregorian calendar went into effect. That in turn results in disparate representations of `Date` before year 1582.
It's not clear how `tm` and `strtime` handles before-Gregorian dates since it's entirely in the implementation details. This PR simply update test expectations accordingly.
> Update `Date.description` tests for Foundation Framework

- Package.swift
[`swift-foundation-icu 0.0.2`](https://github.com/apple/swift-foundation-icu/releases/tag/0.0.2) contains important fixes for building on iOS. Adopting `swift-foundation-icu 0.0.2` allows  `FoundationPreview` to be built and tested on iOS simulators.
> Upgrade swift-foundation-icu to 0.0.2

- Sources/_CShims/include/string_shims.h
- Sources/_CShims/string_shims.c
Add a Windows path for the string functions that deal with locales. This is the first step towards supporting the Windows platform.
> _CShims: add Windows variant of the string functions

- Sources/FoundationEssentials/_ThreadLocal.swift
This removes `@_implementationOnly` from one of the `Darwin` imports since the rest of the package imports `Darwin` as non-implementation-only
> Remove @_implementationOnly import from Darwin

- Sources/FoundationInternationalization/Locale/Locale.swift
- Sources/FoundationInternationalization/Locale/Locale_Wrappers.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
Implement `Locale`'s `identifier(from:)` in Swift.
Perf test:
```swift
let c1 = ["kCFLocaleLanguageCodeKey" : "en"]
let c2 = ["kCFLocaleLanguageCodeKey" : "zh",
"kCFLocaleScriptCodeKey" : "Hans",
"kCFLocaleCountryCodeKey" : "TW"]
let c3 = ["kCFLocaleLanguageCodeKey" : "es",
"kCFLocaleScriptCodeKey" : "",
"kCFLocaleCountryCodeKey" : "409"]
for _ in 0..<100_000 {
let id1 = Locale.identifier(fromComponents: c1)
let id2 = Locale.identifier(fromComponents: c2)
let id3 = Locale.identifier(fromComponents: c3)
assert(id1.isEmpty == false)
assert(id2.isEmpty == false)
assert(id3.isEmpty == false)
}
```
And the results:
```
// Swift implementation
test_identifierFromComponents()	0.040965125 seconds
test_identifierFromComponents()	0.039983875 seconds
// Previous CF implementation, from Swift …
```
> Implement Locale's identifier from components in Swift

- Sources/FoundationEssentials/_ThreadLocal.swift
Windows prefers to use FLS (fibre local storage) for TLS (thread local storage).  The FLS key is of type `DWORD` rather than `UInt`.  Update the `typealias` for Windows.
> FoundationEssentials: correct `PlatformKey` for Windows

- Sources/FoundationEssentials/Data/Data.swift
- Sources/FoundationEssentials/Data/DataProtocol.swift
`unmap` is a non-portable function as it is not part of the C standard. The correct spelling for this on Windows is `UnmapViewOfFile` which expects that the data to be mapped by `MapViewOfFile`.  This cannot be used for freeing memory in general.
> FoundationEssentials: allow `Data` to build on Windows

- Sources/_FoundationInternals/LockedState.swift
Add support for using `SRWLOCK` to implement a mutex on Windows.
> _FoundationInternals: port `LockedState` to Windows

- Sources/FoundationEssentials/JSON/JSON5Scanner.swift
- Sources/FoundationEssentials/JSON/JSONScanner.swift
These calls to `String.reserveCapacity()` are wrong when the accumulated input is non-ASCII, resulting in requests for smaller capacities than is already being consumed. Changing them or removing them shows little to no affect on performance in benchmarks anyway. In the interest of simplicity, let's remove them.
> Remove String.reserveCapacity() calls with dubious value from JSONScanners

- Sources/FoundationEssentials/JSON/JSON5Scanner.swift
- Sources/FoundationEssentials/JSON/JSONScanner.swift
This is a second fix for the delay of the `consuming` parameter modifier for copyable types. The previous attempt, using `__owned`, resulted in a defensive retain of the parameter, which then caused an unnecessary copy. Using an `inout` parameter prevents this.
Addresses rdar://109425225
> Replace `__owned` with an `inout` parameter

- Sources/FoundationEssentials/Decimal+Stub.swift
Add the import for the Windows libc.  This enables to finally build the `FoundationEssentials` module.
> FoundationEssentials: make `Decimal` build on Windows

- Sources/FoundationEssentials/String/String+Encoding.swift
Previously we added a new type `String._Encoding` for FoundationPreview to mirror Foundation framework's `String.Encoding` to work around Clang importer's ambiguous lookup issue. It turns out that the new type isn't needed for this workaround. Adding a typealias itself is sufficient.
> Remove String._Encoding

- Sources/FoundationInternationalization/Formatting/Number/NumberFormatStyleConfiguration.swift
Add the missing conformance for `Codable` to Windows.  This fixes a large set of warnings when building the package.
> Foundationinternationalization: add `Codable` conformance

- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
Use `self.` to mark the capture of `self` within the closure which is identified by the compiler.
> FoundationInternationalization: capture with `self.` prefix

- Sources/FoundationInternationalization/Locale/Locale_Cache.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
We should use `en-001` (language identifier) / `en_001` (locale identifier) as a fallback instead of "just" English.
rdar://108958839
> Update the fallback locale from en to en-001

- Sources/FoundationInternationalization/Formatting/Date/DateFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
- Sources/FoundationInternationalization/Locale/Locale.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
If locale's preferences specifies a custom date format for the given date style, use what's given as-is instead of generating a date pattern from the date style. Realistically this only applies to `Locale.current` since that's the only instance that would have embedded preferences.
> Formatted functions ignore user's date preferences

- Sources/FoundationEssentials/JSON/JSON5Scanner.swift
- Sources/FoundationEssentials/JSON/JSONScanner.swift
`stringValue` and `_slowpath_stringValue` didn’t agree on who should retain the returned string, when using a Swift compiler from the 5.9 branch.
rdar://109537137
> Work around a miscompilation

- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
This test is currently failing on CI.  It is unclear if there is a miscompile currently.  Temporarily disable the test to not lose signal on other tests.
> tests: disable currently failing test

- Package.swift
This adds a conditional handling of `FoundationInternationalization` tests if the `RegexBuilder` module is available.  This currently is unavailable on Windows, which prevents building a complete set of targets.  Adjust the build to accommodate this configuration and automatically enable the tests when the module is available.
> build: add a workaround for Windows tests

- Sources/FoundationInternationalization/Formatting/ByteCountFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Number/ICULegacyNumberFormatter.swift
- Sources/FoundationInternationalization/Formatting/Number/NumberFormatStyleConfiguration.swift
- Sources/FoundationInternationalization/ICU/ICU+Enums.swift
- Tests/FoundationInternationalizationTests/Formatting/ByteCountFormatStyleTests.swift
Only a small number of languages prefer spelling out number in this context according to localization team. Chinese wasn't one of those, hence this bug. Fix it by hard-coding a list of language codes where we should format number 0 as a spellout number.
Also were using a rule-based number formatter to format number 0 into spellout "Zero", which defaults to an ordinal number. That default rule was incorrect. The number should be formatted as a cardinal number instead.
> Zero in "0 byte" displays like latn "O" in Chinese simplified.

- Sources/FoundationEssentials/String/BidirectionalCollection.swift
- Sources/FoundationEssentials/String/String+Essentials.swift
- Sources/FoundationInternationalization/Formatting/Number/FloatingPointParseStrategy.swift
- Sources/FoundationInternationalization/Formatting/Number/IntegerParseStrategy.swift
- Sources/FoundationInternationalization/Formatting/Number/NumberFormatStyleConfiguration.swift
- Sources/_FoundationInternals/String/BidirectionalCollection.swift
- Sources/_FoundationInternals/String/String+Internals.swift
- Tests/FoundationEssentialsTests/StringTests.swift
- Generalize trimming function to take a predicate block. Move this function to FoundationEssentials.
- Call `_trimmingWhitespaces()` instead of through CharacterSet.
> FoundationPreview: Stop relying on CharacterSet for trimming whitespace

- Sources/FoundationInternationalization/BinaryFloatingPoint.swift
- Sources/FoundationInternationalization/BinaryInteger.swift
- Sources/FoundationInternationalization/Calendar/Calendar.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Locale/Locale+Components.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_Cache.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_ICU.swift
Adjust the importing of the system libc library for Windows.  When possible, prefer to import the underlying C library interface through the `ucrt` (clang) module.  When needed, resort to use `CRT` which has an overlay which provides certain overloads for math functions.
> FoundationInternationalization: adjust the libc imports

- Sources/FoundationInternationalization/TimeZone/TimeZone_ICU.swift
Address an open item to implement proper file access for the timezone data on Windows.  Always prefer to use the 64-bit times and 64-bit file sizes.  This should ensure that we minimise the risk for wrapping.
> FoundationInternationalization: implement reading on Windows

- Tests/FoundationEssentialsTests/DateTests.swift
Rather than using `XCTAssertTrue` prefer to use the XCTest comparators to provide a better diagnostic in case of a test failure.
> Tests: spell out XCTest comparators (NFC)

- Tests/FoundationEssentialsTests/DateTests.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Windows does not provide the POSIX variant of `en_US`.  Prefer to use the standard `en_US` locale for the test on this platform.
> Tests: prefer `en_US` to `en_US_POSIX` on Windows

- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
The current locale returned by `setlocale` is being duplicated
explicitly by `strdup` in the code.  The contract for `strdup` states
that the memory allocated by `strdup` must be released by `free`.  We
were previously using `.deallocate` on the `UnsafeRawPointer`.  This is
not guaranteed to be backed as `free` as it makes certain guarantees
about pointer alignment which do not hold with `strdup`.
As a concrete example of a failure, Windows uses `_aligned_free` to
release the memory which assumes that the memory has been allocated by
`_aligned_malloc` which is what is used by
`UnsafeMutableRawPointer.allocate`.  This would thus fail with an
invalid `free`.
Take the opportunity to colocate the memory management with the
allocation by using a `defer` statement.  This is a small stylistic …
> Tests: correct memory management in `test_localeDecimalPolicyIndependence`

- Sources/FoundationEssentials/String/String+Comparison.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_Cache.swift
- Sources/_FoundationInternals/String/BidirectionalCollection.swift
- Tests/FoundationEssentialsTests/StringTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
We continue disentangling the package from system Foundation API in this PR
- Use stdlib's `replacing(:with:)` instead of NSString's `replacingOccurrences(of:with:)`
- Move internal implementation of `_range(of:anchored:backwards:)` to _FoundationInternals. Update callsites to use this instead of NSString's `range(of:)` implementation.
> Work towards: Stop calling into Foundation's implementation 

- Sources/FoundationInternationalization/TimeZone/TimeZone_Cache.swift
This adjusts the Windows paths to account for the handling of file paths and link resolutions.  There is no `readlink` function, particularly in the C library.  Instead, we need to open the file, and then query the I/O Object Manager to determine the final path.  This emulates the behaviour of `readlink` for Windows.
> FoundationInternationalization: improve Windows file path handling

- Sources/FoundationEssentials/Predicate/Predicate.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
This provides static `true` and `false` properties on `Predicate` so that shorthand syntax of `.true` and `.false` can be used in APIs that accept a predicate
Resolves rdar://109162593
> Provide `Predicate.true` and `Predicate.false`

- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
Add an explicit type signature for the closure as it was being inferred as `() -> WeekendRange` rather than `() -> WeekendRange?` which results in a failure to build as `nil` does not conform to `WeekendRange`.
> FoundationInternationalization: add explicit type signature

- Sources/FoundationEssentials/AttributedString/AttributeScope.swift
`_typeByName` is actually quite slow compared to just `dlsym` these days. Use that instead.
Resolves: rdar://109785007
> FoundationEssentials: Use dlsym instead of _typeByName in Attribute scope lookup

- Sources/FoundationEssentials/Predicate/Expression.swift
- Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift
- Sources/FoundationEssentials/Predicate/Predicate.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
This PR ports our `Predicate` -> `NSPredicate` conversion code to FoundationPreview behind `#if FOUNDATION_FRAMEWORK`, and exposes one of our utilities for that code for detecting common collection-based key paths as API.
Resolves rdar://108006317
> Expose `PredicateExpressions.KeyPath.CommonKeyPathKind` as API

- Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
When a `Predicate` captures a `Data` value, we should insert that into the converted `NSPredicate`
> (110353463) Support converting raw Data values in NSPredicate conversion

- Sources/FoundationEssentials/Date.swift
Implement querying the current absolute time on Windows which was previously marked as unimplemented.  Use the
`GetSystemTimePreciseAsFileTime` to query the system time which is in 100-ns intervals since January 1, 1601 (UTC).  This partially enables the `Date` functionality on Windows.
> FoundationEssentials: implement `getCurrentAbsoluteTime` on Windows

- Sources/FoundationEssentials/Date.swift
In the case that `_gmtime_s` fails, the return value is initialised to an invalid value that will fail when invoking `_strftime`.
> Date: protect against invalid use of `_gmtime_s`

- Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
This fixes a typo in `Predicate` to `NSPredicate` conversion that accidentally converted the != operator to ==
> Fix NSPredicate conversion for != operator

- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Skip the `test_JSONUnicodeEncodings` test on Windows similar to Linux as it exhibits the same issue with a stack overflow.
> Tests: extend test skipping to Windows

- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
`String(_utf16:count:)` returns an optional String. Guard it before using it.
> Guard an optional String before using it in String interpolation

- Sources/FoundationEssentials/Predicate/Expressions/Optional.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
This updates the API of `PredicateExpressions.ForcedUnwrap` to use `Inner` instead of `Wrapped` and `lhs:`. Since this is newer API that we don't expect anyone to be using yet, we can safely make this change without causing too much disruption
Resolves rdar://110119524
> Update API naming of PredicateExpressions.ForcedUnwrap

- Sources/FoundationEssentials/String/StringBlocks.swift
- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
- Sources/_FoundationInternals/String/BidirectionalCollection.swift
These started by converting `self` into a `String`. This lead to crashes when `self` happened to be a Substring, as the input range isn’t necessarily a valid index range in the resulting string in that case.
While I’m here, review related helper functions to improve performance and to avoid more correctness issues.
Resolves rdar://109907151&110477287
> Fix StringProtocol.lineRange(for:)/paragraphRange(for:)

- Sources/FoundationInternationalization/Formatting/Date/Date+IntervalFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/DateFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/DateParseStrategy.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
- Sources/FoundationInternationalization/ICU/ICUPatternGenerator.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/ICUPatternGeneratorTests.swift
Some locales prefer conversational day periods, ie. "12 at noon" to "12 pm". Currently clients need to use one of the `conversational` hour option to get this behavior, such as
```swift
let str = Date.now.formatted(.dateTime.hour(.conversationalDefaultDigits(amPM: .wide))
```
In some locales this is in fact the desired behavior, and should be the default. This PR adds a hook to swap "regular" hour with conversational one if we know the locale prefers it.
While we're here, clean up `ICUPatternGenerator`'s function interface and extra steps in `IntervalFormatStyle` that's now unnecessary.
rdar://110180766
> Defaults to conversational hour options if the locale prefers it

- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
We had been supporting `DateComponent.week` in Calendar's date calculation even though it's deprecated until recently. Let's keep doing that for the sake of compatibility.
Resolves rdar://110561999
> Restore support of deprecated `DateComponent.week` when calculating date

- Sources/FoundationInternationalization/Calendar/Calendar.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
- Sources/FoundationInternationalization/ICU/ICU+Enums.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
We should include the calendar identifier via the "ca" keyword when getting calendar symbols from ICU, such as "en_US@ca=hebrew". It was mistakenly dropped when we rewrote Calendar, so now we always return the symbols of the default calendar of the locale.
We can fix this by updating the existing implementation with the correct identifier, but we can also just use `ICUDateFormatter`, bypassing `CFDateFormatter` altogether. We chose the latter approach here.
Fixes rdar://110585721
> Implement getting calendar symbols

- Sources/FoundationInternationalization/Locale/Locale.swift
`CFLocaleCreateCanonicalLocaleIdentifierFromString` may return nil, so it crashes when we force cast it to `String`. We're already handling this properly in the internal function, so just call into that one.
Resolves rdar://110547526
> canonicalLocaleIdentifierFromString crashes with invalid input

- Sources/FoundationInternationalization/Calendar/Calendar.swift
Avoid mutating the underlying calendar when the incoming new value for Calendar's mutable properties is equal to the existing value.
Resolves rdar://109379510
> Don't mutate the underlying Calendar unless necessary

- Sources/FoundationInternationalization/Formatting/Number/ICUNumberFormatter.swift
- Sources/FoundationInternationalization/ICU/ICUPatternGenerator.swift
- Sources/FoundationInternationalization/Locale/Locale+Components.swift
- Sources/FoundationInternationalization/Locale/Locale.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
- Part 1: Clean up various usages of force-12-hour and force-24-hour
Consolidate `force24Hour` and `force12Hour` to `forceHourCycle`. Use this as the universal override option.
- Part 2: Introduce `identifierCapturingPreferences`
Add `Locale.identifierCapturingPreferences` to return a string identifier with preferences encoded in. This allows us to pass this identifier to ICU functions to request overrides rather than specifying options in individual API. This PR also adopts this identifier for `ICUNumberFormatter`.
Work towards resolving rdar://110211953
> Introduce Locale.identifierCapturingPreferences to capture preferences in a single identifier

- Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift
This limits which types of numbers we convert in `Predicate` to `NSPredicate` conversion to those actually supported by `NSNumber` rather than any arbitrary `Numeric` type
Resolves rdar://111351942
> Limit Predicate to NSPredicate conversion to applicable numeric types

- Sources/FoundationInternationalization/Formatting/Date/Date+IntervalFormatStyle.swift
- Tests/FoundationInternationalizationTests/Formatting/DateIntervalFormatStyleTests.swift
This add the missing `formatted` methods to `Range<Date>`.
https://developer.apple.com/documentation/swift/range/formatted()
https://developer.apple.com/documentation/swift/range/formatted(date:time:)
https://developer.apple.com/documentation/swift/range/formatted(_:)
> Foundationinternationalization: Implement date range formatted methods

- Sources/Foundation/Foundation.swift
- Sources/FoundationEssentials/AttributedString/String.Index+ABI.swift
- Sources/FoundationEssentials/BuiltInUnicodeScalarSet.swift
- Sources/FoundationEssentials/CocoaError.swift
- Sources/FoundationEssentials/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/ErrorCodes.swift
- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/Predicate/Expression.swift
- Sources/FoundationEssentials/String/String+Comparison.swift
- Sources/FoundationEssentials/String/StringBlocks.swift
- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
- Sources/FoundationEssentials/UUID_Wrappers.swift
- Sources/FoundationInternationalization/CocoaError+Stub.swift
- Sources/FoundationInternationalization/Date+ICU.swift
- Sources/FoundationInternationalization/Date+Locale.swift
- Sources/FoundationInternationalization/String/String+Locale.swift
- Sources/FoundationInternationalization/String/StringProtocol+Locale.swift
This PR adds the missing `@available` maker to `Swift+Comparisons.swift` and fixed all the incorrect license headers.
Addresses: rdar://108001698, rdar://108968799
> Addressed compiler warnings and updated the incorrect license headers

- Sources/FoundationEssentials/Predicate/Archiving/PredicateCodableConfiguration.swift
- Sources/FoundationEssentials/Predicate/Expressions/Optional.swift
- Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
Adds support for `nil` literals that are unconditionally `Sendable & Codable` in predicates even when the wrapped value type is not `Codable` or `Sendable`.
Resolves rdar://111180725
> Add support for non-Codable nil literals in Predicates

- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
Fixes a regression introduced when rewriting Calendar in Swift -- `CFCalendar` entry points expect this code to only use *one* of week of year or (deprecated) week.
Resolves rdar://111791782
> Only use week if weekOfYear is missing

- Sources/FoundationEssentials/String/String+Comparison.swift
- Tests/FoundationEssentialsTests/StringTests.swift
We had a fast path implemented incorrectly: We search the UTF8 code unit whenever possible, and convert the found UTF8 index back to String index. If the conversion fails, i.e. when the found UTF8 index does not fall on a character boundary, we simply bail and return nil. The correct implementation should be advancing the slice from the point of failure and keeping searching.
But we don't really need this fast path here as we already have another one that skips string transformation inside the helper function. Let's just remove this.
> `Substring._rangeOf` fast path is incorrect

- Sources/FoundationEssentials/Predicate/Archiving/PredicateCodableConfiguration.swift
- Sources/FoundationEssentials/Predicate/Expressions/StringComparison.swift
- Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift
- Sources/FoundationInternationalization/Predicate/LocalizedString.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
- Tests/FoundationInternationalizationTests/PredicateInternationalizationTests.swift
This adds support for the `localizedStandardContains`/`localizedCompare`/`caseInsensitiveCompare` functions in `Predicate`. These operators are all within `FOUNDATION_FRAMEWORK` blocks currently since we haven't ported the respective `String` APIs over to this repo yet. We also use `localizedCompare` instead of `localizedStandardCompare` here since the `Standard` comparison uses options such as forced ordering, width insensitive, etc. that destinations of these `Predicate`s do not yet support.
Resolves rdar://110083385
> Predicate support for localized/case-insensitive string comparisons

- Sources/FoundationInternationalization/Locale/Locale_Cache.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
An "as-if-current" locale should reflect user's preferences. We do that correctly if `allowsMixedLocalizations` is true, but we missed that if otherwise.
> Locale.localeAsIfCurrentWithBundleLocalizations should respect user preferences

- Sources/FoundationEssentials/Predicate/Predicate.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
Developers may wish to construct predicates dynamically with arbitrary operators determined at runtime (for example, when making a predicate editor UI). The predicate builder closure should return an existential rather than a concrete type to allow for this dynamic construction. We annotate the old initializer as `@usableFromInline` to temporarily preserve the ABI of the old initializer until all call-sites have migrated to the source-compatible new initializer.
Resolves rdar://112423538
> Support Predicate construction with existential expression

- Sources/FoundationInternationalization/Formatting/Date/DateFormatStyle.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/ICUPatternGeneratorTests.swift
We added an override to use the conversational day period option for Taiwan in #168. We should constrain it to when the language is Chinese.
> Consider both language and region when deciding whether to override day period with conversational style

- Tests/FoundationInternationalizationTests/LocaleTests.swift
Syncing LocaleTests.swift after adding a test for some behavior specific to the framework.
> Add test for rdar://111859067

- Sources/FoundationInternationalization/Locale/Locale+Components.swift
We have availability markers missing for some of the `Locale` components.
Resolves rdar://110012154
> Added availability markers for Locale and friends

- Tests/FoundationInternationalizationTests/CalendarTests.swift
These tests assume PT time zone, so they fail when host machine is in other time zone.
> (113147749) (Foundation: Tests failures)

- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
We regressed this behavior in 110211953; Now `IntegerFormatStyle` (and all other number format styles) and `Date.FormatStyle` ignores user's region settings if it uses the current locale.
The regression was caused by us changing to use `locale.identifierCapturingPreferences` for the identifier, which includes "Country" code from global preferences as the extra "rg" keyword. I misunderstood what that represents -- It has nothing to do with the Region setting in System Preferences. We should ignore it internally.
I'm very inclined to remove the reference to that key altogether, but let's keep it for compatibility reason for now.
> (112778892) Unlocalized decimal separators

- Sources/FoundationEssentials/Predicate/KeyPath+Inspection.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
In our key path inspection logic, I unfortunately got a few values wrong when inspecting the memory contents of keypaths. This leads to the inspection logic detecting stored property keypaths which use out-of-line storage (i.e. those with a very large offset in a large struct or those whose offset needs to be calculated at runtime due to properties of resilient types) as multiple components when they are only one component. This PR updates the mask values to ensure the appropriate logic, and the unit test (which accesses keypaths before, at, and after the resilient Date type property) ensures that predicate initialization with these keypaths no longer crashes.
> Predicate incorrectly asserts on some keypaths

- Sources/FoundationInternationalization/Locale/Locale_Wrappers.swift
`CFCalendar` has an additional `calendar` key which `NSLocale` does not. The new Swift locale code needs to honor it as well.
rdar://113875255
> Getting localized calendar description via CFLocale is incorrectly returning NULL

- Package@swift-5.8.swift
- Sources/FoundationMacros/FoundationMacros.swift
- Sources/FoundationMacros/PredicateMacro.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
- Tests/FoundationMacrosTests/MacroTestUtilities.swift
- Tests/FoundationMacrosTests/PredicateMacroBasicTests.swift
- Tests/FoundationMacrosTests/PredicateMacroFunctionCallTests.swift
- Tests/FoundationMacrosTests/PredicateMacroLanguageOperatorTests.swift
- Tests/FoundationMacrosTests/PredicateMacroLanguageTokenTests.swift
- Tests/FoundationMacrosTests/PredicateMacroUsageTests.swift
This PR adds the `#Predicate` macro implementation and its unit tests to the open source swift-foundation repo. This will allow clients of swift-foundation to invoke the `#Predicate` macro to construct predicates using standard swift syntax.
A few notes:
- Adding a macro to a package manifest requires 5.9 tools. Since our current manifest only requires 5.8 tools, I created a copy of it (`Package@swift-5.8.swift`) for those using 5.8 tools that doesn't include the macro, and added the macro to the standard `Package.swift` after bumping its requirement to 5.9 tools
- Macros are currently only supported on Darwin platforms, so the package manifest does not add the macro on linux/windows. This isn't a robust solution (it doesn't work well with cross-compilation, etc.) but I expect it to be …
> Move `#Predicate` macro to FoundationPreview

- Package.swift
While using macros within the compiler itself while building a project is not currently supported on linux/windows, building a macro target and running its unit tests _is_ possible on non-darwin platforms. This change updates the package manifest to build the macro target and its test on all platforms, but only adds the FoundationEssentials dependency on FoundationMacros (to allow the macro to be used during the build of downstream modules) when not on linux/windows.
> Macro tests should run on linux

- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
To assist with maintenance of our `FOUNDATION_FRAMEWORK` `NSPredicate` conversion tests, we're moving the calls to the actual `NSPredicate` initializer into a separate function rather than calling it directly from each individual test.
> Move NSPredicate conversion in Predicate tests into a separate function

- Sources/FoundationInternationalization/Locale/Locale_Wrappers.swift
Some CFLocale API require the result of `localizedString(forIdentifier:)` to remain `nullable`, even though the `NSLocale` entry point is non-nullable. Provide a mechanism to preserve compatibility.
Resolves rdar://110834805
> Allow nullable result for localizedString(forIdentifier:)

- Sources/FoundationInternationalization/Locale/Locale.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Sources/FoundationInternationalization/Locale/Locale_Wrappers.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
In previous releases, `CFLocaleCreateLocaleIdentifierFromWindowsLocaleCode` would return `NULL` for a bad locale code. This restores that behavior instead of returning an empty string.
rdar://113874839
> Empty string is returned instead of null for failure on CFLocaleCreateLocaleIdentifierFromWindowsLocaleCode

- Sources/FoundationEssentials/JSON/JSON5Scanner.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Number prevalidation is looking for a trailing "E" character in a number because Decimal string parsing accepts one, but it's not valid JSON (strtod rejects it). However, this should not apply to hex numbers.
Resolves rdar://114714976
> JSON5 parsing hex number with a trailing ‘E’ fails

- Sources/FoundationEssentials/JSON/JSONWriter.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Two bugs for one here. The "direct array" encoding optimization was bypassing the proper means of serializing strings, such that they were not getting filtered through the character escaping checks.
Also, the code performing those checks were assuming a null-terminated C string, which is not correct in the case of an embedded null character.
And yes, roughly the same code is duplicated (and therefore needs fixing) in two places. Heed the comment regarding this:
```
// Ideally we'd entirely de-duplicate this code with serializeString()'s, but at the moment there's a noticeable performance regression when doing so.
```
Would be happy to find a technique to de-duplicate that without the performance penalty!
> JSONEncoder: Fixed escaping of certain strings

- Package.swift
- README.md
- Sources/FoundationEssentials/Predicate/Predicate.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
With support for macros enabled on Linux, we can now enable the `#Predicate` macro on Linux. Using macros on Linux (and Darwin in Swift packages) requires a 5.9 toolchain so this patch replaces the `os(Linux)` checks with `compiler(>=5.9)` checks. This also bumps the minimum recommended 5.9 snapshot to the September 1st snapshot which added support for macros on Linux.
> Enable the `#Predicate` macro on Linux

- Sources/FoundationEssentials/Predicate/Archiving/ExpressionArchiving.swift
- Sources/FoundationEssentials/Predicate/Archiving/Predicate+Codable.swift
- Sources/FoundationEssentials/Predicate/Predicate.swift
- Sources/FoundationEssentials/Predicate/PredicateBindings.swift
When implementing Predicate, we had to employ a few workarounds to compiler bugs we encountered. Now that these bugs have been resolved, we can go ahead and clean up the workarounds to keep the implementation tidy
> Cleanup old Predicate compiler workarounds

- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
Previously due to a compiler limitation, the `Predicate` unit tests used manual constructions rather than the `#Predicate` macro. Now that the limitation has been lifted, we will update most of the unit tests to use the macro. However, we still leave the basic unit tests as-is until macros are supported on Windows.
> Update `Predicate` Unit Tests to use the Macro

- Sources/FoundationEssentials/String/StringBlocks.swift
- Tests/FoundationEssentialsTests/StringTests.swift
In our implementation of `_getBlock` which is used to find the ranges of paragraphs/lines within strings, we can potentially attempt to form an invalid index of a string resulting in a runtime crash. If the range provided begins at the start of the string and only contains one separator character (as is the case with a string that is only a separator character), then we attempt to form an index before the `startIndex` of the string while iterating backwards to find the contents end. This PR updates the `_matchesSeparators` function to use the `formIndex(_:offsetBy:limitedBy:)` function rather than calling `index(before:)` on what may potentially be the `startIndex` to ensure that we don't form invalid indices and instead break out of the loop as soon as we reach the end of the separator …
> String paragraph/line searching can attempt to form invalid indices

- Package.swift
Now that Swift 5.9 is released and swift-syntax has tagged their 509.0.0 release, we should update our dependency on swift-syntax to specify this tag rather than a snapshot.
> Update swift-syntax tag to 509.0.0

- Sources/FoundationInternationalization/Calendar/Calendar.swift
- Sources/FoundationInternationalization/Calendar/Calendar_Enumerate.swift
Add some more protection against loops and other unusual results in calendar enumeration by throwing on errors instead of returning nil or the original value.
> Refactor Calendar enumeration to throw on error

- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_Autoupdating.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_Base.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_Bridge.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_Cache.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_GMT.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_GMTICU.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_ICU.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_ObjC.swift
- Tests/FoundationInternationalizationTests/TimeZoneTests.swift
We would eventually like to have some core classes like `TimeZone`, `Locale`, and `Calendar` be available with reduced functionality when ICU is not present. For example, we can use GMT (+/- offsets), an English/US/POSIX locale, and Gregorian calendar, with appropriate re-implementations of a much smaller amount of ICU's logic.
The goal is to enable some simple date handling in Foundation for cases like logging ISO8601 timestamps.
This PR is the first step of that, by refactoring the guts of TimeZone to use an abstract base class. The "cache" class serves as a factory, and eventually we will be able to have that class pick the right concrete implementation to use depending on what build environment, platform, or runtime is present.
> Refactor TimeZone to allow for ICU-free specialized implementation of GMT

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
`func unwrapString(from value: ...)` throws `DecodingError.valueNotFound` if the value is `null`, but it incorrectly reports that the expected type as `Array<String>` instead of `String`.
This PR fixes the bug, ensuring that the thrown error reports the expected type as `String` aligning the behaviour with Foundation on existing Darwin platforms.
```swift
DecodingError.valueNotFound(String.self, _)
```
> Fix JSONDecoder.unwrapString expectedType

- Tests/FoundationEssentialsTests/AttributedString/AttributedStringPerformanceTests.swift
- Tests/FoundationInternationalizationTests/CalendarPerformanceTests.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
Remove test_xcode_override_french() from Locale's test. This was added to test a behaviour in a part of the Foundation framework that's not open-source and isn't needed in FoundationEssentials.
Also, update the imports for performance tests. They were importing TestSupport, which was then importing Foundation as `@testable`. In performance tests, we run against a release build of the framework, so that import couldn't succeed. Since performance tests are currently not run in FoundationEssentials (see issue #254) for now we simply import Foundation and XCTest in lieu of TestSupport.
> (113054230) Remove a Locale test and update imports in performance tests

- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
```
/FoundationInternationalization/Calendar/Calendar_Enumerate.swift:370:21: error: value of type 'Date' has no member 'isValidForEnumeration'
guard start.isValidForEnumeration else {
~~~~~ ^~~~~~~~~~~~~~~~~~~~~
error: fatalError
```
> Fix build error on main caused by a missing symbol

- Sources/FoundationMacros/PredicateMacro.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
- Tests/FoundationMacrosTests/PredicateMacroBasicTests.swift
SwiftSyntax has recently introduced a handful of deprecations as part of the 509.0.0 snapshots that we should address in FoundationMacros. This PR addresses the current warnings (as well as an isolated warning in `PredicateTests`). I'll update this as any additional changes are made in SwiftSyntax and plan to merge this as the 509.0.0 tag wraps up. Leaving this as a draft until that happens.
> Address FoundationMacros warnings from SwiftSyntax

- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
A few of our `FOUNDATION_FRAMEWORK`-only unit tests are failing due to new uses of the `#Predicate` macro
> Address predicate test failures due to new uses of `#Predicate`

- Sources/FoundationEssentials/Locale/Locale.swift
Recently, we accidentally updated `Locale`'s hashing and equatable implementations to differ - the `hash(into:)` function sometimes took more information (such as the identifier and preferences) into account than the equatable checking leading to multiple `Locale`s being equal but having different hashes. This change updates the two implementations to be compatible and simplifies the logic.
> Fix mismatched Locale hash/equality implementation

- Tests/FoundationInternationalizationTests/DateComponentsTests.swift
This adds support for Windows which is a LLP64 environment.  That maps `Long` to 32-bit, and thus we need to explicitly cast the value to `CLong` which matches the `labs` signature.
> FoundationInternationalizationTests: explicitly cast to `CLong`

- Sources/_CShims/include/_CStdlib.h
While Windows does have tgmath support, it is difficult to use due to the conflicting definitions originating from clang and MSVC.  Excise this for the time being which allows us to build the full project on Windows.
> _CShims: excise tgmath on Windows

- Sources/FoundationEssentials/AttributedString/AttributedStringProtocol.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
`String` has a natively-implemented `_range(of:options:)`. This PR implements `AttributedString`'s `range(of:options:)` with that when localization support is not needed.
Ideally we should implement this on `BigString` to avoid iterating through `Characters`, which is tracked as a future TODO.
This function takes a `Locale` argument, which isn't available in FoundationEssentials. We could move this to FoundationInternalization where `Locale` is defined, but some clients use it with `locale: nil` and do not need localized results. To make the best of this let's add a non-localized version for FoundationEssentials.
> Implement unlocalized range(of:) for AttributedString

- Tests/FoundationEssentialsTests/PredicateTests.swift
- Tests/FoundationInternationalizationTests/PredicateInternationalizationTests.swift
Now that `Predicate` and its associated types have appropriate availability, we can remove the `FOUNDATION_FRAMEWORK` condition around the `Predicate` tests. Previously, this was needed because `Predicate` had `macOS 9999` availability, but due to variadic generics it didn't actually backdeploy to macOS <14. Now that the availability is correct, the tests will not run unless the host is macOS 14. This will allow these tests to run on macOS 14+ hosts (at desk currently, and in CI in the future when the CI devices are updated)
> Remove `FOUNDATION_FRAMEWORK` restriction on macOS Predicate tests

- Sources/FoundationEssentials/String/BidirectionalCollection.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationInternationalization/Formatting/Duration+UnitsFormatStyle.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
> Follow up for #278 : make the required function from FoundationEssentials `package` so we can use it from FoundationI18n

- Sources/FoundationEssentials/Calendar/Calendar.swift
The comparison result for nanoseconds was backwards. This also takes the chance to switch to a more Swift-friendly version of `modf`.
rdar://116433981
> Date comparison handles nanoseconds incorrectly

- Tests/FoundationInternationalizationTests/CalendarTests.swift
This fixes a few warnings in the calendar tests due to unused variables
> Fix a few warnings in CalendarTests

- Sources/TestSupport/Utilities.swift
- Tests/FoundationEssentialsTests/StringTests.swift
Batch add `String` and `Substring` tests from stdlib. These were removed from stdlib in https://github.com/apple/swift/pull/67252/files and https://github.com/apple/swift/pull/67450/. These tests were added to test Foundation's `StringProtocol` extension that called into `NSString` API.
Now that some of the tests were implemented with Swift natively, they should be made available for FoundationPreview, but we'll track that in a separate PR.
> Add String tests from stdlib

- Sources/FoundationInternationalization/Formatting/Date/DateFormatString.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
The previous logic for escaping the CLDR escape character for literal strings in the date pattern string (') when building the `Date.FormatString` was incorrect, producing invalid date pattern strings, and thus causing the formatting to fail under certain circumstances.
This PR fixes the logic along with the test expectations and adds tests that verify the functionality.
> Fix issue with escaping of literals in Date.VerbatimFormatStyle

- Sources/FoundationMacros/PredicateMacro.swift
In some situations, using the `\.argumentList` key path here causes a crash. While that crash is being investigated, switch to assigning to the property directly to avoid the crash.
> Work around SwiftSyntax crash due to keypath usage

- Sources/FoundationEssentials/ComparisonResult.swift
- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Sources/FoundationEssentials/JSON/JSONWriter.swift
- Sources/FoundationEssentials/SortComparator.swift
- Sources/FoundationEssentials/String/StringProtocol+Stub.swift
- Sources/FoundationInternationalization/String/KeyPathComparator.swift
- Sources/FoundationInternationalization/String/SortDescriptor.swift
- Sources/FoundationInternationalization/String/String+SortComparator.swift
- Sources/TestSupport/TestSupport.swift
- Tests/FoundationEssentialsTests/SortComparatorTests.swift
- Tests/FoundationInternationalizationTests/SortDescriptorConversionTests.swift
- Tests/FoundationInternationalizationTests/SortDescriptorTests.swift
- Tests/FoundationInternationalizationTests/StringSortComparatorTests.swift
Ports the `SortComparator` protocol to FoundationEssentials and the `SortDescriptor` type to FoundationInternationalization. The latter is only really useful with localized sorting.
> Add `SortDescriptor` and `SortComparator`

- Package.swift
- Sources/FoundationEssentials/Predicate/Predicate.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
This updates the last of the predicate tests to use `#Predicate` instead of manual construction and removes the windows restrictions for usage of the macro
> Update remaining Predicate tests to use the #Predicate macro

- Sources/FoundationEssentials/Locale/Locale_Autoupdating.swift
We wrongly returned the entire pref dictionary instead of the demanded value.
I did not want to spend too much time adding a test since this is dependent on the the autoupdating current locale. I did verify the following test failed before but passed after the fix.
```Obj-C
- (void)test24HourOverride {
NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
[formatter setLocale:[NSLocale autoupdatingCurrentLocale]];
[formatter setLocalizedDateFormatFromTemplate:@"Jmm"];
NSString *dateFormat = formatter.dateFormat;
XCTAssertEqualObjects(dateFormat, @"HH:mm");
}
```
> Hour-override isn't respected when formatting date

- Package.swift
This bumps the swift-syntax dependency to 509.0.2 to resolve a compiler crasher that was recently fixed by this tag
> Increase `swift-syntax` dependency to 509.0.2

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/TestSupport/Utilities.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
Implement `dateComponents(from date:)`. The implementation largely follows that of ICU in calendar.cpp and gregocal.cpp. Julian day calculation algorithm is referenced [The Explanatory Supplement to the Astronomical Almanac](https://aa.usno.navy.mil/publications/exp_supp).
First, calculate the Julian day number from a given `Date`. Then, convert the Julian day number to Gregorian calendar date fields[^1]. The remaining part is the time within the day.
There are a few things to look out for
- Julian day starts at noon, while `Date` uses midnight as the reference time, so we need to adjust it acccordingly at every conversion. Note that ICU uses Modified Julian Day number throughout their codebase, which starts at midnight, so
- Dates close to Gregorian calendar adoption, which is also …
> WIP Gregorian Calendar in FoundationEssentials

- Sources/FoundationEssentials/Predicate/Expression.swift
- Sources/FoundationEssentials/Predicate/Expressions/Aggregate.swift
- Sources/FoundationEssentials/Predicate/Expressions/Arithmetic.swift
- Sources/FoundationEssentials/Predicate/Expressions/Collection.swift
- Sources/FoundationEssentials/Predicate/Expressions/Comparison.swift
- Sources/FoundationEssentials/Predicate/Expressions/Conditional.swift
- Sources/FoundationEssentials/Predicate/Expressions/Conjunction.swift
- Sources/FoundationEssentials/Predicate/Expressions/Dictionary.swift
- Sources/FoundationEssentials/Predicate/Expressions/Disjunction.swift
- Sources/FoundationEssentials/Predicate/Expressions/Division.swift
- Sources/FoundationEssentials/Predicate/Expressions/Equality.swift
- Sources/FoundationEssentials/Predicate/Expressions/Filter.swift
- Sources/FoundationEssentials/Predicate/Expressions/Inequality.swift
- Sources/FoundationEssentials/Predicate/Expressions/Negation.swift
- Sources/FoundationEssentials/Predicate/Expressions/Optional.swift
- Sources/FoundationEssentials/Predicate/Expressions/Range.swift
- Sources/FoundationEssentials/Predicate/Expressions/Sequence.swift
- Sources/FoundationEssentials/Predicate/Expressions/StringComparison.swift
- Sources/FoundationEssentials/Predicate/Expressions/Types.swift
- Sources/FoundationEssentials/Predicate/Expressions/UnaryMinus.swift
- Sources/FoundationEssentials/Predicate/Predicate+Description.swift
- Sources/FoundationInternationalization/Predicate/LocalizedString.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
This PR adds descriptions to both `Predicate` and the individual `PredicateExpression` types. In particular, `Predicate` conforms to `CustomStringConvertible` and `CustomDebugStringConvertible` to provide expansive descriptions and compact single-line descriptions respectively and the expression types conform to `CustomStringConvertible` to provide a single, compact description each.
> Add descriptions to Predicate

- Sources/FoundationEssentials/AttributedString/AttributeScope.swift
Adds an import for use of `_dyld_image_count` in `FOUNDATION_FRAMEWORK` block.
> Add import for _dyld_image_count

- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
Update the Windows path for `String.range(of:)` being altered to `String._range(of:anchored:backwards:)`. This repairs the build of FoundationEssentials on Windows.
> FoundationEssentials: repair the `TimeZone` implementation on Windows

- Sources/FoundationInternationalization/Formatting/Duration+TimeFormatStyle.swift
Trivial typo fix: `s/mintue/minute/g`. No public API is affected.
> Fix typo in Duration+TimeFormatStyle

- Tests/FoundationInternationalizationTests/LocaleTests.swift
This is caused by ICU's update: rdar://114361374.
Introduce FIXED_ICU_20187 to indicate the ICU version with the fix and update test expectation behind the flag. The upstream change https://github.com/unicode-org/icu/commit/1afef30549d93c17bb966c6803d5d943cf055925 is scheduled to go into ICU 74. Darwin ICU picked this up earlier than their annual ICU update. When we update FoundationICU to ICU74 we should remove this flag and enable the desired behavior everywhere.
Resolves rdar://118564689
> test_identifierTypesFromSpecialIdentifier() fails on Darwin

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/TimeZone/TimeZone.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Autoupdating.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_GMT.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Protocol.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_Bridge.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_GMTICU.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_ICU.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
- Tests/FoundationInternationalizationTests/TimeZoneTests.swift
To support DST-observing time zone, add a helper function for TimeZone to return the raw offset and DST offset individually so we can fine-tune the behavior for the time during the skipped time frame and the repeated time frame.
> [GregorianCalendar] Implement TimeZone support for `date(from components: DateComponents)`

- Tests/FoundationInternationalizationTests/SortDescriptorTests.swift
A recent change in the type checker seems to have caused this code to time out on build. For now specify the explicit type.
> Workaround type checker timeout

- Sources/FoundationEssentials/Calendar/Calendar.swift
We recently (#289) updated this code to compare nanoseconds correctly, but we found some existing apps depending on the wrong order. This puts in a compatibility check (framework only) to restore the broken behavior until those apps have a chance to update.
> Workaround compatibility issue with nanoseconds fix

- Sources/FoundationEssentials/Locale/Locale_Cache.swift
- Sources/FoundationInternationalization/Formatting/Number/ICUNumberFormatter.swift
- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
`autoupdatingCurrentLocale` only considers its autoupdating-ness as far as hashing and equality goes. That means if we include it in the `Signature` of the caches used for number formatters (which is how we unique them), an underlying change to the current locale does not result in flushing the cache correctly.
Resolve this for number formatting by storing the identifier and preferences directly. Although we do not use the preferences yet, we will need to in the near future to resolve an issue where we do not honor users customized grouping separators.
> Do not attempt to cache based on a signature that uses a `Locale`

- Sources/FoundationEssentials/JSON/JSON5Scanner.swift
- Sources/FoundationEssentials/JSON/JSONScanner.swift
- Sources/_CShims/include/_CShimsMacros.h
- Sources/_CShims/include/string_shims.h
- Sources/_CShims/include/uuid.h
- Sources/_CShims/string_shims.c
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Make sure that CShim functions are (a) hidden in framework mode, because external clients don't use them and (b) exported in package mode, because external clients may end up calling them.
> Adjust symbol visibility for CShims

- Sources/FoundationInternationalization/Formatting/ByteCountFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/Date+IntervalFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/Date+RelativeFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateIntervalFormatter.swift
- Sources/FoundationInternationalization/Formatting/Date/ICURelativeDateFormatter.swift
- Sources/FoundationInternationalization/Formatting/ICUListFormatter.swift
- Sources/FoundationInternationalization/Formatting/ListFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Number/Decimal+ParseStrategy.swift
- Sources/FoundationInternationalization/Formatting/Number/FloatingPointParseStrategy.swift
- Sources/FoundationInternationalization/Formatting/Number/ICULegacyNumberFormatter.swift
- Sources/FoundationInternationalization/Formatting/Number/IntegerParseStrategy.swift
- Tests/FoundationInternationalizationTests/Formatting/DateIntervalFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateRelativeFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/ListFormatStyleTests.swift
Fix up remaining issues where we cache a `Locale` for format styles, and an autoupdating locale will not cause a refreshed format.
Follows up on 18ac5ac (#334 )
Fixes rdar://119010483
> Fix remaining FormatStyle caches of autoupdating locales

- Sources/FoundationEssentials/Predicate/Archiving/PredicateCodableConfiguration.swift
- Sources/FoundationEssentials/Predicate/Expressions/PredicateEvaluation.swift
- Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift
- Sources/FoundationEssentials/Predicate/Predicate+Description.swift
- Sources/FoundationMacros/PredicateMacro.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
- Tests/FoundationMacrosTests/PredicateMacroFunctionCallTests.swift
This PR adds support for combining predicates together to form compound predicates. Predicates can be combined like the following:
```swift
let predicateA: Predicate<String>
let predicateB: Predicate<Int>
let predicateC = #Predicate<String, Int> {
predicateA.evaluate($0) && predicateB.evaluate($1)
}
```
This creates a compound `predicateC` which only evaluates to true when `predicateA` evaluates to true given the first input, and `predicateB` evaluates to true given the second input.
> Support combining Predicates

- Sources/FoundationEssentials/Predicate/Archiving/PredicateCodableConfiguration.swift
- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
It looks like we missed an expression type in the standard configuration. This adds it to allow for encoding/decoding with predicates that contain these expressions without requiring it to be manually allowed.
Resolves #344
> Add RangeExpressionContains to the standard PredicateCodableConfiguration

- Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
`NSPredicate` supports embedded URLs when passing the `NSPredicate` to CoreData, so we should ensure that when converting a `Predicate` to an `NSPredicate` it successfully embeds captured URLs
> Predicate to NSPredicate conversion should support captured URLs

- Sources/FoundationEssentials/String/BuiltInUnicodeScalarSet.swift
- Sources/FoundationEssentials/String/String+Internals.swift
- Tests/FoundationEssentialsTests/StringTests.swift
This implements a file system representation for String for use by file-system related APIs. On Darwin, this is a UTF-8 representation of the NFD form of the string (with a specific set of decomposable characters not equal to those that are decomposable in the current Unicode version) and on Linux this is just the UTF-8 representation of the string as-is.
> Implement file system representation for String

- Proposals/NNNN-calendar-improvements.md
In macOS 14 / iOS 17, `Calendar` was rewritten entirely in Swift. One of the many benefits of this change is that we can now more easily create Swift-specific `Calendar` API that feels more natural than the existing `enumerate` methods. In addition, we are taking the opportunity to add a new field to the `DateComponents` type to handle one case that was only exposed via the somewhat esoteric CoreFoundation API `CFCalendarDecomposeAbsoluteTime`.
> Propose API improvements to Calendar

- Sources/FoundationInternationalization/Formatting/ByteCountFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Number/BinaryFloatingPoint+FormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Number/BinaryInteger+FormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Number/ICUNumberFormatter.swift
- Sources/FoundationInternationalization/Formatting/Number/IntegerFormatStyle.swift
- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
Howdy! I've made some changes to improve your big-number formatting.
- Removed trapping conversion to Int in BinaryInteger/formatted().
- IntegerFormatStyle can format big integers since ([#262](https://github.com/apple/swift-foundation/pull/262)).
- Removed rounding conversion to Double in BinaryFloatingPoint/formatted()
- This method now does whatever FloatingPointFormatStyle/format(\_:) does.
- Reenabled "Decimal Tests" in NumberFormatStyleTests.swift.
- The normal styles worked as-is, but the attributed one needed some love.
- Added a "numeric string representation" case to ICUNumberFormatterBase.Value.
- IntegerFormatStyle.Attributed now uses this value rather than Int64(clamping:).
- Removed conversions to Decimal in each integer format style …
> Improved big-number formatting

- Sources/FoundationInternationalization/Formatting/Duration+UnitsFormatStyle.swift
Fixes an off-by-one error in `Duration.UnitsFormatStyle._getFullListPattern(length:)` for lengths greater than 2 which prevents applying the "end piece" pattern.
> Fix off-by-one in Duration.UnitsFormatStyle list pattern getter

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/TimeZone/TimeZone.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Autoupdating.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_GMT.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Protocol.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_Bridge.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_GMTICU.swift
- Sources/FoundationInternationalization/TimeZone/TimeZone_ICU.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
Currently we implement adding units larger than `.day` as follows:
- Convert the date to date components
- Update the value of the added component
- Convert the date components back to date
The time of the day information is reduced to a `DateComponents` with, e.g. `hour == 1`, `minute == 30`, at step 1. Then when we convert the `DateComponents` back to `Date` at step 3, we always use the *first* occurrence of the time if it falls into the DST repeated time frame.
This is different from `Calendar_ICU`'s implementation, which uses the *latter* and rewind back the date by the DST transition interval (e.g. 1 hour for Pacific Time).
These yeild the same result except for when the input time and the output time are *both* during DST transition time frame. Update the implementation to match …
> [Gregorian Calendar] Handle adding date components across DST transition like Calendar_ICU

- Sources/FoundationEssentials/AttributedString/AttributeScope.swift
- Sources/FoundationEssentials/AttributedString/Conversion.swift
This is a small patch that improves the performance of `AttributedString` to `NSAttributedString` conversion. First, dynamically merging the descriptions of each attribute scope can be expensive, so we now only do that once and cache the result rather than combining scopes dynamically for each request. Additionally, setting an empty attribute dictionary over a run can also be expensive, so we now ensure that we only set attributes for a range of the created NSAS if we have attributes to set (since we know that the string starts with no attributes)
> AttributedString --> NSAS conversion is expensive due to dictionary merging and setting empty attribute dictionaries

- Proposals/0002-additional-configuration-properties-for-formatstyle-implementations.md
- Proposals/NNNN-additional-configuration-properties-for-formatstyle-implementations.md
Foundation defines the `FormatStyle` protocol making it easy to format all kinds of data. However, many of the implementations Foundation provides could offer more customization and do even more to provide access to the configuration after the `FormatStyle` instance has been created. This is critical where the definition of the format and the actual formatting are done in different places or even by different parties.
[Read the full proposal here...](https://github.com/themomax/swift-foundation/blob/maxobermeier/additional-configuration-properties-for-formatstyle-implementations-proposal/Proposals/0002-additional-configuration-properties-for-formatstyle-implementations.md)
Implementation: #338
> Proposal: Additional Configuration Properties for Foundation's `FormatStyle` Implementations

- Proposals/0003-discrete-format-style.md
- Proposals/NNNN-discrete-format-style.md
Foundation defines the `FormatStyle` protocol making it easy to format all kinds of data. While its API works great for defining a format and formatting static values, re-formatting every time a continuous dynamic input value changes is unnecessary and computationally expensive. Format styles need a mechanism to provide information for what inputs it is actually necessary to update the output.
[Read the full proposal here...](https://github.com/themomax/swift-foundation/blob/maxobermeier/discrete-format-style-proposal/Proposals/0003-discrete-format-style.md)
Implementation: themomax/swift-foundation#2
> Proposal: The `DiscreteFormatStyle` Protocol

- Sources/FoundationEssentials/String/String+Internals.swift
- Tests/FoundationEssentialsTests/StringTests.swift
String's file system representation uses a buffer of size `PATH_MAX`, so strings up to size `PATH_MAX - 1` should fit (to leave room for the null byte). However, due to an off by one error, we accidentally failed for strings of exactly length `PATH_MAX - 1`.
> Fix an Off-By-One Error in String's File System Representation

- .gitignore
- Benchmarks/Package.swift
The benchmark package relies on the package at `../` for the `FoundationEssentials` module. By default the package name is inferred to be the directory name, so the dependency on `"swift-foundation"` works if your directory is named `swift-foundation` but fails to resolve the package if your directory is named differently. This adds a manual override for the package name to ensure the name of the directory doesn't influence whether you can build benchmarks
While I'm at it, I added `Benchmarks/.swiftpm` to the `.gitignore` in addition to `/.swiftpm`
> Provide manual name override for local swift-foundation in the benchmark package

- Benchmarks/Benchmarks/Calendar/Calendar.swift
- Benchmarks/Package.swift
Using our nice new benchmarking suite (#291), add some basic benchmarks for Calendar and Locale. We can expand this with more tests over time of course.
> Add some benchmarks for Calendar and Locale

- Benchmarks/Benchmarks/Essentials/Essentials.swift
- Benchmarks/Package.swift
- Sources/FoundationEssentials/UUID.swift
Improves the performance of UUID equality. Also, restores desired behavior (for security reasons) of doing the comparison in constant time.
> Improve performance of UUID equality

- Proposals/0001-calendar-improvements.md
This pull request corrects the argument order and syntax in the Calendar method examples in the Swift Foundation proposal `SF-0001`. The changes ensure that the code examples reflect the current API design and usage.
- Updated the argument order for `Calendar.dates` method calls to match the current API.
- Corrected the missing parenthesis in the leap year date example.
> Correct Argument Order and Syntax in Calendar Method Examples (`SF-0001`)

- Sources/FoundationInternationalization/ICU/ICUPatternGenerator.swift
Simple, straightforward fix - check for success _after_ attempting the operation rather than before it. I can't imagine `udatpg_clone()` fails even remotely often enough for this to ever get noticed under normal conditions (nor can I think of a meaningful unit test, given that a failure trips a fatal error).
> Fix out of order result check in ICUPatternGenerator

- Package.swift
- README.md
Upgrade `SwiftFoundationICU` to `0.0.5` to workaround the build failure.
---
Also fixed the instruction in the `README`
> Upgrade SwiftFoudationICU to 0.0.5

- Benchmarks/Benchmarks/DataIO/DataIO.swift
- Benchmarks/Package.swift
- Sources/FoundationEssentials/CocoaError.swift
- Sources/FoundationEssentials/Data/Data+Error.swift
- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Data/Data+Stub.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Data/Data.swift
- Sources/FoundationEssentials/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/String/String+Internals.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL+Stub.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
- Tests/FoundationEssentialsTests/DataTests.swift
Implements file reading and writing for `Data`. For now use `String` for path instead of `URL`.
> Implement Data reading and writing

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Cache.swift
- Sources/FoundationEssentials/Calendar/Calendar_Enumerate.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Calendar/DateComponents.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ObjC.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
> Calendar Sequence API

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
Implementation follows that of Calendar_ICU and ICU's Calendar::fieldDifference.
Like many calendar algorithms, we get the difference by iterative search: We start advancing from `start` until we reach or pass `end`, striding using the queried component. If we land on `end` exactly, return the striding count as-is. If we pass `end`, do a binary search to find the optimal stride.
> [Gregorian Calendar] Implement `dateComponents(_:from:to:)`

- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
- Sources/FoundationInternationalization/String/StringProtocol+Locale.swift
Enable the code paths guarded behind the feature flag unconditionally now that the feature flag has been enabled for quite a while now.
> Remove `_foundation_essentials_feature_enabled` guard in FOUNDATION_FRAMEWORK

- Sources/FoundationEssentials/JSON/JSONDecoder.swift
Large integers are valid JSON, and we accept loss of precision when converting them to Double.
Since this is an implementation-specific decision, we should document it somewhere.
(The RFC does not specify behaviour for this case, one way or the other.)
> [json] implementation note regarding Double

- Sources/FoundationEssentials/UUID.swift
- Sources/_CShims/include/uuid.h
- Sources/_CShims/uuid.c
Since we export the `uuid` functions from the library, we should prefix them with something so they don't conflict with the (commonly used) names from another UUID library.
> Rename the UUID functions so they do not conflict with other definitions

- Sources/FoundationEssentials/Data/Data.swift
These options need to be public in order to use them outside the module!
> Fix public visibility of Data writing and reading options

- Sources/FoundationEssentials/String/String+Internals.swift
When we have an all-ASCII NSString and we need to get it's filesystem representation we just copy the string's UTF-8 buffer into our new buffer. However, the function used crashes if the destination buffer does not have enough room for the source buffer. To avoid the crash, we now use initialize(from:) instead which returns an iterator that we can use to validate there were no extra un-copied bytes.
> Guard against UTF8 buffers from large strings in NSString filesystem representation

- Sources/FoundationEssentials/Formatting/Date+ISO8601FormatStyle.swift
- Tests/FoundationEssentialsTests/Formatting/DateISO8601FormatStyleEssentialsTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateISO8601FormatStyleTests.swift
Discovered that the new implementation of ISO8601 formatting didn't handle time zones correctly. I fixed that plus added some unit tests.
> ISO8601 time zone outputs is off by 30 seconds

- Sources/FoundationEssentials/ErrorCodes+POSIX.swift
We don't need to redeclare POSIXError here, we can just use the one from Glibc or Darwin.
Also use the platform ifdefs from swift-corelibs-foundation
> Use Glibc or Darwin for POSIX error codes

- Sources/FoundationInternationalization/Formatting/Date/Date+ComponentsFormatStyle+Stub.swift
- Sources/FoundationInternationalization/Formatting/Date/Date+RelativeFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/Date+VerbatimFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/DateFieldSymbol.swift
- Sources/FoundationInternationalization/Formatting/Date/DateFormatString.swift
- Sources/FoundationInternationalization/Formatting/Date/DateFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Duration+TimeFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Duration+UnitsFormatStyle.swift
- Sources/_FoundationInternals/BinaryFloatingPoint.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateRelativeFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DurationTimeFormatStyle.swift
This PR lists all changes proposed in the ["Additional Configuration Properties for Foundation's `FormatStyle` Implementations" proposal](https://github.com/apple/swift-foundation/pull/339), with few exceptions:
1. the proposed changes to `Measurement.AttributedStyle` are not included as that type is not part of Foundation Preview yet
2. a stub for `Date.ComponentsFormatStyle` was added, because it is not part of Foundation Preview yet and `Date.RelativeFormatStyle.Field` is a type alias to `Date.ComponentsFormatStyle.Field`
> Implementation for "Additional Configuration Properties for Foundation's `FormatStyle` Implementations" proposal

- Sources/FoundationEssentials/Data/Data+Writing.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
`Data` slices don't start with zero indices.
> Use correct start index when accessing Data slices

- Package.swift
- Sources/FoundationEssentials/CocoaError.swift
- Sources/FoundationEssentials/Data/Data+Stub.swift
- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/FileManager/FileManager+Bridge.swift
- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+SearchPaths.swift
- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/FileManager/SwiftFileManager.swift
- Sources/FoundationEssentials/FileManager/SwiftFileManagerDelegate.swift
- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL+Stub.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Sources/TestSupport/TestSupport.swift
- Sources/_CShims/filemanager_shims.c
- Sources/_CShims/include/filemanager_shims.h
- Sources/_CShims/include/io_shims.h
- Tests/FoundationEssentialsTests/FileManager/FileManagerPlayground.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
This PR adds a swift-native implementation of `FileManager` that also serves as the new underlying implementation of `NSFileManager`/`FileManager` in Foundation itself on Darwin. With a swift-first approach, there are definitely some areas around this API that we could improve to make more natural in swift (such as the delegate pattern, `async`/`await` support, etc.) but we'd like to land the API as-is currently to provide compatibility with the existing `FileManager` APIs, and leave API improvements as a future direction.
There are some areas of `FileManager` that aren't fully implemented here - notably those APIs that require `URL` implementations. For now the `FileManager` operates on `String`-based path APIs and I'll circle back to add the `URL` functionality later once we can port …
> Port FileManager to swift-foundation

- Sources/FoundationEssentials/String/String+Internals.swift
- Tests/FoundationEssentialsTests/StringTests.swift
There are certain strings that historically use the file system representation that aren't strictly paths (such as environment values and arguments to a launched process). Since these can exceed the size of `PATH_MAX`, we should use a variable size for the buffer rather than a fixed `PATH_MAX` size
> File system representations should not be limited to PATH_MAX

- Sources/FoundationEssentials/Date.swift
`Date` has conformed to `Strideable` in the framework for a while now.
> Add Strideable conformance to Date

- Sources/FoundationEssentials/String/String+Internals.swift
- Tests/FoundationEssentialsTests/StringTests.swift
The file system representation for a `String` previously used `utf16.count * 9 + 1` because (given the specific character decomposition rules for file system representations) the largest ratio of UTF-16 scalar to decomposed UTF-8 scalar was 1:9. However, `utf16.count` is not efficient for native Swift strings which are backed by UTF-8 buffers, so this switches the calculation to use the UTF-8 view instead with `utf8.count * 3 + 1`. This is a similarly-calculated ratio: the maximum ratio of UTF-8 scalars to produced decomposed UTF-8 scalars is 1:3 (see examples inline in the comments) and I added some of these examples as a test case for validation as well to ensure that in the worst possible scenario we don't overflow the buffer.
> Efficient buffer size calculation for String file system representation

- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/_CShims/include/platform_shims.h
- Sources/_CShims/platform_shims.c
Lock the environment when resolving.
While I was here: also added nullability annotations.
> Add lock when retrieving ProcessInfo.environment

- Sources/FoundationInternationalization/TimeZone/TimeZone_ICU.swift
- Tests/FoundationInternationalizationTests/TimeZoneTests.swift
We're capping the time zone offset calculation to some arbitrary dates, so the results outside of the date range are incorrect.
The range was added originally as a workaround for poor ICU performance in `ucal_get` for rdar://6238412, but since then ICU has added new API, which we also adopted, so it shouldn't been needed now.
> Incorrect result for secondsFromGMT for remote dates

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
Use the date component's time zone if there is one.
Resolves 122918762
> CalendarGregorian's date(from: components) does not honor the DateComponents time zone

- Sources/FoundationEssentials/Calendar/Calendar_Enumerate.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Formatting/DiscreteFormatStyle.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Duration+Utils.swift
- Sources/FoundationInternationalization/Formatting/Date/Date+AnchoredRelativeFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/Date+RelativeFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/Date+VerbatimFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/DateFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
- Sources/FoundationInternationalization/Formatting/Duration+Formatting.swift
- Sources/FoundationInternationalization/Formatting/Duration+TimeFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Duration+UnitsFormatStyle.swift
- Sources/TestSupport/TestSupport.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DateRelativeFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DiscreteFormatStyleTestUtilities.swift
- Tests/FoundationInternationalizationTests/Formatting/DurationTimeFormatStyle.swift
- Tests/FoundationInternationalizationTests/Formatting/DurationUnitsFormatStyle.swift
This PR lists all changes proposed in the ["The `DiscreteFormatStyle` Protocol](https://github.com/apple/swift-foundation/pull/340), with few exceptions:
1. Conformance for `Date.ComponentsFormatStyle` is not included as the type is not part of FoundationPreview yet
2. Conformance for `Date.ISO8601FormatStyle` is not included to the type's recent rewrite.
> Implementation for "The `DiscreteFormatStyle` Protocol" proposal

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Standardizing a path has historically unconditionally changed some paths in certain directories to support auto mount paths. However, there are certain directories on Darwin that exist when the system is installed that we know will never be an auto mount path, so we now instead exclude them from this behavior to avoid standardizing a path to something that has different semantic meaning.
> Exclude some paths from automount standardization

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Locale/Locale+Components.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
We are capping the input `Date` to the internal upper bound in various internal functions. This caused the incremental search functions to loop indefinitely because the search results are always the same since the effective input never changes.
Remove the capping from internal functions entirely. The capping was added to improving performance when calling into ICU. We should instead move the capping up to Calendar.swift, the call site to reach consistent behavior, but not inside the implementation.
Also fix miscellaneous other problems found in testing
Resolves 122946218
> CalendarGregorian search functions may loop indefinitely when reaching the capped date

- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/String/String+Path.swift
This PR fixes two small issues:
1. Resolving symlinks in a path should use `getattrlist` for absolute paths, not relative paths (this resulted in slower-than-expected performance for absolute paths)
2. Setting cat info attributes for a file should be a no-op when no relevant attributes are specified
> FileManager's setAttributes:forItemAtPath: is unnecessarily slow

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
The file manager implementation needs to call the `fileManager` variable when calling other FileManager functions instead of using `self` in order to call down to an overriden subclass implementation if present. I accidentally used `self` instead of `fileManager` in one instance which resulted in subclasses experiencing different behavior with this swift implementation of `FileManager`. I'll followup with a future change to make this mistake harder to create by potentially renaming the internal functions to be different than the public API functions.
> FileManager directory creation doesn't call to subclasses

- Sources/FoundationEssentials/Predicate/Expression.swift
Instead of a global lock, we can use a global atomic counter instead for incrementing PredicateExpression.VariableID. Let's use it!
> [Predicate] Use a global atomic counter for VariableID

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
When resolving symlinks via the quick-path using `getattrlist`, we accidentally dropped ~8 characters from the start of the path due to incorrectly offsetting by `attr_dataoffset`. Since this offset is the offset from the start of the returned buffer struct and not from the path buffer itself, we don't need to use this offset here and instead can just use the pointer directly without advancing it. Previously, the unit test would drop the leading 8 characters from the path (and we call the internal function from the unit test to avoid standardizing `/private/var` paths to `/var` which coincidentally also looks like dropping the leading 8 characters but is intentional.
> Resolving symlinks can remove prefix from path

- Proposals/NNNN-swift-subprocess.md
This PR introduces a proposal for `Subprocess`.
> Introduce Swift Subprocess Proposal

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Cache.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/TestSupport/Utilities.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
- Fix precision issues around nanoseconds calculation.
Update test expectations.
- Lessen the chance of overflowing `func add(:)` by using `Double`
We eventually convert to Double before return anyways.
- Disable TestDateComponentsDiscreteConformance.testRandomSamples temporarily for 32-bit platforms
This test triggers code path that has wrong assumption on Calendar API's return value, and overflows when the input dates are distant from each other. Disable it for now. Will track the fix in 123262305
Resolves 123318367
> Use `_CalendarGregorian` as the backing calendar for `struct Calendar`

- Sources/FoundationEssentials/Error/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/TestSupport/TestSupport.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
This change updates the checking of the `removefile` result value to ensure that errors are properly thrown from `removeItem(atPath:)` calls on Darwin where we use `removefile`
> FileManager.removeItem does not throw error when encoutering long paths

- Sources/FoundationEssentials/FileManager/FileManager+SearchPaths.swift
Some clients of the search paths `FileManager` API may provide values greater than `UInt32.max` that still fit inside the API defined requirement of `UInt`. These values don't hold meaning at runtime so we should simply truncate the high order bits instead of crashing here.
> foundation_sysdir_start_search_path_enumeration shouldn't crash with extra option bits set

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
Guard against infinite loop by validating each intermittent result. This is similar to what we're doing in Calendar enumeration functions.
Resolves 123660148
> [Gregorian Calendar] Guard against potential infinite loop caused by iterative search

- Benchmarks/Benchmarks/Calendar/Calendar.swift
- Benchmarks/Benchmarks/DataIO/DataIO.swift
- Benchmarks/Benchmarks/Essentials/Essentials.swift
- Benchmarks/Benchmarks/Formatting/Formatting.swift
- Benchmarks/Benchmarks/Predicates/Predicates.swift
Adds use of the `FOUNDATION_FRAMEWORK` define to the benchmarks so we can use them in more build configurations.
I also took the opportunity to clean up some of the settings (don't use ARC counting, for example), and further segment the predicate tests until we get some attention on that compile time issue with predicates with 3 items.
> Add framework-style builds to Benchmarks

- Package.swift
We use `9998` as a version number to signal a "future" version because it does not have the same compiler magic as being available everywhere like `9999`. However, there are APIs in the standard library we use only on a future OS that are marked as available in the magic `9999` version. This PR switches uses of `9998` to `10000` to still avoid the compiler magic around `9999`, but ensure the version is greater than that of the standard library future APIs we use, such as `_literalPattern`. This should resolve the compilation errors we're seeing in CI
> Update 9998 availability to 10000 availability

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
We triggered a Swift runtime error when converting a `Double` to an `Int` because the value exceeds the value representable by an `Int`. This patch works-around this issue with the following:
- Return a capped value if the date exceeds the bound before conversion.
- Ensure compatibility among various `_CalendarProtocol` observers by capping the input date upfront.
Resolves 123664232
> [Gregorian Calendar] Guard against julian dates that are too far away to be representable by `Int`

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
When checking if a date matches components, we were checking whether isLeapMonth has been set, but were not reading its actual value. This meant that this method would sometimes return wrong results in calendars that have leap months.
> Calendar.date(_: , matchesComponents: ) does not check for leap months correctly

- Sources/FoundationEssentials/Data/Data+Writing.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
On Darwin, at least, we need to limit the size of each chunk to 2GB. Other platforms may have higher requirements, which this is compatible with. If any have lower, we will need to account for that in the future.
I also fixed a bit of code where we are passing a `0` to `POSIXError` instead of errno.
> Data.write fails with EINVAL when writing 2GiB or more

- Sources/FoundationEssentials/Data/Data+Writing.swift
Previously on 32 bit platforms, taking `1 << 31` and subtracting `1` here would cause an integer underflow (which causes an abort) as `1 << 31 == Int.min` on 32 bit platforms. Instead, we now use `Int32.max` here (which is equivalent to `(1 << 31) - 1` but without possibly causing issues due to different integer sizes)
> Prevent data writing integer underflow on 32 bit platforms

- Sources/FoundationEssentials/Formatting/Date+ISO8601FormatStyle.swift
- Tests/FoundationEssentialsTests/Formatting/DateISO8601FormatStyleEssentialsTests.swift
Round towards zero, matching previous ICU implementation and also avoiding a situation where we round from 999 to 1000 for milliseconds.
> Round towards zero, matching behavior of previous ICU implementation

- Sources/FoundationInternationalization/String/String+SortComparator.swift
- Tests/FoundationInternationalizationTests/StringSortComparatorTests.swift
SortComparator’s StandardComparator always uses `Locale.current` instead of checking the `isLocalized` property.
> Fix lexical sorting for SortComparator

- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
This bug is due to ICU's handling of ambiguous/conflicting components. If both "day of year" and "day of month" fields are set via `ucal_set`, the newer one takes priority. Therefore it breaks existing behavior when we set "day of year" after having set "day of month".
Fix this by moving "day of year" before "day of month" to maintain compatibility.
123703256
> Reorder day of year and day of month for Calendar calculations

- Sources/FoundationEssentials/Data/Data+Writing.swift
We need to import DarwinPrivate for the framework build to get the `VREG` constant.
> Import DarwinPrivate to get VREG

- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
`_platform_shims_lock_environ` locks the global environment, which is very disruptive. We should limit the amount of call outs as much as possible. This patch copies the environment values before attempting to create strings out of it. 
resolves: rdar://123704736
> ProcessInfo.environment should create String values outside of lock

- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
Swift's `CommandLine.arguments` doesn't always report the full executable path, most noticeably when the app is launched via `PATH` instead of full path name (`ls` vs `/bin/ls`). This patch adds a fallback to retrieve the full executable path for arg0
resolves rdar://122930912
> ProcessInfo Bincompat: always use full executable path for arg0

- Sources/FoundationEssentials/String/String+Path.swift
The previous ObjC implementation of `FileManager` standardized the home directory path, but the new Swift implementation did not. This could lead to home directory paths (vended by APIs such as `urls(for:in:)`) beginning with prefixes such as `/private/var` instead of `/var`. Restore the old behavior of standardizing home directory paths for behavioral compatibility.
> FileManager should standardize home directory paths

- Benchmarks/Benchmarks/DataIO/DataIO.swift
- Sources/FoundationEssentials/Data/Data+Base64.swift
- Sources/FoundationEssentials/Data/Data+Stub.swift
- Sources/FoundationEssentials/Data/Data.swift
Update Data with some requirements for the Framework side builds of base64 and others. For now we will continue to use the NSData implementation there, and come back later to unify once we have validated the performance requirements. Added a base64 benchmark.
> Update Data.swift framework side builds; add base64 benchmark

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Locale/Locale.swift
- Sources/FoundationEssentials/Locale/Locale_Autoupdating.swift
- Sources/FoundationEssentials/Locale/Locale_Protocol.swift
- Sources/FoundationEssentials/Locale/Locale_Unlocalized.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
"First day of week" and "minimum days in first week" are locale specific. Move the logic of fetching the locale's preferred value into `LocaleProtocol`, so that calendar can return the value from its enclosed locale.
Resolves 123630636
> Calendar should return the first day of week of its locale

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Currently, `FileManager`'s `attributesOfItem(atPath:)` returns a dictionary which only contains values for the `immutable` and `appendOnly` keys if the value is true, otherwise the dictionary does not contain the key. Instead, we should always add the value to the dictionary even if the value is false to match the previous behavior of the ObjC implementation.
This also adds a drive-by fix to ensure that we can also read `Bool` values for these keys in `setAttributes(_:ofItemAtPath:)` instead of just numeric values like `Int` outside of `FOUNDATION_FRAMEWORK`.
Resolves rdar://123713046
> FileManager should always return values for immutable/appendOnly attributes

- Sources/FoundationEssentials/FileManager/FileManager+SearchPaths.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
This code is only called for specially handled cases in search path enumeration. In these specially handled cases, the previous code to strip trailing slashes from the string accidentally truncated one too many characters for strings ending in a slash, resulting in paths ending like `<some path>/.Tras` instead of `<some path>/.Trash`. This replaces the buffer truncation logic with a string initialization and string index logic (which is now correct). It's ok to not call to FileManager here since we use the default file manager, so calling `String(cString:)` directly is much more efficient.
> Fix FileManager macOS trash folder truncation

- Sources/TestSupport/TestSupport.swift
We started getting errors about duplicated symbols now that `DiscreteFormatStyle` has landed in SDK. Workaround this by adding a typealias like other types.
> Duplicated DiscreteFormatStyle in tests

- Package.swift
Now that [swift-collections 1.1](https://github.com/apple/swift-collections/releases/tag/1.1.0) is released, we can update our dependency to point at that tag. Our previous dependency was on a particular commit on the `release/1.1` branch, but now we'll depend on the official tag instead of a particular commit. This tag includes everything that swift-foundation needs.
> Update swift-collections dependency to the 1.1 tag

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Previously, the ObjC implementation of `FileManager` did not crash on modification dates provided that were malformed (for example, having a time interval of +/-Inf or NaN), but the new swift implementation crashes because that new value cannot fit inside of the integer sized type defined by the system module. Instead, we now ignore this attribute value if the date cannot fit into the appropriately sized integer type.
> FileManager should not crash on malformed modificationDate attribute value

- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
`ProcessInfo.arguments` assumed `CommandLine.arguments` is always non-empty, and that turns out not to be the case 100%. Added bounds check to avoid crashing.
> Add bounds check for CommandLine.arguments since it could be empty

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
When adding month or year to a `Date`, we convert a `Date` to a `DateComponent`, modify the component, and convert the modified `DateComponent` back to `Date`. However for dates falling into the "repeated" time frame on DST end date, we do not have the information of which time the `DateComponent` represents when converting it back to `Date`.
This has been the design, and we have always assumed the second occurrence. The only implementation difference is that in the ICU implementation, we return early when the value is 0 and do not proceed onto adding. We should do that for GregorianCalendar too.
Resolves 124231654
> Return early if the component value being added is zero

- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
In JST (GMT+9) the date will be `2021-04-13 00:04:32`, so the tests would fail.
Kudos to @norio-nomura
> Make `DateAttributedFormatStyleTests.testSettingLocale` time zone independent

- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Data/Data.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
A case I missed when bringing Data writing into Swift -- `NSMutableData` is copied when bridged into `struct Data`. There is no need to do that.
Here I just lower the stack of writing functions to the lowest common denominator, which we used eventually when we call the bare `write` function -- `UnsafeRawBufferPointer`. Explicitly listing the input type of the ObjC function as `NSData` instead of `Data` avoids the bridge itself and allows the Swift code to grab a pointer/size pair.
> Avoid copying mutable NSData subclasses when writing

- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/String/String+Path.swift
Historically, Foundation has ensured a stable home directory for processes that call `seteuid` by falling back to `getuid()` when the EUID is the root user. This ensures that processes calling `seteuid(0)` maintain a stable home directory. In order to preserve compatibility with clients expecting this behavior, restore the behavior to the swift implementation.
> Ensure stable home directory for processes calling seteuid

- Sources/_CShims/include/string_shims.h
- Sources/_CShims/string_shims.c
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
The module is internal to Foundation's implementation only. In addition, the call site for it was a disabled test.
> Do not include _CShims from the test project

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/TestSupport/TestSupport.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Previously when `attributesForItem(atPath:)` was written in Objective-C, the effective type of the value for the `.type` key was an `NSString`. In Swift, we added it to the dictionary as a `FileAttributeType` but to preserve compatibility with clients relying on `NSString` to `String` casting (ex. `attributesForItem(atPath: ...)[.type] as? String`) we will store the value as an `NSString` instead where `NSString` is available (in non-`FOUNDATION_FRAMEWORK` we continue storing it as a `FileAttributeType` since this promotes the best Swift interface rather than storing the raw value as a `String`)
> attributesForItem(atPath:) uses FileAttributeType instead of String

- Sources/FoundationEssentials/FileManager/FileManager+SearchPaths.swift
The previous ObjC implementation masked the provided domains to a list of known, valid, public domains. For clients providing the "all domains" value, the new swift implementation doesn't appropriately drop bit values for domains not in this masking list resulting in unexpected behavior. This PR adds the masking behavior to the new Swift implementation
> `_SearchPaths` doesn't correctly mask invalid domains

- Sources/FoundationEssentials/Locale/Locale_Cache.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
We re-construct a `Locale` everytime `calendar.locale` getter is called with `Locale(identifier:preferences:)`. When `preferences == nil`, this "preference-carried" `Locale` should behave exactly the same as a "fixed" locale.
Since we cache all fixed locale by their identifiers already, we should just return one from the cache instead of creating a brand new one. This allows us to reuse all precomputed values and avoid having to call into ICU repeatedly.
124868926
> `Calendar.startOfDay(for:)` preformance regression

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/RecurrenceRule.swift
- Tests/FoundationInternationalizationTests/CalendarRecurrenceRuleTests.swift
This commit adds the new `Calendar.RecurrenceRule` struct that was introduced in
SF-0009. It doesn't implement enumeration of recurrences, that will be done in a
separate commit. Resolves rdar://120559017.
> Add `Calendar.RecurrenceRule`

- Package.swift
Many of `FoundationInternationalization`'s unit tests are failing and we traced it down to an issue in ICU (not *caused by* ICU... see https://github.com/apple/swift-foundation-icu/pull/19 for details). Pin `swift-foundation-icu` to this specific commit until we tag a new version (likely after ICU 74 upgrade).
> Update FoundationICU to fix broken unit tests

- Benchmarks/Benchmarks/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Autoupdating.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Calendar/Calendar_Protocol.swift
- Sources/FoundationEssentials/Locale/Locale.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
CalendarGregorian currently decomposes `Locale` into its identifer plus preferences, stores the two properties separately, and recreates everytime a `Locale` when needed. This results in us always creating new locales, and calling ICU whenever requesting its properties. While we do have cache in place for `Locale.init(identifier:preferences:)` for nil `preferences`, we are not hitting the cache because `preferences` is always non-nil when calendar is `.current`.
Fix this by storing a `Locale` inside calendar so we always hit the cache. This also allows `Locale.autoupdatingCurrent` to work properly -- previously you would not get the right locale back if you set `calendar.locale = Locale.autoupdatingCurrent`. This change fixes that as the identity of the `Locale` is now preserved.
Resolves …
> Calendar.dateComponents(:) performance issues

- Package.swift
- Sources/FoundationMacros/PredicateMacro.swift
This updates our dependency on swift-syntax to 510.0.0 now that Swift 5.10 has been released. The code change is due to a new deprecation warning on `argumentsList` which was replaced by `arguments` in SwiftSyntax 510.
> Update swift-syntax dependency to 510.0.0

- Tests/FoundationEssentialsTests/DataIOTests.swift
Added a test for `String(contentsOf:)` for the empt file case.
> Add tests for String(contentsOf:) for empty string

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
When deciding the component values when calculating `Date` given a `DateComponent`, we incorrectly rewind to the previous year if `weekOfYear == 1` regardless of the passed-in `month`. This adjustment is incorrect and unncessary when `month == 1` -- being in the first month already presumes the start of the year, so doing so results in over-adjustment.
Fix this by skipping this adjustment if we're already in the first month.
Resolves 124661497
> [Gregorian Calendar] Correctly handle last week of year and first week of year when calculating a `Date` from `DateComponents`

- Sources/FoundationInternationalization/Formatting/Duration+UnitsFormatStyle.swift
Because it is unnecessary to sort values to get the smallest one, replaced `sorted` with `min`.
(Since a smaller `rawValue` represents a larger unit, an inequality operator is inverted.)
> Remove an unnecessary sort

- Sources/_CShims/platform_shims.c
This was obscuring the current foundation blocker for Windows: ICU. The last update to ICU broke the Windows build and there does not seem to be a clear repair for that. See apple/swift-foundation-icu#15 for more details on the ICU failure. In the meantime, repair the `environ` handling for Windows. `unistd.h` is the Unix standard header which must be available when `__unix__` is defined. Add an explicit check for that to avoid including the header on other platforms.
> _CShims: repair the Windows build

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Error/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/String/String+Path.swift
This allows us to get further into building FoundationEssentials once again on Windows. Much of the file system work has resulted in this module no longer being viable on Windows and will need to be replaced to allow building on Windows which does not have the `fts` APIs.
> FoundationEssentials: add some missing imports for Windows

- Sources/FoundationEssentials/Data/Data+Writing.swift
`data.bytes` will add a retain/autorelease on the argument `NSData` here (because it needs to extend the lifetime of the object). This can be surprising to clients calling in from ObjC who do not have their own autoreleasepools in place.
> Add an autoreleasepool around callout to Swift data write

- Package.swift
This patch upgrades `FoundationICU` to `0.0.6` which contains two important fixes:
- Temporary fix for failing Unit tests on macOS
- Fix building on Windows.
> Upgrade FoundationICU to 0.0.6

- Sources/_CShims/platform_shims.c
Update import condition to `__has_include` so it's more permissive (we only really care about being able to import `<unistd.h>` here anyway).
> Update platform_shims' import condition to __has_include

- Sources/FoundationEssentials/Data/Data+Writing.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
Calling `Data.write(to:)` invokes a call to `fsync` on the file descriptor before returning. On Linux, `fsync` will return `-1` and set `errno` to `EINVAL` for special files (such as `/dev/stdout`) but this is safe to ignore. This change pulls in a test case originally in swift-corelibs-foundation to test this and suppresses this error only on Linux (the `fsync` call on macOS succeeds)
> Support data writing to special files on linux

- README.md
Since Swift 5.9 (actually 5.10 even) is bundled with Xcode we can remove the instructions on how to install the development version of the toolchain. Should we also remove the 'Development Focus for 2023' part too since it's 2024 now?
> Remove outdated building instructions

- Sources/FoundationEssentials/Data/Data.swift
- Sources/FoundationEssentials/Data/DataProtocol.swift
- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
When trying to revive the Windows port, these warnings clutter the current set of things to resolve still. Silence the warnings by explicitly ignoring the results.
> FoundationEssentials: squelch some warnings

- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Sources/FoundationEssentials/Error/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/Error/ErrorCodes+Win32.swift
Introduce the new Win32 error domain and error type to allow us to represent the underlying OS error for file system operations. This prepares us for the necessary support in `FileManager`.
> FoundationEssentials: introduce a new error domain for Windows

- Sources/FoundationEssentials/Calendar/Date+FormatStyle.swift
- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Sources/FoundationInternationalization/Formatting/Date/DateFormatStyle.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
With #518 and #392 merged, we can now enable ISO8601 encoding/decoding for the FoundationEssentials `JSONEncoder` and `JSONDecoder`.
This also moves the fundamental `Date` formatting API down to Essentials, since it depends only on the `FormatStyle` type which is also in Essentials.
> Enable ISO8601 encoding and decoding on top of new ISO8601 implementation

- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
Disable exhaustive tests on platforms that assume Int is Int64
Resolves 125999523
> NumberFormatStyleTests.swift:642:30: error: integer literal '92233720368' overflows when stored into 'Decimal'

- Sources/FoundationEssentials/Predicate/Expression.swift
- Sources/FoundationEssentials/Predicate/Expressions/ExpressionEvaluation.swift
- Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift
- Sources/FoundationEssentials/Predicate/Predicate+Description.swift
- Sources/TestSupport/TestSupport.swift
- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
Temporarily mark the `Expression` type and associated types as `@_spi` while I work out some downstream build issues
> Temporarily mark Expression as SPI

- Sources/FoundationEssentials/String/String+Internals.swift
Filling a file system representation into a buffer currently partially fills the buffer in the failure case, and the buffer can be filled with a partial unicode scalar (i.e. only the first UTF-8 scalar out of 3 in a unicode scalar) before failing. Previously the ObjC implementation ensured that while we partially fill the buffer during failure we never partially fill it with incomplete UTF-8 so this adjusts the swift implementation to behave the same way.
This doesn't impact the `withFileSystemRepresentation` function our swift implementations use as we never use the partial buffer in the failure case.
> Avoid filling file system representation with partial scalars on failure

- Sources/FoundationEssentials/String/String+Internals.swift
This helper allows us to convert paths to the NT path representation. The NT Path representation is important for internal usage as it allows us to bypass the `MAX_PATH` (261) limit for Win32 APIs. In order to do this, we simply escape the string with the NT prefix (`\\?\`) which requires that the path is normalised (uses `\` rather than `/`) and generally should be an absolute path. Using the NT path allows us to use the fully supported 32k character path length of the NT kernel.
> FoundationEssentials: add `withNTPathRepresentation`

- Sources/FoundationEssentials/Calendar/Calendar_Cache.swift
- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
Remove the `_foundation_essentials_feature_enabled` function since we no longer need it
> Remove _foundation_essentials_feature_enabled

- Sources/FoundationEssentials/TimeZone/TimeZone.swift
- Sources/_CShims/include/_CStdlib.h
This fixes a few build failures (mainly on iOS) due to code that references the TZ data file
> Fix build failures related to tz data file

- Sources/FoundationEssentials/Date.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
Add a helper for time conversion and remove some functions which do not make sense on Windows - users are not identified by integral IDs but rather by SIDs. This helps reduce the error diagnostics when building FoundationEssentials on Windows.
> FoundationEssentials: tweak FileManager utilities for Windows

- Sources/_CShims/include/_CStdlib.h
Removes a few extra newline characters in this file that I had forgotten to remove previously
> Remove extra newlines in `_CStdlib.h`

- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationEssentials/WinSDK+Extensions.swift
This allows for us to use the constants without explicitly casting the type to `DWORD` on each site of use. By providing the shadowing overload we can simply use the constants without impacting the readability of the surrounding code.
> FoundationEssentials: provide typed overloads for constants from WinSDK

- Sources/FoundationEssentials/Formatting/BinaryInteger+NumericStringRepresentation.swift
Add a missing import for the math routines that are required for the binary integer representation to be processed properly.
> FoundationEssentials: add missing import for numerics

- Sources/FoundationEssentials/Predicate/Expression.swift
- Sources/FoundationEssentials/Predicate/Expressions/ExpressionEvaluation.swift
- Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift
- Sources/FoundationEssentials/Predicate/Predicate+Description.swift
- Sources/TestSupport/TestSupport.swift
- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
Now that the previous build issues are resolved, we can remove the `@_spi` annotations from `Expression` and its related types
> Remove SPI annotations from Expression

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Tests/FoundationEssentialsTests/GregorianCalendarTests.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
We compute the differences in Calendar component values from the largest to the smallest in `dateComponents(_:from:to:)`, but we are not following the same order in `date(byAdding:to:)`. Change the order of the latter so we add the largest components first.
The results are the same for most cases regardless of the order. The only exception is when the addition moves the date across DST transition. The reason for this is that the implementation aims to maintain the clock time when adding units that are larger than `day` to a date, so that the time in the day remains unchanged even after time zone offset changes. However, we cannot hold this promise if the result lands in the "skipped hour" on the DST start date as that time does not actually exist. To adjust for this case, we adjust the …
> Add components in the order of granularity in `date(byAdding:to:)`

- Sources/FoundationEssentials/AttributedString/AttributedString+UnicodeScalarView.swift
In macOS 14 aligned releases we added a "back deployed" `AttributedString.UnicodeScalarView.distance(from:to:)` function. However, the availability check in the emitted implementation attempts to call the entrypoint within Foundation on macOS 13 aligned releases due to an incorrect availability annotation. This updates the annotation so that building against an SDK that contains this change and back deploying to macOS 13 no longer causes a crash at runtime.
> Fix AttributedString.UnicodeScalarView.distance(from:to:) availability

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
We should be using the NT Path representation to ensure that we can use long paths. Additionally, we need to use the UTF16 encoded variant of the path rather than the UTF-8. Adjust the changing directory path to account for this.
> FoundationEssentials: support changing directories on Windows

- Sources/FoundationEssentials/PropertyList/PlistDecoder.swift
This aligns the raw values of this enum with those on Darwin and those in swift-corelibs-foundation which will make swift-corelibs-foundation adoption of `PropertyListDecoder` easier
> Correct non-Darwin PropertyListFormat raw values

- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
The `URL`-based symlink functions called directly to the `String`-based implementations without deferring to subclasses when present. This simple change defers to a possible subclass when calling to the `String`-based implementations to ensure correct behavior for subclasses that only implement the `String`-based functions and not the `URL`-based ones
> FileManager doesn't defer to subclasses when creating symbolic links

- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Sources/FoundationEssentials/JSON/JSONWriter.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
- Tests/FoundationInternationalizationTests/LocaleComponentsTests.swift
This updates `JSONEncoder` to use an unlocalized sort for its `sortedKeys` option which allows us to enable it in FoundationEssentials
> Enable sortedKeys in JSONEncoder in swift-foundation

- Tests/FoundationInternationalizationTests/Formatting/ByteCountFormatStyleTests.swift
To account for underlying changes in ICU - we now use the `ar_SA` locale here to ensure that we get the expected arabic-indic numerals in the formatted output
> Use ar_SA locale for tests expecting Arab-Indic numerals

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationInternationalization/Formatting/Duration+UnitsFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Number/NumberFormatStyleConfiguration.swift
- Sources/FoundationInternationalization/String/SortDescriptor.swift
- Sources/FoundationInternationalization/String/String+SortComparator.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
- Tests/FoundationEssentialsTests/Formatting/ISO8601FormatStyleParsingTests.swift
- Tests/FoundationInternationalizationTests/TimeZoneTests.swift
1. reso `vl` es -> resolves
2. mini `n` umLength -> minimumLength
3. fract ` ` onal -> fractional
4. beca `su` e -> because
5. retr `ei` ve -> retrieve
6. cur ` ` ently -> currently
7. For `am` tStyle -> FormatStyle
8. Se ` ` onds -> Seconds
> Fix some typos

- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
- Tests/FoundationEssentialsTests/StringTests.swift
This PR implements `String` to `Data` conversion for the `.ascii` and `.nonLossyAscii` encodings in Swift
Resolves rdar://123921236
> Implement ASCII encoding for String.data(using:)

- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
Moved process name resolution to be "on demand" instead of always eagerly resolving  them in `init()` to improved app launch time.
> Change ProcessInfo.procssName to be lazily loaded

- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo+API.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/TestSupport/TestSupport.swift
- Sources/_CShims/platform_shims.c
- Tests/FoundationEssentialsTests/ProcessInfoTests.swift
This adds the implementations of `ProcessInfo` APIs for other platforms such as Windows and WASI (copied from swift-corelibs-foundation) so that this type can fully replace the `ProcessInfo` present in swift-corelibs-foundation
> Add ProcessInfo implementations for other platforms

- Sources/FoundationEssentials/FileManager/FileOperations.swift
The changes to repair the macOS/Linux build adversely impacted the Windows build. Accommodate the API and logic changes for Windows.
> FoundationEssentials: repair the Windows build after tweaks

- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
Windows does not have the same Unix file system APIs (e.g. FTS). Implement a platform specific implementation to compare files on Windows.
> FoundationEssentials: implement file diffing support for Windows

- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
This temporarily disables a portion of this test which is failing due to https://github.com/apple/swift/pull/73347
> Temporarily disable failing part of testDefaultAllowList()

- Benchmarks/Benchmarks/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift
- Sources/FoundationEssentials/Calendar/RecurrenceRule.swift
- Tests/FoundationEssentialsTests/GregorianCalendarRecurrenceRuleTests.swift
- Tests/FoundationInternationalizationTests/CalendarRecurrenceRuleTests.swift
This commit implements the `Calendar.RecurrenceRule` type first pitched in https://github.com/apple/swift-foundation/pull/422.
This type models a subset of RRULE as specified in RFC-5545, section 3.3.10. One
notable difference is that it doesn't support a frequency of "secondly", as that
was not part of the original proposal. It also implements RFC-7529 Non-Gregorian
Recurrence Rules and works with any instance of `Calendar`.
Recurrences are calculated according to our interpretation of the RFCs. As such,
the resulting dates may differ in certain edge cases when compared to other open
source implementations.
Resolves rdar://120559017&123337748
> Implement Calendar.RecurrenceRule.recurrences(of: )

- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/TimeZone/TimeZone.swift
Use the Windows POSIX API spellings to avoid the warnings. Take the opportunity to change the environment handling to ensure that we are able to handle weird unicode environment variables which may not be rendered properly in the ASCII environment representation. Adjust some types to better match the implementation on Windows which is a minor uop to avoid unnecessary `trunc` and `sext` or `zext`.
> FoundationEssentials: clean up some Windows warnings

- Sources/FoundationEssentials/Platform.swift
Adjust the hostname querying to properly respond to the result.
> FoundationEssentials: repair the hostname query logic

- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/_CShims/include/platform_shims.h
Use a dynamically allocated buffer to avoid truncation/underruns that are not possible to recover from. Fix some parameter passing to match the type signature of the C function.
> FoundationEssentials: repair `ProcessInfo` queries for Windows

- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
The terminator is a valid string and will give a valid pointer. However, the string itself is empty (`\0\0`) and indicates the termination of the process environment block. Handle this properly to avoid a buffer overrun.
> FoundationEssentials: properly handle env duplication

- Sources/FoundationMacros/FoundationMacros.swift
- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
- Tests/FoundationEssentialsTests/PredicateConversionTests.swift
- Tests/FoundationEssentialsTests/PredicateTests.swift
Now that blocking issues have been resolved, we can update our unit tests to invoke the `#Expression` macro directly instead of initializing an `Expression` without the macro
> Use the #Expression macro instead of initializing Expression directly

- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
Windows uses a signed integer for enumerations where as other platforms use an unsigned integer. Account for this in the types for the bridged values in Swift.
> FoundationInternationalization: adjust types for enumerations

- Sources/FoundationInternationalization/Formatting/Duration+Formatting.swift
Add the missing import for Windows which is required for the type-generic math routines to function.
> FoundationInternationalization: add missing import for Windows

- Sources/FoundationEssentials/String/String+Internals.swift
The returned value in the success case does not account for the terminating nul character, resulting in the value being 1 less than the allocation required. This was causing a spurious failure and thus unable to compute the location of the process.
> FoundationEssentials: correct an off-by-one error on Windows

- Sources/FoundationEssentials/Data/Data+Reading.swift
This adjusts the data reading path for supporting Windows which does not have the `mmap` function but does provide memory-mapped IO. The difference in the API is sufficient to create a separate path for the wrapping function rather than trying to have a single shared implementation that simply uses different APIs for the system integration.
> FoundationEssentials: support mmap'ed reading on Windows

- Sources/FoundationEssentials/Data/Data+Reading.swift
We were using the wrong buffer when creating the result, forming the wrong deallocation for the buffer. Remove the unnecessary mapping and correct the buffer usage to prevent a cross-domain free of the data.
> FoundationEssentials: correct memory mapping on Windows

- Sources/FoundationEssentials/Data/Data+Writing.swift
In some cases we were throwing a `CocoaError` with an `errno` that was 0. This PR updates all of the places in Data writing where we throw an error with an `errno` that could be outdated (since we make calls between when we capture `errno` and when the function fails). I've updated all of the places where we have this pattern to correctly save the right `errno` value
> Ensure Data Writing throws errors with correct errnos

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/FileManager/SwiftFileManager.swift
- Sources/FoundationEssentials/FileManager/SwiftFileManagerDelegate.swift
- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
Now that we have `URL` in `FileManager`, we can adopt it throughout the APIs. Many of the APIs already existed using the `URL` stub previously available, but now the delegate methods and other APIs have been updated to use the full `URL` implementation.
Some APIs are currently still not available/ported because they rely on the `URLResourceValues` implementation which hasn't been ported yet. Those will be added in a followup PR. I also made 2 minor warning fixes while I was here.
> Utilize URL in FileManager

- Sources/FoundationEssentials/String/RegexPatternCache.swift
- Sources/FoundationEssentials/String/String+Comparison.swift
- Tests/FoundationEssentialsTests/StringTests.swift
Previously the `String.range(of:)` function's regex matching used ICU word boundaries rather than the more advanced Unicode boundaries. However, when we adopted `Regex` for the implementation we changed the behavior because `Regex` defaults to more advanced unicode word boundaries. This changes `String.range(of:)` back to ICU word boundaries for this API
> Use ICU-equivalent \b behavior with Regex for String.range(of:)

- Package.swift
SPM does not permit building macro tests on Windows due to mishandling of build types, resulting in multiply defined `main` which is a strong error on Windows. As a workaround, remove the macro tests for the time being.
> build: adjust package manifest to allow building on Windows

- Tests/FoundationEssentialsTests/StringTests.swift
This unit test started failing in some configurations on macOS. This is because the `range(of:)` function is not defined in FoundationEssentials (just in Foundation) so this test was inadvertently calling to the system Foundation which does not have the fixed behavior on all OS's. While the test now looks a bit more clunky, it explicitly calls the internal entry point in FoundationEssentials rather than the system Foundation to ensure we're testing the right version of this function
> testRangeRegexB can use System Foundation instead of FoundationEssentials

- Sources/FoundationEssentials/Data/Data+Stub.swift
- Sources/FoundationEssentials/Data/Data.swift
- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Sources/FoundationEssentials/JSON/JSONEncoder.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
- Tests/FoundationEssentialsTests/ResourceUtilities.swift
Now that we have the `URL` type ported to swift-foundation, we can begin adopting it in our other APIs. This PR removes the `FOUNDATION_FRAMEWORK` blocks around usages of `URL` in `JSONEncoder`/`JSONDecoder` and the `Data` reading/writing APIs. I'll followup with a change for `FileManager`, but this should bring Data/JSON APIs on-par with what Foundation provides for URL-related behavior and APIs (and removes some of the temporary `String`-based APIs we added
> Use URL in JSON/Data APIs

- Sources/FoundationEssentials/URL/URL.swift
This new helper was added but did not support windows as `stat` is a Unix operation and the Windows equivalent is more nuanced when you are trying to minimise IO overheads. Add a Windows specific path to repair the build on Windows.
> FoundationEssentials: recover from backslide on Windows

- Tests/FoundationEssentialsTests/ProcessInfoTests.swift
Use `Thread.sleep(forTimeInterval:)` instead of `nanosleep` which is not a portable sleep primitive. This allows us to build the package tests on Windows.
> FoundationEssentialTests: `nanosleep` is not portable, avoid it

- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Windows does not have the concept of a "root" user, instead all users have rights assigned to them with a capabilities system. As there is no equivalent for `euid`, simply elide this suite on Windows for now.
> FoundationEssentialTests: elide some tests on Windows

- Sources/FoundationEssentials/Error/CocoaError.swift
- Sources/FoundationEssentials/URL/URL.swift
This PR includes two minor bug fixes identified while adopting `URL` in the re-cored package branch of SCF. This ensures that we use the proper error user info key declaration and also ensures that standardizing a URL or resolving symlinks in a URL will respect the directory designation when that `URL` was initialized even if it doesn't match what's on the filesystem.
> Minor fixes to support using URL in swift-corelibs-foundation

- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL/URL.swift
- Sources/FoundationEssentials/URL/URLParser.swift
Supports initializing file URLs with Windows paths. Allow `"\"` as the path separator, allow UNC paths (`"\\"`) with host, and allow/standardize drive letter paths (`"C:"`). However, we always store the URL with forward slashes to stay consistent for path parsing operations. I think `String.withNTPathRepresentation(_:)` should then be used to convert any `"/"` back to `"\"` before consulting the file system on Windows. @compnerd thoughts on this approach?
The file URL initializers also now resolve against the base URL (or current directory) for checking if the file is a directory.
> Support Windows URL paths in FoundationEssentials

- Sources/FoundationEssentials/Platform.swift
In the case that the query fails due to a reason other than an insufficient buffer, the returned value is 0. However, a 0 sized allocation can trigger an issue, so ensure that we always have a non-zero buffer size before we attempt an allocation.
> FoundationEssentials: protect against a failed query on Windows

- Sources/FoundationEssentials/CodableUtilities.swift
- Sources/FoundationEssentials/String/String+Internals.swift
We would previously conditionally call `GetFullPathNameW` and do string manipulations for normalising the path. Instead, always call `GetFullPathNameW` to normalise the path as per Windows' rules. This more importantly will collapse runs of the arc separator, which is crucial when using extended paths as the NT path form must always use the normalised paths or the access will fail.
> FoundationEssentials: simplify path normalization

- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/URL/URL.swift
- Tests/FoundationEssentialsTests/URLTests.swift
The fix I added in #602 to address this wasn't correct since `.mergedPath(for:)` should be called on an URL that has already been initialized with a base URL. I separated this logic out into a String extension that handles the merging generally and use this method when determining the absolute file path to directory check in `.init(filePath:)`.
> URL.init(filePath:) should resolve against the base URL before checking if the file is a directory

- Sources/FoundationEssentials/FileManager/SearchPaths/FileManager+WindowsSearchPaths.swift
- Sources/FoundationEssentials/WinSDK+Extensions.swift
Repair the Windows build after recent additions for FileManager.
> FoundationEssentials: repair the Windows build

- Sources/FoundationEssentials/Data/Data+Writing.swift
`open` is a variatic function and does not take the same permission modes on Windows. Prefer to use `_sopen_s` to allow us to have a non-variadic signature and repair the runtime on Windows.
> FoundationEssentials: correct the use of `open` on Windows

- Sources/FoundationEssentials/FileManager/FileOperations.swift
The condition of the error check was inverted as it was meant to be a `guard` statement. This was resulting in an infinite loop. With this we now pass a few additional tests and the test suite no longer hangs.
> FoundationEssentials: correct error handling for item removal

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/SearchPaths/FileManager+XDGSearchPaths.swift
There are two pieces of `FileManager` that need to be updated so that swift-corelibs-foundation can use this `FileManager` implementation:
1. When providing file attributes, many call-sites provide numeric attributes as SCL-F's `NSNumber` type. However, since swift-foundation does not know about `NSNumber`, it currently doesn't work. `NSNumber` is implicitly bridged to concrete numeric types, but not to an existential type like `any BinaryInteger`. So to fix this, when reading numeric attributes we now try a direct dynamic cast to the target type (`as? T`) which will succeed if `value` is an `NSNumber`, then we try a dynamic cast to `any BinaryInteger` to catch any other numeric types
2. User directories provided by XDG configuration files can be absolute or relative, but the current …
> Update FileManager for use by SCL-F

- Sources/FoundationEssentials/JSON/JSON5Scanner.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/StringTests.swift
Reimplement `String._transmutingCompressingSlashes` and `pathHasDotDot` without using Regex. Reimplementing this method without Regex allows us to:
- Reduce the additional frames at launch since the Swift rewrite (Regex parsing brings in tons of frames)
- Not having to load additional dylib (`libswift_StringProcessing)
> Improve String+Path performance by removing Regex

- Sources/FoundationEssentials/FileManager/SearchPaths/FileManager+WindowsSearchPaths.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Repair the error reporting on Windows in the case of a failure in `SHGetKnownFolder` - the returned value is a `HRESULT`, which is the extended error code unlike the Win32 APIs which return a `BOOL`.
The "Recyle Bin" is a virtual folder and does not have an associated path with the folder that we can query. Undo the implementation here for the time being to avoid the assertion failure in the runtime.
> FoundationEssentials: avoid precondition failure on Windows

- Sources/FoundationEssentials/Data/Data+Writing.swift
On failure, the error information is stored in `errno` not the Win32 error domain. Use the correct initialiser to ensure that we get the details of the failure.
> FoundationEssentials: correct error reporting for `_mktemp_s`

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
In some cases, the `isDirectory` resource value may not be set even though it was requested. We should gracefully handle this to avoid a crash in this situation
> Gracefully handle cases where the isDirectory url resource might not be set

- Sources/FoundationEssentials/Data/Data+Writing.swift
When trying to perform a move, we would encounter a sharing violation due to the file descriptor being open preventing the file from being moved. Perform an early close of the file descriptor before performing the move. This adds complexity to the defer, however, avoiding the defer complicates the code flow analysis for error propagation.
> FoundationEssentials: avoid a sharing violation on Windows

- Sources/FoundationEssentials/Data/Data+Writing.swift
Windows spells their `open` flags differently. Ensure that we use the Windows spellings on Windows to get the correct value.
> FoundationEssentials: use the correct flags on Windows

- Sources/FoundationEssentials/ComparisonResult.swift
Ensure that the framework and package are using the same implementation of `Codable` for `ComparisonResult`.
> Unify ComparisonResult codable conformance

- Sources/FoundationEssentials/URL/URL.swift
We would strip the first characters of a path if it were non-absolute. For special files like `CON` we would end up stripping the name to `N`.
> FoundationEssentials: do not strip non-absolute paths

- Sources/FoundationEssentials/CodableUtilities.swift
- Sources/FoundationEssentials/URL/URL.swift
Use more named constants when checking for matching constants in the string.
> FoundationEssentials: use named constants for characters

- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Due to an incorrect check of the `lstat` return value, the copy item functions can return incorrect errors when the source file/directory does not exist. This corrects that logic to ensure the appropriate error codes are thrown (and match the error codes in the old ObjC implementation)
> Adjust errors thrown from FileManager's copyItem function

- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Formatting/ByteCountFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/Date+IntervalFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/Date+VerbatimFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/DateFormatStyle.swift
- Sources/FoundationInternationalization/Formatting/Date/DateParseStrategy.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateIntervalFormatter.swift
- Sources/FoundationInternationalization/ICU/ICU+Foundation.swift
- Sources/FoundationInternationalization/ICU/ICUPatternGenerator.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
Instead of assuming ICU calls always succeed, surface the error back to callsites and fallback to some default value if we can't get ICU formatters.
Resovles 125918488
> Handle ICU failures better

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
Follow the expected behaviour to drop invalid modification dates, e.g. `+NaN`. This matches the semantics that are expected on Unix and avoids a crash due to the initialiser.
> FoundationEssentials: drop invalid modification dates

- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
Now that the underlying issue has been resolved, we can re-enable all portions of this test (still guarded by `FOUNDATION_FRAMEWORK`)
> Re-enable all of testDefaultAllowlist()

- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
When enumerating a directory on Windows, we would fail to increment the iterator as we would increment _after_ the return. Insert a `defer`'ed increment on the iterator to allow us to track the state properly. Because the iteration was may have completed on the previous run, we need to track an additional bit of state as `bValid` which provides us an indication if iteration has completed.
> FoundationEssentials: correct directory enumeration on Windows

- Sources/FoundationEssentials/JSON/JSONWriter.swift
Adds a compatibility path within `FOUNDATION_FRAMEWORK` to use the old sorting behavior for JSONEncoder. This does not affect the open source build
> Add compatibility path for JSONEncoder.sortedKeys behavior change

- Benchmarks/Benchmarks/DataIO/BenchmarkDataIO.swift
- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
Also, when asking for progress reporting, cap the number of updates at approximately 100 instead of fileSize/4k.
> Reduce number of read calls when not asking for progress reporting.

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Get the file type using the Win32 APIs and wire that into the attribute dictionary.
> FoundationEssentials: add type to the file attributes on Windows

- Sources/FoundationEssentials/FileManager/SearchPaths/FileManager+XDGSearchPaths.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
During the review for the changes to support Windows, we realized that the location that is being used for the autosave information is only available within the user domain mask. The Windows implementation was corrected as part of the implementation, but this corrects the XDG compliant path to reflect this reality.
> FoundationEssentials: limit autosave to user domain

- Sources/FoundationEssentials/String/String+Internals.swift
When creating a file system representation from the path, we need to strip the leading `/` which is added for the RFC representation of the Windows path. Without this, the C runtime will fail with an invalid argument error. Unfortunately this regresses the test suite by causing a hang.
> FoundationEssentials: strip leading `/`

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
Clients of the existing SCL-F expect to be able to cast file attribute values to any numeric type via `NSNumber` implicit bridging. This works in Foundation.framework today and this PR enables this functionality when SCL-F is imported on non-Darwin platforms by dynamically checking to see if we can initialize an `NSNumber` (falling back to the existing concrete numeric type when `Foundation` is not loaded.
> Return file attributes as NSNumbers when SCL-F is imported

- Sources/FoundationEssentials/String/String+Path.swift
Strip the extended path prefix for bypassing the Win32 API layer. This is guaranteed to be prefixed on strings as per the documentation.
> FoundationEssentials: correct path canonicalisation handling on Windows

- Sources/FoundationEssentials/Data/Data+Writing.swift
Ensure that we open the file in binary mode to avoid line ending conversion. Without this, writing any 0xa byte would translate to writing 0xd 0xa. This improves the test coverage pass rate.
> FoundationEssentials: correct file writing on Windows

- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Sources/FoundationEssentials/URL/URL.swift
In some cases, file manager APIs may be called with malformed string paths. We correctly `throw` an error in those cases, but when throwing an error we try to initialize a `URL` from the path. In certain `FOUNDATION_FRAMEWORK` scenarios this leads to calling into an `NSURL` initializer which crashes. This code works around that crash by creating an internal failable path we can take instead when we know we're in a scenario where we may have malformed paths.
> Avoid crashing due to malformed paths creating URLs

- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
There are some scenarios in which you want to copy attributes from one file to another (for example, from within `copyItem(atPath:toPath:)`. However currently, calling `setAttributes(_:forItemAtPath:)` with attributes retrieved from `attributesForItem(atPath:)` will `throw` because we can fetch `.creationDate` but we cannot set it (yet). Until this functionality is implemented in swift-foundation, we exclude `.creationDate` from the `featureUnsupported` check to ensure that applying attributes that Foundation provides will succeed.
This prevents throwing an error from `copyItem` calls made by SwiftPM when using the new re-cored Foundation
> Prevent throwing when applying file attributes retrieved via `attributesOfItem(atPath:)`

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
On non-Windows targets we ensure that the path exists when we attempt to query the attributes of the path. This adds the same check on Windows so that we can have similar behaviour on all platforms.
> FoundationEssentials: ensure that the path exists when stat'ing

- Sources/FoundationEssentials/AttributedString/AttributeContainer.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+AttributeTransformation.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+CharacterView.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Guts.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+AttributeSlices.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+Run.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+UnicodeScalarView.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+_InternalRun.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+_InternalRuns.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+_InternalRunsSlice.swift
- Sources/FoundationEssentials/AttributedString/AttributedString.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringAttribute.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringAttributeConstrainingBehavior.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringAttributeStorage.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringCodable.swift
- Sources/FoundationEssentials/AttributedString/AttributedStringProtocol.swift
- Sources/FoundationEssentials/AttributedString/AttributedSubstring.swift
- Sources/FoundationEssentials/AttributedString/Conversion.swift
- Sources/FoundationEssentials/AttributedString/FoundationAttributes.swift
- Sources/FoundationEssentials/PropertyList/BPlistEncodingFormat.swift
- Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
When swift-foundation builds within the toolchain, the collections module name will be `_FoundationCollections` instead of separate `OrderedCollections`/`_RopeModule` modules. This change prepares for the toolchain build by conditionalizing between `CollectionsInternal` for `FOUNDATION_FRAMEWORK` builds, `_RopeModule`/`OrderedCollections` for SPM builds, and `_FoundationCollections` for toolchain builds.
> Prepare for _FoundationCollections module name

- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
The internal function returns a FSR value where as the value being returned from the `appendingPathComponent` is not the FSR. Explicitly convert to the FSR for the check.
> FoundationEssentialsTests: we convert to FSR when checking

- Sources/FoundationEssentials/URL/URLParser.swift
In RFC3986Parser, while constructing the percent-encoded urlString, .user, .password, .host, .query, and .fragment all call `percentEncode(_:component:)`, but only .path calls `percentEncodePath(_:)`. 
This PR replaces `percentEncodePath(_:)` with `percentEncode(_:component:)` for consistency.
> Use percentEncode(path, component: .path) instead of percentEncodePath(path)

- Tests/FoundationEssentialsTests/StringTests.swift
We would use the Unix (non-portable) arc separator (`/`). On Windows, we need to ensure that we account for the proper arc separator (`\`) when checking the FSR of the string.
> FoundationEssentialsTests: repair the test suite on Windows

- Sources/FoundationEssentials/Bundle+Stub.swift
This is only an implementation detail and we don't want it to become ambiguous with the `Bundle` from SCL-F currently
> Mark Bundle stub as package instead of public

- Sources/FoundationEssentials/FileManager/FileOperations.swift
Convert a `var` to `let` as it was originally. This variable is no longer mutated and causes a warning.
> FoundationEssentials: silence a warning

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
In the case that the destination exists, we should check for continue after error. If the source does not exist, simply do nothing.
Furthermore, adjust the test to ensure that we are using the path spelling rather than the FSR.
> FoundationEssentials: correct callbacks for `moveItem(atPath:toPath:)`

- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
When performing a `subpathsOfDirectory`, ensure that the path exists. On the non-Windows path, `_FTSSequence` will perform the initial `statvfs` during construction which obscured this requirement. We instead explicitly inline this call in the implementation. This repairs further test failures.
> FoundationEssentials: ensure that the path exists before iteration

- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
We need to use `FILE_FLAG_BACKUP_SEMANTICS` to ensure that we are able to diff directories as well. Previously we would mishandle this case and was caught by the test suite.
Thanks to Jeremy Day for helping resolve this!
> FoundationEssentials: handle directory diff properly

- Sources/FoundationEssentials/String/String+Internals.swift
In the case that the path is canonicalised, the `/` would be replaced with `\`. The leading `\` would interfere with our ability to recognise the absolute path representation and thus get the wrong response.
> FoundationEssentials: handle canonical and non-canonical paths

- Sources/FoundationInternationalization/ICU/ICU+Foundation.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Tests/FoundationInternationalizationTests/LocaleTests.swift
In `_withFixedCharBuffer` helper, we allocate a buffer with the requested size + 1 (for null-termination). With the assumption that the closure's return value `len <= the requested size`, the null-terminated character should be on index `len`, not `len + 1`.
Fixes rdar://129154192
> Potential stack buffer overflow in `_withFixedCharBuffer`

- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
With https://github.com/apple/swift-foundation/pull/644 resolved, we can now enable this test as it now behaves as expected on non-Darwin platforms
> Enable an extra FileManager copyItem test

- Tests/FoundationInternationalizationTests/Formatting/DurationTimeFormatStyleTests.swift
- Tests/FoundationInternationalizationTests/Formatting/DurationUnitsFormatStyleTests.swift
This test was unnecessary disabled for 32 bit platforms.
> Re-enable tests for Duration based DiscreteFormatStyle conformances on 32 bit platforms

- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
The Windows API calls return `ERROR_TOO_MANY_OPEN_FILES` (4) which is "The system cannot open the file.". One of the tests ensures that the return code is 260 which does not match reality.
> FoundationEssentials: adjust error code constants for Windows

- Sources/FoundationEssentials/FileManager/SearchPaths/FileManager+WindowsSearchPaths.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
When running in CI, we would see failures due to the environment variables being changed. This relaxes the precondition to allow the test failure to propagate.
> FoundationEssentials: relax error handling for `SHGetFolderPath`

- Sources/FoundationInternationalization/Formatting/Number/IntegerParseStrategy.swift
- Tests/FoundationInternationalizationTests/Formatting/NumberParseStrategyTests.swift
Hello friends, we meet again!
I've come to propose some changes to IntegerParseStrategy's fallback Double path. Ideally, it should never need to go through Double, but that is out-of-scope for this contribution. Today, I'll only suggest that you reject magnitudes >=(2^53).
In short, Double is a 52-bit window that slides around. The greater the value, the greater the distance between adjacent values. This distance is <=(1) for values in [-2^53, 2^53]. Outside this range, the parseAsDouble(_:) rounds its input String to the nearest Double before the  Double is passed to BinaryInteger.init(exactly:). The lossless range is, therefore, 52 bits since ±(2^53) may represent ±(2^53+1) rounded towards zero. The rounding error is ±(1024) when parsing UInt64 values through Double. Here's a brief …
> Limit IntegerParseStrategy's fallback Double path to lossless integer range

- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
This resolves a build failure on macOS that was accidentally introduced by https://github.com/apple/swift-foundation/pull/670
> Fix calloc build failure on macOS

- Sources/FoundationEssentials/AttributedString/AttributedString+AttributeTransformation.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+AttributeSlices.swift
- Sources/FoundationEssentials/Predicate/Archiving/PredicateCodableConfiguration.swift
- Sources/FoundationEssentials/Predicate/PredicateExpression.swift
- Sources/FoundationEssentials/SortComparator.swift
- Sources/FoundationInternationalization/String/KeyPathComparator.swift
- Sources/FoundationInternationalization/String/SortDescriptor.swift
- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
We found some ABI stability issues with `Sendable` and `@preconcurrency` adoption in areas where we use key paths. This patch reverts those while we figure out what's going wrong.
> Revert some Sendable fixes around KeyPath while we sort out a compiler bug with ABI stability

- Tests/FoundationEssentialsTests/DateTests.swift
The MSVC libc does not properly handle dates that are far out from the Unix epoch. For the purposes of allowing the test suite to pass on CI, skip these tests on Windows.
> FoundationEssentialsTests: skip distant{Future,Past} tests on Windows

- Sources/FoundationInternationalization/ICU/ICU+Foundation.swift
- Tests/FoundationInternationalizationTests/StringTests+Locale.swift
Start the outer buffer with the capacity of `initialSize + 1` so later we can null terminate on the index of `initialSize`, assuming the return length is smaller or equal to `initialSize`. We don't bother to verify the assumption since that'd be a user error.
Also fix a terrible copy-pasta error: We should null-terminate the inner buffer, not the outer buffer.
Fixed 129806508
> Follow up fix for buffer overflow

- Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
If the original string is not contiguous UTF8 (as in the case where it is bridged from NSString), do not use the fast path.
> Only use the underscored utf16 function when we are a contiguous UTF8 string

- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationInternationalization/CMakeLists.txt
- Sources/FoundationMacros/CMakeLists.txt
This fix ensures that `FoundationEssentials`/`FoundationInternationalization`/`FoundationMacros` do not have an rpath entry pointing into the build folder using a setting that we already use on the `main` branch of swift-corelibs-foundation today. Additionally, this adds `$ORIGIN` as an rpath for `FoundationMacros`.
Before this change, we had:
```
root@swift-ci-ubuntu-22:/Repos/swift-dev/swift# readelf -d swift-nightly-install/usr/lib/swift/linux/libFoundationEssentials.so | grep RUNPATH
0x000000000000001d (RUNPATH)            Library runpath: [/Repos/swift-dev/build/buildbot_linux/swift-linux-aarch64/lib/swift/linux:$ORIGIN]
root@swift-ci-ubuntu-22:/Repos/swift-dev/swift# readelf -d swift-nightly-install/usr/lib/swift/linux/libFoundationInternationalization.so | grep RUNPATH …
```
> Correct rpaths in cmake files

- Sources/_CShims/CMakeLists.txt
For the static swift build, we need to install not only the shared libraries but also the static libraries that we need to link against. swift-foundation only has one such library (_CShims) so this adds an additional install step to install _CShims for only the static swift build (it gets statically linked into the `FoundationEssentials` and `FoundationInternationalization` shared libraries in the non-static build)
> Install _CShims in static swift build

- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationInternationalization/CMakeLists.txt
For private dependencies, the compiler needs to know to link the extra static libraries when building against the static stdlib. These extra flags ensure that when linking against `libFoundationEssentials.a` that the compiler also links `lib_CShims.a` and `lib_FoundationCollections.a` and that when linking against `libFoundationInternationalization.a` that the compiler also links `lib_CShims.a` and `lib_FoundatonICU.a`
> [CMake] Autolink static libraries for foundation_static build

- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/Date.swift
- Tests/FoundationInternationalizationTests/CalendarTests.swift
Validate the given `DateComponents` values up front to align with the supported Calendar calculation date range, defined as `Date.validCalendarRange`.
We could alternatively guard all arithmetic operations with `...reportingOverflow`, but there are too many operations, and so it seems untenable. I opted for a more realistic approach instead. `_CalendarICU` unconditionally truncates values to `Int32`, so the results for `Calendar.date(from:)` have always been incorrect for distant dates anyways.
Fixed 129782208
> Overflow when calling `Calendar.date(from:)`

- Sources/FoundationEssentials/Data/Data.swift
- Tests/FoundationEssentialsTests/DataTests.swift
This patch fixes (#638) and adds a regression test.
> Data/copyBytes(to:from:) slice offset fix

- Sources/FoundationEssentials/URL/URL.swift
I had previously used `.init(reference:)` so that an initializer was called in all code paths, but this caused the underlying `NSURL` to be `_converted` twice in those cases. This causes an issue when force-casting `as! NSURL` if the first conversion returns `nil`. This PR adds and uses a `.init(convertedReference:)` that assigns an already-converted `NSURL` to `_url` directly.
> (129922624) Don't convert already-converted NSURLs

- Package.swift
When building/running Foundation tests in swift-ci as part of a full toolchain test (and not just an isolated test of only Foundation), we want to build this package against the locally checked out versions of our dependencies. This checks a new environment variable `SWIFTCI_USE_LOCAL_DEPS` and, when set, will look in sibling directories for our dependencies rather than checking out dependencies from GitHub. This is similar to the setup that some other packages such as [swift-format](https://github.com/apple/swift-format/blob/d46e30fe67b722c950424e09840dfc391651dbfa/Package.swift#L155-L169) use.
> Add SWIFTCI_USE_LOCAL_DEPS build mode

- Sources/FoundationEssentials/Decimal/Decimal.swift
- Tests/FoundationEssentialsTests/DecimalTests.swift
For binary compatibility, `Decimal.init(string:)` should return `nil` instead of `0` for totally invalid Decimal strings. 
resolves: rdar://130209835
> Decimal.init(string:) should return nil for invalid Decimal strings

- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Tests/FoundationEssentialsTests/DataTests.swift
On some platforms like Darwin, attempting to read `Data` from a path representing a socket can cause the `EOPNOTSUPP` error to be thrown, but `POSIXError.Code` is missing a case for this errno so we hit an assertion failure in our code. This patch works around this case to avoid the crash by dropping the posix info from the produced error while still asserting for other invalid errno's to catch cases where we incorrectly capture `errno`
> Ensure EOPNOTSUPP thrown via Data reading from a socket does not crash

- Sources/CMakeLists.txt
- Sources/FoundationEssentials/CMakeLists.txt
- Sources/FoundationInternationalization/CMakeLists.txt
- Sources/_FoundationCShims/CMakeLists.txt
Now that `_CShims` has been renamed to `_FoundationCShims`, we need to update the cmake files to account for this rename
> [CMake] Update CMake build to account for _CShims --> _FoundationCShims rename

- Sources/FoundationEssentials/Data/Data.swift
when bridging back from objc the start index was not correctly re-constructed into the slices of no copy datas. This adds functionality for that.
resolves rdar://130106808
> Slices of no copy Data bridged to and back incorrectly account for the start index

- Sources/_FoundationCShims/CMakeLists.txt
This copies the public headers to a known location in the build tree so that direct clients (before installation) can specify that directory as an include path when not building via a CMake dependency
> [CMake] Copy headers to known directory for direct client test builds

- Sources/FoundationEssentials/JSON/JSON5Scanner.swift
- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Hello again, friends!
This patch is the sequel to (#667) that fixes JSONDecoder's Int64 clamping-esque behavior (#613). 
It also fixes a bug in \_parseJSON5Integer(\_:isHex:), which forgot to drop the sign for decimal inputs.
> Limit JSONDecoder's fallback Double path to lossless integer range

- Sources/_FoundationCShims/include/_CShimsTargetConditionals.h
Add the target conditional to identify android which is required to enable the package to build for Android.
> FoundationCShims: introduce `TARGET_OS_ANDROID`

- Sources/_FoundationCShims/string_shims.c
The `strncasecmp_l` was added at API level 23. For now, simply abort on older releases, though we should consider shimming the path.
> _FoundationCShims: enable building on Android

- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift
- Sources/FoundationEssentials/CodableUtilities.swift
- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Data/Data+Writing.swift
- Sources/FoundationEssentials/Data/Data.swift
- Sources/FoundationEssentials/Date.swift
- Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
- Sources/FoundationEssentials/Error/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/FileManager/FileManager+Basics.swift
- Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
- Sources/FoundationEssentials/FileManager/FileManager+SymbolicLinks.swift
- Sources/FoundationEssentials/FileManager/FileManager+Utilities.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
- Sources/FoundationEssentials/Formatting/BinaryInteger+NumericStringRepresentation.swift
- Sources/FoundationEssentials/LockedState.swift
- Sources/FoundationEssentials/Platform.swift
- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
- Sources/FoundationEssentials/PropertyList/OpenStepPlist.swift
- Sources/FoundationEssentials/String/String+Path.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationEssentials/_ThreadLocal.swift
This adds the necessary guards and includes for the Android modules. While the module does not compile currently due to nullability differences (and in some cases missing declarations), this at least brings the module to a point where we can start working on the errors and differences to create a maintainable codebase for Android.
> FoundationEssentials: initial pass to add Android support

- Sources/CMakeLists.txt
- Sources/FoundationEssentials/CMakeLists.txt
The macro can only be built for the host architecture (since that's where it runs and that's what the SwiftSyntax dependency is built for). This works on Linux because the host architecture is always the same as the architecture for which we build Foundation. However, when building the Windows toolchain, Foundation is built for a variety of architectures that may include those that are not the same as the host. In the fullness of time, we need to ensure the macros only build for the host architecture (either by splitting it out into a separate, single CMake invocation or by providing the architecture to the cmake build to override for the macro target). But in the short term, to unblock merging the Foundation re-core, this disables the macro on Windows toolchain builds to keep the ball …
> [CMake] Disable macros in Windows CMake build

- Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift
The Windows toolchain build for x86 was failing with:
```
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-foundation\Sources\FoundationEssentials\ProcessInfo\ProcessInfo.swift:141:34: error: cannot convert value of type 'DWORD' (aka 'UInt') to expected argument type 'UInt32'
139 |     var processIdentifier: Int32 {
140 | #if os(Windows)
141 |         return Int32(bitPattern: GetProcessId(GetCurrentProcess()))
|                                  `- error: cannot convert value of type 'DWORD' (aka 'UInt') to expected argument type 'UInt32'
142 | #else
143 |         return Int32(getpid())
```
[In SCL-F](https://github.com/apple/swift-corelibs-foundation/blob/ca3669eb9ac282c649e71824d9357dbe140c8251/Sources/Foundation/ProcessInfo.swift#L75) we just call …
> [Windows] Fix Int32(bitPattern:) call failure

- CMakeLists.txt
The GNUInstallDirs module sets CMAKE_INSTALL_BINDIR which is used on Windows as the destination for installed .dll files. This addresses issues that I saw when building a Windows toolchain where the .dll files were not installed into the toolchain previously, but with this change are correctly installed into the bin directory.
> [CMake] Include GNUInstallDirs

- Sources/FoundationEssentials/Data/Data+Reading.swift
- Sources/FoundationEssentials/Error/ErrorCodes+POSIX.swift
- Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift
- Sources/FoundationEssentials/FileManager/FileOperations.swift
This adjusts the API usage to account for differences on Android. The biggest source of difference is the nullability, particularly in the `fts` APIs. Unfortunately, `MMAP_FAILED` is not imported by the clang importer due to the casting involved so we manually inline the constant at the single site.
> FoundationEssentials: make build on Android

- Sources/FoundationEssentials/Data/Data.swift
This reverts commit 7fa9d1f4a948da4eeed3928946d0b458d2f3bcf6. It was found that the bridging of already bridged slices behavioral change causes regressions so this had to be backed out.
> Revert "Slices of no copy Data bridged to and back incorrectly account for the start index (#698)"

- Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
- Sources/FoundationInternationalization/Date+ICU.swift
- Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
- Sources/FoundationInternationalization/Formatting/Duration+Formatting.swift
This adds the missing imports for Android and enables building for Android.
> FoundationInternationalization: add `Android` imports

- Tests/FoundationEssentialsTests/DataIOTests.swift
DataIOTests.test_largeFile reads a larger than 2GB file twice into the memory. Adding `.mappedIfSafe` option when reading Data to prevent the test getting killed due to memory usage.
resolves: rdar://130769047
> Use .mappedIfSafe in DataIOTests.test_largeFile

- CMakeLists.txt
swift-collections v1.1.2 has a handful of CMake changes necessary for the swift-foundation build. This won't impact the swift toolchain build, but will update the version of swift-collections used when building swift-foundation in isolation and fetching swift-collections via dependency management.
> [CMake] Update swift-collections to 1.1.2

- Benchmarks/Benchmarks/Formatting/BenchmarkFormatting.swift
- Sources/FoundationEssentials/Calendar/Calendar.swift
- Sources/FoundationEssentials/Calendar/Calendar_Cache.swift
- Sources/FoundationEssentials/Formatting/FormatterCache.swift
- Sources/FoundationEssentials/Locale/Locale.swift
- Sources/FoundationEssentials/Locale/Locale_Autoupdating.swift
- Sources/FoundationEssentials/Locale/Locale_Cache.swift
- Sources/FoundationEssentials/Locale/Locale_Notifications.swift
- Sources/FoundationEssentials/LockedState.swift
- Sources/FoundationEssentials/String/String+Internals.swift
- Sources/FoundationEssentials/TimeZone/TimeZone.swift
- Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
- Sources/FoundationInternationalization/Calendar/Calendar_ObjC.swift
- Sources/FoundationInternationalization/Formatting/Number/ICUNumberFormatter.swift
- Sources/FoundationInternationalization/Locale/Locale_ICU.swift
- Sources/FoundationInternationalization/Locale/Locale_ObjC.swift
Improves the performance of formatting dates and times, especially when used in multithreaded contexts. 
This patch reworks some of the caching in the Locale, TimeZone, and Calendar types to more efficiently store the singleton values.
```
parallel-and-serialized-number-formatting
╒═══════════════════════════╤════════╕
│ Time (total CPU) (μs) *   │   6884 │
╘═══════════════════════════╧════════╛
parallel-number-formatting
╒═══════════════════════════╤════════╕
│ Time (total CPU) (μs) *   │   8330 │
╘═══════════════════════════╧════════╛
serialized-number-formatting
╒═══════════════════════════╤════════╕
│ Time (total CPU) (μs) *   │   1226 │
╘═══════════════════════════╧════════╛
```
```
parallel-and-serialized-number-formatting
╒═══════════════════════════╤════════╕
│ Time (total CPU) …
```
> Improve performance of FormatStyle formatting when used in multithreaded context

- Sources/FoundationEssentials/Data/Data+Writing.swift
On Windows, `_commit` can only be used for file descriptors backing files that are on disks. We would previously flush all file types which would cause an error.
Thanks to @z2oh for tracking down the cause of the error!
> FoundationEssentials: fix corner case of flushing file descriptor

- Foundation_Build_Process.md
- README.md
This adds a new build process document outlining all of the ways that we build Foundation and the details of each build variant. This also updates our main README to point to this document highlighting the getting started steps for building Foundation.
> [Documentation] Add new Build Process Document

- Sources/FoundationEssentials/PropertyList/XMLPlistEncodingFormat.swift
- Tests/FoundationEssentialsTests/PropertyListEncoderTests.swift
Historically `PropertyListEncoder` encodes whole-value reals _without_ the `.0` suffix. We should maintain this behavior.
> PropertyListEncoder should encode whole-value reals in XML without the .0 suffix for backward compatibility

- Sources/FoundationEssentials/Locale/CMakeLists.txt
This adds a forgotten file to the `CMakeLists.txt` file to get the CMake build working again
> [CMake] Add Locale_Notifications.swift

- Sources/FoundationEssentials/AttributedString/AttributedString.swift
- Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
`AttributedString` goes out of its way to emulate the stdlib’s behavior for `String` slicing. Unfortunately, it went a little overboard:
```swift
import Foundation
let str1 = "F\u{301}a\u{308}n\u{303}c\u{327}y\u{30a}" // "F́äñçẙ"
let str2 = AttributedString(str1)
let substr1 = str1[...str1.startIndex] // “F\u{301}”
let substr2 = str2[...str2.startIndex] // “F”
```
We expect slicing on range expressions to always produce  consistent results between `String` and `AttributedString`.
When slicing character-based string views on `…str.startIndex`, we naturally expect the range expression to cover the entire first `Character`, and that is precisely what `String` does.
`AttributedString`’s default view is not as obviously `Character`-based as `String` is, but emulating the stdlib’s behavior is …
> Fix AttributedString slicing behavior on range expressions

- Sources/FoundationEssentials/FileManager/FileManager+Files.swift
This implements the remaining attributes for `attributesOfItem(atPath:)` for windows. This is required for the Windows toolchain build because `TSCBasic` requires these attributes and `swiftc.exe` ends up calling down to this API while compiling SwiftPM manifests.
The implementation of all of these attributes comes from the existing sources in swift-corelibs-foundation (roughly).
> [Windows] Implement additional file attributes

- Sources/FoundationEssentials/String/String+Path.swift
- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
All of our `String`-based path processing assumes that the paths are standardized to forward slashes, however there are many sources (such as `FileManager`) where these paths may come in on Windows with backslashes resulting in incorrect path manipulation. This updates all of these functions to standardize to forward slashes where needed when performing path-related functions. On windows, these slashes will already be automatically changed back to backslashes if necessary by the file system representation functions.
_Note: this currently doesn't handle drive letters any differently than other path components. We can probably do better there, but this at least unblocks the toolchain work and gets us on-par with what SCL-F used to do_
> [Windows] Standardize slashes before path processing

- Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
This test attempts to test an optimization that is only present on Darwin (using `getattrlist` to resolve symlinks when possible). I encountered a situation on Windows on my local device where calling this function would standardize other portions of the path resulting in test failures. Since this test isn't applicable on non-Darwin anyways, this disables the test to ensure we don't hit accidental failures depending on local device setups.
In my device's case, the expected destination path was
```
C:\\Users\\jmschonfeld\\AppData\\Local\\Temp\\FileManagerPlayground_F2BEE091-140C-478E-91B2-1EBB08B88E5C\\destination
```
However calling this function was standardizing this to
```
C:\\Users\\JMSCHO~1\\AppData\\Local\\Temp\\FileManagerPlayground_F2BEE091-140C-478E-91B2-1EBB08B88E5C\\destination …
```
> Disable testResolveSymlinksViaGetAttrList() on non-Darwin

- Sources/FoundationEssentials/Date.swift
- Tests/FoundationEssentialsTests/DateTests.swift
Correct the constant value used for Date's current time calculation, and put in a smoke test for the result. Also, use `Double` here so we get sub-1s precision.
> Use correct calculation for Date's current time

- Sources/FoundationEssentials/Locale/Locale_Notifications.swift
There are some issues with using the `Synchronization` module from within the toolchain on Linux so for now we'll limit its usage to `FOUNDATION_FRAMEWORK` only
> Limit Synchronization usage to FOUNDATION_FRAMEWORK

- Sources/FoundationEssentials/Data/Data+Reading.swift
- Tests/FoundationEssentialsTests/DataIOTests.swift
Some files on Linux (such as those in `/proc`) report a size of `0` when stat-ing the files. However, these files do have contents, but the length is not able to be predetermined. On Linux, we now always attempt a read in chunks even if the file reports as empty and grow our buffer as necessary to accommodate the resulting size.
> Enable reading files of indeterminate length on Linux

- Sources/FoundationEssentials/Decimal/Decimal+Conformances.swift
- Sources/FoundationEssentials/Decimal/Decimal+Math.swift
- Tests/FoundationEssentialsTests/DecimalTests.swift
This patch pulls in numerous improvements and bug fixes to `Decimal` in `swift-corelibs-foundation`. Each commit in this PR corresponds to a (hand applied, modified if necessary) commit from the original `swift-corelibs-foundation` repo.
> Pull in swift-corelibs-foundation Decimal improvements

- Sources/FoundationEssentials/AttributedString/AttributeScope.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+AttributeTransformation.swift
- Sources/FoundationEssentials/AttributedString/AttributedString+Runs+AttributeSlices.swift
- Sources/FoundationEssentials/Predicate/Archiving/PredicateCodableConfiguration.swift
- Sources/FoundationEssentials/Predicate/Archiving/PredicateExpressionConstruction.swift
- Sources/FoundationEssentials/Predicate/PredicateExpression.swift
- Sources/FoundationEssentials/SortComparator.swift
- Sources/FoundationInternationalization/String/KeyPathComparator.swift
- Sources/FoundationInternationalization/String/SortDescriptor.swift
- Tests/FoundationEssentialsTests/PredicateCodableTests.swift
We previously reverted some sendable annotations in https://github.com/apple/swift-foundation/pull/679 due to a compiler bug around the IRGen for `KeyPath & Sendable` parameters. While the compiler bug is not yet resolved, this adds these annotations back in place using a workaround to prevent the compiler bug from causing issues on ABI stable platforms. This ensures that our public API is the most correct, and in the future when the bug is resolved we can remove the additional AEIC functions that serve as a workaround currently.
> Re-add sendable annotations

- Sources/FoundationEssentials/Locale/CMakeLists.txt
Reverts apple/swift-foundation#726
`Locale_Notifications.swift` was removed in https://github.com/apple/swift-foundation/pull/744
> Revert "[CMake] Add Locale_Notifications.swift"

- Sources/FoundationEssentials/Decimal/Decimal+Conformances.swift
- Sources/FoundationEssentials/Decimal/Decimal.swift
- Sources/FoundationEssentials/JSON/JSONDecoder.swift
- Tests/FoundationEssentialsTests/DecimalTests.swift
While I was here: imported more Decimal tests from swift-corelibs-foundation
> Decimal.init(sign:exponent:significand:) should clamp exponent
