swiftlang/swift-foundation

Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift
=> Fix typo in ICUDateFormatter.swift

Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift, Tests/FoundationInternationalizationTests/Formatting/DateIntervalFormatStyleTests.swift, Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift, Tests/FoundationInternationalizationTests/Formatting/ParseStrategy+RegexComponentTests.swift
- unifdef FIXED_106570987
- Update test expectations due to different ICU version used by FOUNDATION_FRAMEWORK.
- Update test result on FOUNDATION_FRAMEWORK
=> Re-enable ICU tests

Tests/FoundationEssentialsTests/LockedStateTests.swift
This PR adds a test to verify the behavior of `LockedState.withLockExtendingLifetimeOfState(_:)`.
The desired behavior is that the old state object not be deallocated until after the lock is released.
During the review of #107, we did not come up with a way to test the expected behavior of this method. An idea for testing it popped into my head, so I tried it out.
This test attempts to acquire the lock when the state object is deallocated. If the lock is still held at that point, the test fails. (Unfortunately, it fails by crashing, but I don't know a way around that.)
I ran this test with the implementations of `withLockExtendingLifetimeOfState` from both #97 (test failed) and #107 (test passed).
=> Add test to verify lifetime extension

Sources/FoundationInternationalization/Formatting/Number/ICUNumberFormatter.swift
Update currency codes in StringLocalization test, remove errant __bridge
Authored by @parkera.
rdar://107341898
=> Fix numerous leaks in tests

Sources/FoundationEssentials/Predicate/Archiving/EncodingContainers+PredicateExpression.swift, Sources/FoundationEssentials/Predicate/Archiving/ExpressionArchiving.swift, Sources/FoundationEssentials/Predicate/Archiving/Predicate+Codable.swift, Sources/FoundationEssentials/Predicate/NSPredicateConversion.swift, Sources/FoundationEssentials/Predicate/Predicate.swift, Tests/FoundationEssentialsTests/PredicateCodableTests.swift, Tests/FoundationEssentialsTests/PredicateTests.swift
Adds variadic input support for Predicate and its associated types and APIs
Resolves rdar://103142402
=> Variadic Generics Support for Predicate

Sources/FoundationInternationalization/Formatting/Date/ICUDateFormatter.swift, Sources/FoundationInternationalization/ICU/ICUPatternGenerator.swift
We cache the generated date format per `Date.FormatStyle`. Normally `Date.FormatStyle`'s locale change would result in a cache miss because the hash has changed. However, using `.autoupdating` is an edge case where this does not apply -- `Locale.autoupdating` always compares equal to itself even when the locale identifier or preferences are different. Therefore we end up fetching the stale value when the locale is `.autoupdating`.
Fix this by using the locale identifier instead of the locale instance as the hash key.
Follow up: encapsulate hour preferences in the locale identifier instead of setting it as a special override. We should use this pattern wherever possible.
=> Date.FormatStyle does not autoupdate when 12-24 hour preferences changes when using autoupdating locale

Sources/FoundationEssentials/Predicate/Archiving/ExpressionArchiving.swift, Tests/FoundationEssentialsTests/PredicateCodableTests.swift
This patch throws an error that ensures we won't crash if we encounter types with type parameter packs while encoding/decoding a predicate
=> Account for type parameter packs in Predicate coding

Sources/FoundationEssentials/UUID.swift, Sources/FoundationEssentials/UUID_Wrappers.swift
=> Fixed UUID lifetime

Sources/FoundationEssentials/JSON/JSONWriter.swift, Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Resolves rdar://107968842
Test portion partially resolves rdar://108071246
=> Fixed .sortedKeys performance regression

Sources/FoundationEssentials/Data/Data.swift
=> Add the missing availability marker to Data.replaceBytes

Package.swift, Sources/FoundationEssentials/AttributedString/AttributedString+CharacterView.swift, Sources/FoundationEssentials/AttributedString/AttributedString+Runs.swift, Sources/FoundationEssentials/AttributedString/AttributedString+UnicodeScalarView.swift, Sources/FoundationEssentials/AttributedString/Conversion.swift, Sources/FoundationEssentials/AttributedString/FoundationAttributes.swift, Sources/FoundationEssentials/Calendar/Calendar.swift, Sources/FoundationEssentials/Data/Data.swift, Sources/FoundationEssentials/JSON/JSONDecoder.swift, Sources/FoundationEssentials/JSON/JSONEncoder.swift, Sources/FoundationEssentials/Locale/Locale+Components.swift, Sources/FoundationEssentials/UUID.swift, Tests/FoundationEssentialsTests/JSONEncoderTests.swift, Tests/FoundationEssentialsTests/UUIDTests.swift
This PR introduces `Availability Macros` for `FoundationPreview`. 
Resolves rdar://113171218
=> Introduce Availability Macros for FoundationPreview

Sources/FoundationEssentials/TimeZone/TimeZone.swift
Added  documentation for Name Style in TimeZone.
=> Documentation for Name Style in TimeZone

Tests/FoundationEssentialsTests/PredicateTests.swift
This updates the unit test I recently added to use the `#Predicate` macro
=> Update PredicateTests.testDebugDescription() to use the #Predicate macro

Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift, Sources/FoundationEssentials/Calendar/DateComponents.swift, Tests/FoundationEssentialsTests/GregorianCalendarTests.swift, Tests/FoundationInternationalizationTests/CalendarTests.swift
The implementation largely follows ICU's calendar::add and calendar::roll.
=> [WIP Gregorian Calendar] Implement `date(byAdding components: DateComponents, to date: Date, wrappingComponents: Bool)`

README.md
Added description of Benchmark usage copied from swift-nio (https://github.com/apple/swift-nio/blob/main/README.md?plain=1)
=> Update README.md to add information on how to run Benchmarks

Package.swift, Sources/TestSupport/TestSupport.swift, Tests/FoundationInternationalizationTests/Formatting/DateFormatStyleTests.swift, Tests/FoundationInternationalizationTests/Formatting/DateIntervalFormatStyleTests.swift, Tests/FoundationInternationalizationTests/Formatting/ICUPatternGeneratorTests.swift
This PR updates our FoundationICU dependency to `0.0.4` (corresponds to `ICU 72.1`, the same version shipped in macOS Sonoma).
=> Update FoundationICU to 0.0.4

Sources/FoundationEssentials/AttributedString/AttributeScope.swift
The `LoadedScopeCache` had a bug in its handling of `Optional` dictionary values in which it would fail to store negative lookup results rather than storing a `nil` value in the dictionary. This switches the representation to use a custom `enum` rather than an `Optional` to ensure clarity and avoid this bug causing many unnecessary `dlopen` calls for lookup misses.
=> AttributeScope cache does not correctly store negative results

Sources/FoundationEssentials/Locale/Locale_Cache.swift
When resetting the autoupdating current locale, we should not take into account the current bundle for language-matching purposes.
Follow up for #342
=> Make sure to turn off bundle matching when resetting the autoupdating locale for testing purposes

Sources/FoundationEssentials/Platform.swift, Sources/FoundationEssentials/ProcessInfo/ProcessInfo+API.swift, Sources/FoundationEssentials/ProcessInfo/ProcessInfo+ObjC.swift, Sources/FoundationEssentials/ProcessInfo/ProcessInfo.swift, Sources/_CShims/include/platform_shims.h, Sources/_CShims/platform_shims.c, Tests/FoundationEssentialsTests/ProcessInfoTests.swift, Tests/FoundationInternationalizationTests/Formatting/NumberFormatStyleTests.swift
This patch introduces `ProcessInfo` (aka `NSProcessInfo`).
Resolves:
- https://github.com/apple/swift-foundation/issues/308
- rdar://115915507
=> Rewrite ProcessInfo in Swift

Proposals/0004-predicate-regex-support.md, Proposals/NNNN-predicate-regex-support.md
This proposal adds new APIs to support the use of regular expressions within predicates
=> [Proposal] Predicate Regex Support

Proposals/0005-rangeset-indexset-conversion.md, Proposals/NNNN-rangeset-indexset-conversion.md
This proposal adds new API to `RangeSet<Int>` and `IndexSet` to allow conversion between the two types
=> [Proposal] RangeSet/IndexSet Conversion

Sources/FoundationEssentials/Predicate/Archiving/ExpressionArchiving.swift, Sources/FoundationEssentials/Predicate/Archiving/Predicate+Codable.swift, Sources/FoundationEssentials/Predicate/Archiving/PredicateCodableConfiguration.swift, Sources/FoundationEssentials/Predicate/Expressions/PredicateEvaluation.swift, Tests/FoundationEssentialsTests/PredicateCodableTests.swift, Tests/FoundationEssentialsTests/PredicateTests.swift
This adds `Codable` support to the predicate evaluation operator
=> Codable support for PredicateExpressions.EvaluatePredicate

Proposals/0004-predicate-regex-support.md, Proposals/0005-rangeset-indexset-conversion.md
`SF-0004` and `SF-0005` has been accepted.
=> Update SF-0004, SF-0005 status

Sources/FoundationEssentials/FileManager/FileManager+Files.swift
Historically, `FileManager` has omitted extended attribute keys that produce empty data so this PR updates the implementation to match the historical behavior rather than throwing an error for a size of `0` which results in a trap due to `errno` being `0`.
=> Fix error handling for reading extended attributes

Proposals/0007-swift-subprocess.md
Update review manager and status
=> Update and rename NNNN-swift-subprocess.md to 0007-swift-subprocess.md

Sources/FoundationEssentials/IndexPath.swift, Sources/TestSupport/TestSupport.swift, Tests/FoundationEssentialsTests/IndexPathTests.swift
Bring `IndexPath` to FoundationEssentials.
=> Port IndexPath to FoundationEssentials

Sources/FoundationEssentials/ProcessInfo/ProcessInfo+ObjC.swift
Cleaned up unused code in `ProcessInfo`.
resolves: rdar://122976909
=> Cleanup unused code in ProcessInfo

Sources/FoundationEssentials/CodableUtilities.swift, Sources/FoundationEssentials/JSON/BufferViewCompatibility.swift, Sources/FoundationEssentials/JSON/JSON5Scanner.swift, Sources/FoundationEssentials/JSON/JSONDecoder.swift, Sources/FoundationEssentials/JSON/JSONEncoder.swift, Sources/FoundationEssentials/JSON/JSONScanner.swift, Sources/FoundationEssentials/JSON/JSONWriter.swift, Tests/FoundationEssentialsTests/JSONEncoderTests.swift
In preparation for the new implementation of PropertyListDecoder, update a few things in the JSONDecoder.
=> Update JSONDecoder to prepare for PropertyListDecoder

Proposals/0009-calendar-recurrence-rule.md, Proposals/NNNN-calendar-recurrence-rule.md
This pull request introduces a proposal for a new type, `Calendar.RecurrenceRule`, that allows to describe recurring events and calculate future occurrences.
=> Introduce proposal for Calendar.RecurrenceRule

Sources/FoundationEssentials/Error/CocoaError+FilePath.swift
Our recent rewrites of `Data`/`FileManager` have switched around whether we use `NSFilePathErrorKey` or `NSURLErrorKey` in some implementations. While we don't make any guarantees about which will be used in a given API, we can update the implementation to provide values for both keys for compatibility.
=> (124302607) Path-based CocoaErrors should use both NSFilePathErrorKey and NSURLErrorKey

Proposals/0008-notation-formatting-for-currencies.md
Review period ended with no pending feedback, so marking this as Accepted
=> Update 0008 Status to Accepted

Tests/FoundationInternationalizationTests/Formatting/DateIntervalFormatStyleTests.swift
ICU 74 made these changes:
1. "en_GB@hours=h12" used to return "am", but now it returns "AM".
2. The separator used to be a simple dash, but now it's dash with NNSP. This would also be an intentional change.
Update the test expectations, but disable the tests for now until ICU74 landed in all platforms.
Resolves 122765941
=> Update test expectation for upcoming ICU-74 change

Sources/FoundationEssentials/FileManager/FileManager+Directories.swift
Use the Windows APIs properly to compute the current working directory. Query the required storage before performing the allocation and then use temporary storage to acquire a buffer. This repairs some of the build errors encountered when building on Windows.
=> FoundationEssentials: repair `FileManager.currentDirectoryPath` on Win32

Sources/FoundationEssentials/String/String+Path.swift
Add an implementation for querying the user's home directory and for resolving symbolic links on Windows.
=> FoundationEssentials: implement some path utilities on Windows

Sources/FoundationEssentials/FileManager/FileManager+Directories.swift, Sources/FoundationEssentials/FileManager/FileOperations+Enumeration.swift, Sources/FoundationEssentials/WinSDK+Extensions.swift
Implement the directory enumeration operations in FileManager on Windows. The implementation uses the Win32 API surface to ensure that we can use the full features of the platform.
=> FoundationEssentials: support directory enumeration operations on Windows

Sources/FoundationEssentials/String/String+Internals.swift
The previous ObjC implementation of this function did not add objects to the autorelease pool, but the calls to `_fastCharacterContents` and `_fastCStringContents` implicitly retain+autorelease `self` here since those functions are `NS_RETURNS_INNER_POINTER`. Adding this `autoreleasepool` invocation ensures that we drain these items from the pool before returning so that we don't add to the pool
=> Add autorelease pool to __swiftFillFileSystemRepresentation

Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift
Use the Win32 APIs for environment access to ensure that we handle unicode values properly, adjust the logic to deal with encoding differences.
=> FoundationEssentials: tweak TimeZone handling for Windows

Sources/FoundationEssentials/AttributedString/FoundationAttributes.swift
=> Introduce `formatNumber` attribute for attributed strings

Sources/FoundationEssentials/Data/Data+Writing.swift
Adjust for the Windows API usage. Similar to the reading case, truncate to the narrower types for path sharing in Windows.
=> FoundationEssentials: adjust API usage in Data writing

Sources/FoundationEssentials/String/String+IO.swift
Add a compatibility path for `String(bytes:encoding:)`. Some clients expected this to correctly handle null-terminated strings. This patch falls back on `NSString`'s behavior of producing a string with embedded nulls in some cases.
=> Add compatibility path for String(bytes:encoding:)

Sources/FoundationEssentials/FileManager/FileOperations.swift, Tests/FoundationEssentialsTests/FileManager/FileManagerTests.swift
Ensure that we call the callbacks at the appropriate time. Change the indentation and encapsulating scope to avoid a double callback.
=> FoundationEssentials: tweak `removeFile(_:with:)` on Windows

Sources/FoundationEssentials/String/String+Internals.swift
When trying to get the file system representation of a string, we may have previously used `appendingPathComponent(_:)` which will have used the incorrect separator. Ensure that all the separators are properly converted prior to returning the path.
=> FoundationEssentials: canonicalise the arc separator more aggressively

Sources/FoundationEssentials/String/String+EndianAdaptorSequence.swift, Sources/FoundationEssentials/String/StringProtocol+Essentials.swift
Unifies the UTF16/32 String-to-data path.
Results:
```
utf16-encode -- Linux, or macOS using Linux Implementation
╒═══════════════════════════╤═══════╕
│ Metric                    │  p100 │
├───────────────────────────┼───────┤
│ Time (wall clock) (μs) *  │  3918 │
╘═══════════════════════════╧═══════╛
utf16-encode - NSString
╒═══════════════════════════╤═══════╕
│ Metric                    │  p100 │
╞═══════════════════════════╪═══════╡
│ Time (wall clock) (μs) *  │   919 │
╘═══════════════════════════╧═══════╛
utf16-encode - Using _copyUTF16 plus other changes
╒═══════════════════════════╤══════╕
│ Metric                    │ p100 │
╞═══════════════════════════╪══════╡
│ Time (wall clock) (μs) *  │  568 │
╘═══════════════════════════╧══════╛
```
=> Unify UTF16 conversion path for String

Sources/FoundationEssentials/FileManager/FileManager+Files.swift
While I was removing some code from `FileManager` in SCL-F, I copied some of the WASI conditionals from that (now removed) code over here to swift-foundation
=> Add some WASI conditionals to FileManager

Sources/FoundationEssentials/Decimal/Decimal+Conformances.swift
=> Remove Decimal.zero because Decimal inherit it from AdditiveArithmetic

Sources/FoundationEssentials/Locale/Locale_Notifications.swift
Still check for presence of Synchronization module.
=> Still use canImport(Synchronization)

Sources/FoundationEssentials/String/String+Path.swift
There appear to be some instances where `confstr` can fail to create a temporary directory that are not the direct result of a programmer error. To accommodate this, we should handle this gracefully instead of aborting so that we fall through to either `TMPDIR` or `/tmp`.
=> Gracefully handle confstr failures

Sources/FoundationEssentials/Decimal/CMakeLists.txt, Sources/FoundationEssentials/Decimal/Decimal+Conformances.swift, Sources/FoundationEssentials/Decimal/Decimal+Math.swift, Sources/FoundationEssentials/Decimal/Decimal.swift, Sources/FoundationEssentials/JSON/JSONDecoder.swift, Tests/FoundationEssentialsTests/DecimalTests.swift
This patch implements Decimal arithmetics (plus, minus, power, etc) which completes Decimal's implementation.
=> Introduce Decimal arithmetics

CMakeLists.txt, Package.swift
This pulls in the latest CMake and build changes for swift-foundation-icu
=> Bump swift-foundation-icu to 0.0.9

Sources/FoundationEssentials/URL/URL.swift, Sources/FoundationEssentials/URL/URLComponents.swift
=> Missing visionOS availability for API_TO_BE_DEPRECATED

README.md
Update swift-syntax repository link in README.md
=> Update swift-syntax repository link in README.md

.gitignore
Remove some old and obsolete stuff from gitignore, and add support for other build directories and VSCode directories.
=> Modernize and update gitignore

Sources/FoundationEssentials/Calendar/RecurrenceRule.swift
As agreed in SF-0010. Resolves rdar://136704624
=> Make RecurrenceRule and its friends conform to Hashable

Sources/FoundationEssentials/JSON/JSONDecoder.swift
=> JSONDecoder should parse base64 via a buffer instead of creating a string

Sources/FoundationEssentials/JSON/JSONDecoder.swift, Sources/FoundationEssentials/PropertyList/PlistDecoderGeneric.swift, Tests/FoundationEssentialsTests/JSONEncoderTests.swift, Tests/FoundationEssentialsTests/PropertyListEncoderTests.swift
=> Provide concrete implementation of all decodeIfPresent API in KeyedContainerProtocol for JSONDecoder

Sources/FoundationEssentials/JSON/JSONEncoder.swift, Sources/FoundationEssentials/JSON/JSONWriter.swift, Tests/FoundationEssentialsTests/JSONEncoderTests.swift
This reverts commit 19abae74f8355948fec8c7265f08af4f05c689d2.
=> Revert "rdar://135836990 (JSONEncoder performance regressed from 5.10 toolchain to 6.0) (#1006)"

Sources/FoundationEssentials/JSON/JSONEncoder.swift, Sources/FoundationEssentials/JSON/JSONWriter.swift, Tests/FoundationEssentialsTests/JSONEncoderTests.swift
Same as #1006, but hopefully without the bugs this time.
=> rdar://135836990 (JSONEncoder performance regressed from 5.10 toolchain to 6.0)

Sources/FoundationEssentials/Formatting/FormatStyle.swift
Address #987. Please let me know if further modifications are needed. Thank you for reviewing my first contribution!
=> Adopt primary associated types to FormatStyle

Sources/FoundationEssentials/FileManager/FileOperations.swift
Regression after bb3fccfa360d00f63999ac8faf6ba37224ce5174
=> [android] fix 32-bit build

Sources/FoundationEssentials/Data/Data.swift, Tests/FoundationEssentialsTests/DataTests.swift
This is a confluence of a number of other fixes that exposed a flaw when combined - a UAF bug could occur when causing a retain of an underlying buffer from a no-copy initializer. This forces all bridging of no-copy cases to actually copy by robbing a bit from the capacity.
=> (140288075) Use-after-free in Swift implementation of NSData

CMakeLists.txt, Package.swift
=> Add `FoundationPreview 6.1` as an allowed availability annotation

Proposals/0015-attributedstring-tracking-indices.md
Per https://forums.swift.org/t/review-sf-0015-attributedstring-tracking-indices/77229/7, adds minor clarifications to the proposal based on discussions during API Review
=> [SF-0015] v2: minor clarifications from API review feedback

NNNN-Hindu-calendar-support-OOS.md
This proposal offers support for additional calendars.
=> Expanded calendar support

Proposals/0016-http-date-format.md
This proposal offers a "HTTP" date format for Foundation.
=> [Proposal] HTTP date format

Proposals/0000-template.md
Use SF as the proposal prefix and update the links placeholder
=> Update the proposal template

Sources/FoundationEssentials/Calendar/Calendar.swift, Sources/FoundationInternationalization/Calendar/Calendar_ICU.swift
Exposed identifiers for 12 calendars. API Proposal: [SF-017](https://github.com/swiftlang/swift-foundation/blob/main/Proposals/0017-expanded-calendar-support.md)
141795986
=> New Calendar Identifiers

Sources/FoundationEssentials/AttributedString/AttributeContainer.swift, Tests/FoundationEssentialsTests/AttributedString/AttributedStringTests.swift
Implements APIs to filter an `AttributeContainer`'s contents based on the constraints of the contained attributes
=> AttributeContainer Filtering

Proposals/0020-uri-templating.md
Update and rename 00020-uri-templating.md to 0020-uri-templating.md
=> Update and rename 00020-uri-templating.md to 0020-uri-templating.md

Sources/FoundationEssentials/Formatting/CMakeLists.txt
Follow-up to 63cfcb9bfde8153a9f385f60ee437fc45912a1dc
https://ci.swift.org/job/oss-swift-package-ubuntu-20_04/4052/console
=> build: Fix CMake build by adding missing source file

Sources/FoundationEssentials/Locale/Locale.swift
Introduces the [preferredLocales](https://forums.swift.org/t/pitch-introduce-locale-preferredlocales/79900) API.
=> Introduce preferredLocales API

Sources/FoundationEssentials/Calendar/Calendar_Gregorian.swift, Tests/FoundationInternationalizationTests/CalendarTests.swift
Use proper overflow add function.
Resolves 144178080
=> ASAN error in _CalendarGregorian calendar implementation

Proposals/0023-progress-reporter.md
Hello @chloe-yeo, thank you for your proposal about progress. I really appreciate your work on this.
I may be misunderstanding, but is the second assignment intended to target deadlineTracker rather than overall?
=> Update example to assign to deadlineTracker (if intended)
